### ISSUE TITLE
Unit tests don't pass on CI

### ISSUE THREAD

**Issue by Ermesx** [OrchardCMS/Orchard#5180]
I forked orchard repo and connected it with AppVeyor CI to provide autobuilds and tests for my commits, but I encountered some problems with tests.
Issue  appears when I want to build branch 1.x and looks like below:
<pre>nunit-console.exe "C:\projects\orchard\src\Orchard.Core.Tests\bin\Release\Orchard.Core.Tests.dll" "C:\projects\orchard\src\Orchard.Core.Tests\bin\Release\Orchard.Framework.Tests.dll" "C:\projects\orchard\src\Orchard.Core.Tests\bin\Release\Orchard.Tests.Modules.dll" "C:\projects\orchard\src\Orchard.Web\Modules\Orchard.Projections\Tests\bin\Orchard.Projections.Tests.dll" "C:\projects\orchard\src\Orchard.Web\Modules\Orchard.Tokens\Tests\bin\Orchard.Tokens.Tests.dll" "C:\projects\orchard\src\Orchard.Web.Tests\bin\Release\Orchard.Web.Tests.dll" "C:\projects\orchard\src\Tools\Orchard.Tests\bin\Release\Orchard.Tests.dll"
NUnit-Console version 2.6.3.13283
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.
 
Runtime Environment - 
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 2.0.50727.8009 ( Net 3.5 )
 
ProcessModel: Default    DomainUsage: Multiple
Execution Runtime: net-3.5
Unhandled Exception:
System.IO.FileLoadException: Could not load file or assembly 'Autofac, Version=3.4.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Autofac, Version=3.4.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da'
 
Server stack trace: 
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at NUnit.Core.CoreExtensions.InstallAdhocExtensions(Assembly assembly)
   at NUnit.Core.Builders.TestAssemblyBuilder.Load(String path)
   at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, Boolean autoSuites)
   at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, String testName, Boolean autoSuites)
   at NUnit.Core.TestSuiteBuilder.BuildSingleAssembly(TestPackage package)
   at NUnit.Core.TestSuiteBuilder.Build(TestPackage package)
   at NUnit.Core.SimpleTestRunner.Load(TestPackage package)
   at NUnit.Core.ProxyTestRunner.Load(TestPackage package)
   at NUnit.Core.ProxyTestRunner.Load(TestPackage package)
   at NUnit.Core.RemoteTestRunner.Load(TestPackage package)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
 
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Core.TestRunner.Load(TestPackage package)
   at NUnit.Util.TestDomain.Load(TestPackage package)
   at NUnit.Util.AggregatingTestRunner.Load(TestPackage package)
   at NUnit.Core.ProxyTestRunner.Load(TestPackage package)
   at NUnit.Util.RemoteTestAgent.AgentRunner.Load(TestPackage package)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
 
Exception rethrown at [1]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Core.TestRunner.Load(TestPackage package)
   at NUnit.Core.ProxyTestRunner.Load(TestPackage package)
   at NUnit.Util.ProcessRunner.Load(TestPackage package)
   at NUnit.ConsoleRunner.ConsoleUi.Execute(ConsoleOptions options)
   at NUnit.ConsoleRunner.Runner.Main(String[] args)
 
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
 
Command exited with code -100</pre>
[Build with issue](https://ci.appveyor.com/project/Ermesx/orchard/build/1.0.10)

**Comment by thekaveman** [comment]
For the 1.x build, you should be targeting .NET 4.5.1

**Comment by Ermesx** [comment]
@thekaveman You are right but problem is even deeper. AppVeyor has installed .NET 4.5.1 but when I exact clr .NET 4.5 for nunit it shows me:
<pre>nunit-console.exe "C:\projects\orchard\src\Orchard.Core.Tests\bin\Release\Orchard.Core.Tests.dll" "C:\projects\orchard\src\Orchard.Core.Tests\bin\Release\Orchard.Framework.Tests.dll" "C:\projects\orchard\src\Orchard.Core.Tests\bin\Release\Orchard.Tests.Modules.dll" "C:\projects\orchard\src\Orchard.Web\Modules\Orchard.Projections\Tests\bin\Orchard.Projections.Tests.dll" "C:\projects\orchard\src\Orchard.Web\Modules\Orchard.Tokens\Tests\bin\Orchard.Tokens.Tests.dll" "C:\projects\orchard\src\Orchard.Web.Tests\bin\Release\Orchard.Web.Tests.dll" "C:\projects\orchard\src\Tools\Orchard.Tests\bin\Release\Orchard.Tests.dll" /framework:net-4.5
NUnit-Console version 2.6.3.13283
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.
 
Runtime Environment - 
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 2.0.50727.8009 ( Net 3.5 )
 
ProcessModel: Default    DomainUsage: Multiple
Execution Runtime: net-4.5</pre>
[Here](http://help.appveyor.com/discussions/problems/1625-nunit-not-picking-up-net-framework-version) I found topic about it.
It means that in order to resolve this issue nUnit console should be upgraded to v3.0.
So let's do it task #5136 :+1: 

*I split this issue because Scripting.DLR tests belong to another case*

**Comment by Ermesx** [comment]
@thekaveman I used NUnit from Orchard libs and I have the same issue.
The CLR Version: 4.0.30319.34209 ( Net 4.0.30319.34209 ) - means .NET 4.5.2
<pre>C:\projects\orchard\lib\nunit\nunit-console.exe "C:\projects\orchard\src\Orchard.Core.Tests\bin\Release\Orchard.Core.Tests.dll" "C:\projects\orchard\src\Orchard.Core.Tests\bin\Release\Orchard.Framework.Tests.dll" "C:\projects\orchard\src\Orchard.Core.Tests\bin\Release\Orchard.Tests.Modules.dll" "C:\projects\orchard\src\Orchard.Web\Modules\Orchard.Projections\Tests\bin\Orchard.Projections.Tests.dll" "C:\projects\orchard\src\Orchard.Web\Modules\Orchard.Tokens\Tests\bin\Orchard.Tokens.Tests.dll" "C:\projects\orchard\src\Orchard.Web.Tests\bin\Release\Orchard.Web.Tests.dll" "C:\projects\orchard\src\Tools\Orchard.Tests\bin\Release\Orchard.Tests.dll" /framework:net-4.0
NUnit version 2.5.2.9222
Copyright (C) 2002-2009 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.
 
Runtime Environment - 
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 4.0.30319.34209 ( Net 4.0.30319.34209 )
 
ProcessModel: Default    DomainUsage: Multiple
Execution Runtime: net-4.0
Unhandled Exception:
System.IO.FileLoadException: Could not load file or assembly 'Autofac, Version=3.4.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Autofac, Version=3.4.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da'</pre>

**Comment by lihuishe** [comment]
Having the same problem. @Ermesx did you solve this eventually?
