### ISSUE TITLE
Orchard Layouts Problems with Element Blueprint Based off of Content Parts

### ISSUE THREAD

**Issue by emeraldarcher** [OrchardCMS/Orchard#5302]
I get the following error in the logs when I try to create an Element Blueprint from my custom Part.

2015-05-19 17:21:49,265 [180] Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator - Default - NullReferenceException thrown from IContentPartDriver by Orchard.Layouts.Drivers.LayoutPartDriver
 http://localhost:27547/Admin/Contents/Create/Layout
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.Layouts.Services.ElementFactory.Activate(ElementDescriptor descriptor, Action`1 initialize)
   at Orchard.Layouts.Services.ElementManager.ActivateElement(ElementDescriptor descriptor, Action`1 initialize)
   at Orchard.Layouts.Providers.BlueprintElementHarvester.<HarvestElements>b__8(<>f__AnonymousType7`2 <>h__TransparentIdentifier1)
   at System.Linq.Enumerable.<>c__DisplayClass12`3.<CombineSelectors>b__11(TSource x)
   at System.Linq.Enumerable.<>c__DisplayClass12`3.<CombineSelectors>b__11(TSource x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Orchard.Layouts.Providers.BlueprintElementHarvester.HarvestElements(HarvestElementsContext context)
   at Orchard.Layouts.Services.ElementManager.<>c__DisplayClass7.<>c__DisplayClassc.<DescribeElements>b__3(ElementHarvester harvester)
   at System.Linq.Enumerable.<SelectManyIterator>d__31`3.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Orchard.Layouts.Services.ElementManager.<>c__DisplayClass7.<DescribeElements>b__2(AcquireContext`1 acquireContext)
   at Orchard.Caching.Cache`2.CreateEntry(TKey k, Func`2 acquire) in z:\Builds\work\bd725928c3da365b\src\Orchard\Caching\Cache.cs:line 57
   at Orchard.Caching.Cache`2.<>c__DisplayClass2.<Get>b__0(TKey k) in z:\Builds\work\bd725928c3da365b\src\Orchard\Caching\Cache.cs:line 19
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at Orchard.Caching.Cache`2.Get(TKey key, Func`2 acquire) in z:\Builds\work\bd725928c3da365b\src\Orchard\Caching\Cache.cs:line 17
   at Orchard.Caching.DefaultCacheManager.Get[TKey,TResult](TKey key, Func`2 acquire) in z:\Builds\work\bd725928c3da365b\src\Orchard\Caching\DefaultCacheManager.cs:line 33
   at Orchard.Layouts.Services.ElementManager.DescribeElements(DescribeElementsContext context)
   at Orchard.Layouts.Services.ElementManager.<>c__DisplayClass10.<GetCategories>b__e(AcquireContext`1 acquireContext)
   at Orchard.Caching.Cache`2.CreateEntry(TKey k, Func`2 acquire) in z:\Builds\work\bd725928c3da365b\src\Orchard\Caching\Cache.cs:line 57
   at Orchard.Caching.Cache`2.<>c__DisplayClass2.<Get>b__0(TKey k) in z:\Builds\work\bd725928c3da365b\src\Orchard\Caching\Cache.cs:line 19
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at Orchard.Caching.Cache`2.Get(TKey key, Func`2 acquire) in z:\Builds\work\bd725928c3da365b\src\Orchard\Caching\Cache.cs:line 17
   at Orchard.Caching.DefaultCacheManager.Get[TKey,TResult](TKey key, Func`2 acquire) in z:\Builds\work\bd725928c3da365b\src\Orchard\Caching\DefaultCacheManager.cs:line 33
   at Orchard.Layouts.Services.ElementManager.GetCategories(DescribeElementsContext context)
   at Orchard.Layouts.Services.LayoutEditorFactory.GetCategories(IContent content)
   at Orchard.Layouts.Services.LayoutEditorFactory.GetConfigurationData(IContent content)
   at Orchard.Layouts.Services.LayoutEditorFactory.Create(String layoutData, String sessionKey, Nullable`1 templateId, IContent content)
   at Orchard.Layouts.Services.LayoutEditorFactory.Create(LayoutPart layoutPart)
   at Orchard.Layouts.Drivers.LayoutPartDriver.<>c__DisplayClass12.<Editor>b__11()
   at Orchard.ContentManagement.Drivers.ContentPartDriver`1.<>c__DisplayClass15.<ContentShape>b__14(BuildShapeContext ctx) in z:\Builds\work\bd725928c3da365b\src\Orchard\ContentManagement\Drivers\ContentPartDriver.cs:line 196
   at Orchard.ContentManagement.Drivers.ContentPartDriver`1.<>c__DisplayClass1b.<ContentShapeImplementation>b__1a(BuildShapeContext ctx) in z:\Builds\work\bd725928c3da365b\src\Orchard\ContentManagement\Drivers\ContentPartDriver.cs:line 205
   at Orchard.ContentManagement.Drivers.ContentShapeResult.ApplyImplementation(BuildShapeContext context, String displayType) in z:\Builds\work\bd725928c3da365b\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 45
   at Orchard.ContentManagement.Drivers.ContentShapeResult.Apply(BuildEditorContext context) in z:\Builds\work\bd725928c3da365b\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 25
   at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.<>c__DisplayClassd.<BuildEditor>b__c(IContentPartDriver driver) in z:\Builds\work\

**Comment by emeraldarcher** [comment]
Closed, meant to put this in a discussion not an issue area.

**Comment by emeraldarcher** [comment]
Thought there was just some user error on my part but I've tried creating a dummy content part with a few fields through the Orchard GUI and got the same result when trying to create an element blueprint based off of the new part.

**Comment by sfmskywalker** [comment]
I can't reproduce the issue. Can you try again with the latest code in the 1.9.x branch and reopen the issue if you can still repro?
