### ISSUE TITLE
Setup fails for tenants whose name starts with a number

### ISSUE THREAD

**Issue by ryanwawr** [OrchardCMS/Orchard#5343]
I have been playing around with Orchard's multitenant functionality over the last few days in preparation for moving several of our websites to a multitenant setup. I've found that, when I create a tenant whose name starts with a number (I tried 2014Test), I get the following error once for each existing tenant when I try to cook from the setup page.

```
2015-06-01 10:18:45,706 [35] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default
 (null)
System.Xml.XmlException: Name cannot begin with the '2' character, hexadecimal value 0x32. Line 6, position 4.
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at Orchard.Environment.Descriptor.ShellDescriptorCache.Fetch(String name)
   at Orchard.Environment.ShellBuilders.ShellContextFactory.CreateShellContext(ShellSettings settings)
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__7(ShellSettings settings)
```

I tried deleting or renaming the tenant, but, in both cases, the whole site breaks. All I see when I try to load the default site or any of the tenants is a 404 page with no specific errors, and the above error message printed to the log.

**Comment by Piedone** [comment]
How did you create the tenants? Because this is expected and there is validation to prevent creating sites with invalid names in Orchard.MultiTenancy.

**Comment by ryanwawr** [comment]
Under "Add a Tenant" I entered the name and URL prefix, selected "Allow the tenant to set up the database", then clicked "Set Up" and filled in the rest on the Orchard set up page. It made sense that the validation prevented the tenant site from being created, I just didn't expect the rest of the site to break after I deleted the tenant folder from App_Data/Sites. I tried copying the deleted folder back in, but it was still giving me 404 errors for the default site and valid tenants.

**Comment by DanielStolt** [comment]
We have a tenant named "21" here and it works fine, both creation and setup.

**Comment by SzymonSel** [comment]
> I tried deleting or renaming the tenant, but, in both cases, the whole site breaks.
Rename the site's folder and tenant name in Settings.txt to fix the issue.

**Comment by sebastienros** [comment]
Closing this one and following up on the related
