### ISSUE TITLE
Audit Trail trimming causes error

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#5478]
I have enabled trimming of the audit trail and get the following error every minute (or 30 seconds... it happens a lot)
```
System.InvalidOperationException: Sequence contains more than one element
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
   at Orchard.Data.Repository`1.Get(Expression`1 predicate)
   at Orchard.Data.Repository`1.Orchard.Data.IRepository<T>.Get(Expression`1 predicate)
   at Orchard.TaskLease.Services.TaskLeaseService.Acquire(String taskName, DateTime expiredUtc)
   at Orchard.AuditTrail.Services.AuditTrailTrimmingBackgroundTask.Sweep()
```
stacktrace
```
 at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
   at Orchard.Data.Repository`1.Get(Expression`1 predicate)
   at Orchard.Data.Repository`1.Orchard.Data.IRepository<T>.Get(Expression`1 predicate)
   at Orchard.TaskLease.Services.TaskLeaseService.Acquire(String taskName, DateTime expiredUtc)
   at Orchard.AuditTrail.Services.AuditTrailTrimmingBackgroundTask.Sweep()
```

**Comment by dcinzona** [comment]
Had to disable trimming due to this error.  It only seems to happen in the production deployment.  The QA deployment does not produce the error.

**Comment by dcinzona** [comment]
I noticed that the table `Orchard_TaskLease_TaskLeaseRecord` contained two records for the same task name: `Orchard.AuditTrail.Services.AuditTrailTrimmingBackgroundTask` but differentiated in Machine Name.

The query is passing in SingleOrDefault which errors out because it is only searching on TaskName and not taking machine name into account.  Now, not sure if this was related to the migration from Cloud Services to Azure Web Apps or if this is just a general bug, but deleting one of the rows has resolved the issue.  

May need to update this so that the tasks take machine name into account, unless that breaks something else?

**Comment by Piedone** [comment]
This is the same issue as in #5621. Will be fixed with a new way of farm-wide locking.
