### ISSUE TITLE
Could not sync database state with session

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#5480]
I'm not sure what is causing this, but it appears that every few hours, we get the following error in the logs

Message
```
Could not synchronize database state with session
```

Exception
```
NHibernate.StaleStateException: Batch update returned unexpected row count from update; actual row count: 1; expected: 2
   at NHibernate.AdoNet.Expectations.VerifyOutcomeBatched(Int32 expectedRowCount, Int32 rowCount)
   at NHibernate.AdoNet.SqlClientBatchingBatcher.DoExecuteBatch(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatchWithTiming(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatch()
   at NHibernate.Engine.ActionQueue.ExecuteActions(IList list)
   at NHibernate.Engine.ActionQueue.ExecuteActions()
   at NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)
```

Stacktrace
```
at NHibernate.AdoNet.Expectations.VerifyOutcomeBatched(Int32 expectedRowCount, Int32 rowCount)
   at NHibernate.AdoNet.SqlClientBatchingBatcher.DoExecuteBatch(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatchWithTiming(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatch()
   at NHibernate.Engine.ActionQueue.ExecuteActions(IList list)
   at NHibernate.Engine.ActionQueue.ExecuteActions()
   at NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)
```

I've been trying to locate the cause of the error, and am unable to flush it out.  Has anyone else seen these errors?  Seems to happen when running on multiple instances (Azure Web Apps and Cloud Services)

**Comment by Piedone** [comment]
Are you running Syscache by chance? Any 2nd-level NHibernate cache without a shared state will cause this in a multi-node setup.

**Comment by dcinzona** [comment]
We do not have Syscache enabled.  We only have Redis output caching enabled (and the required dependencies).
![capture](https://cloud.githubusercontent.com/assets/52411/8533275/01459094-2402-11e5-941e-4836e86e2ac3.PNG)

**Comment by dcinzona** [comment]
By the way, this isn't once a day.  It's many times.  6 times in the last 24 hours.

**Comment by sfmskywalker** [comment]
Do you know since when this started happening?

**Comment by dcinzona** [comment]
We trim the log every 30 days... so I can't see anything past that, but in the last 30 days, it's been logged 436 times.  This has been happening since we launched.  We've always been in Azure with Orchard, we just migrated from cloud services to azure web apps, but the database has been constant.  We also upgraded to Azure SQL databases to V12 after it went GA.  Then a few weeks ago we moved over to an Azure SQL Elastic pool in hopes of maintaining more concurrency.

But to answer your question more directly, I don't have an exact date or event that triggered it...it just sort of started showing up and has been there pretty consistently since I can remember.

![screen shot 2015-07-09 at 1 08 16 pm](https://cloud.githubusercontent.com/assets/52411/8601722/d0d8c6d8-263b-11e5-9855-adbd2562e7e3.png)

**Comment by sfmskywalker** [comment]
That's fine, it's just to get an idea of when this may have started happening. Thanks for all the details!

**Comment by dcinzona** [comment]
No problem!  Let me know if there's anything else I can do to help.

**Comment by sebastienros** [comment]
Do you have any triggers in your database?

**Comment by Piedone** [comment]
On a side note... @dcinzona what's the log analyzer you've shown the screenshot from?

**Comment by dcinzona** [comment]
I'm using elastic search with kibana for logging. It's fantastic

**Comment by dcinzona** [comment]
Sorry, we don't have any triggers set up in the DB.  We are using the standard, unmodified DB for Orchard on SQL Azure.

For the elasticsearch integration, we are using the .net wrapper and our own logging and audit module.
https://www.elastic.co/products/elasticsearch
https://github.com/elastic/elasticsearch-net

**Comment by dcinzona** [comment]
Unfortunately, we are still experiencing this problem with 1.9.2

**Comment by peterkeating** [comment]
@dcinzona Did you ever find a solution for this issue? Experience the same problem with 1.9.2.

**Comment by dcinzona** [comment]
It's still happening for us. Both on QA and PROD.

On Feb 2, 2016, at 10:00 AM, Peter Keating <notifications@github.com<mailto:notifications@github.com>> wrote:


@dcinzona<https://github.com/dcinzona> Did you ever find a solution for this issue? Experience the same problem with 1.9.2.

-

**Comment by peterkeating** [comment]
@dcinzona do you have any scheduled tasks setup? I setup a similar environment on my local environment and enabled logging of SQL queries run by NHibernate. The offending query for was deleting a scheduled task from the database (see log below).

I would say the error I'm getting is slightly different to yours as you get `actual row count: 1; expected: 2` and I get `actual row count: 0; expected: 1`.

When I disable the scheduled tasks the errors disappear, suggesting there is an issue with Scheduling in a multi node setup. I'm wondering if there is something I've not setup right that enables Scheduling to work in a multi node setup.

```
command 0:DELETE FROM Scheduling_ScheduledTaskRecord WHERE Id = @p0;@p0 = 41457 [Type: Int32 (0)]

2016-02-21 13:12:26,930 [7] NHibernate.Event.Default.AbstractFlushingEventListener - (null) - Could not synchronize database state with session
NHibernate.StaleStateException: Batch update returned unexpected row count from update; actual row count: 0; expected: 1
   at NHibernate.AdoNet.Expectations.VerifyOutcomeBatched(Int32 expectedRowCount, Int32 rowCount)
   at NHibernate.AdoNet.SqlClientBatchingBatcher.DoExecuteBatch(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatchWithTiming(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatch()
   at NHibernate.Engine.ActionQueue.ExecuteActions(IList list)
   at NHibernate.Engine.ActionQueue.ExecuteActions()
   at NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)
2016-02-21 13:12:27,084 [7] Orchard.Core.Scheduling.Services.ScheduledTaskExecutor - (null) - Unable to process scheduled task #41457 of type FacebookFeed
NHibernate.StaleStateException: Batch update returned unexpected row count from update; actual row count: 0; expected: 1
   at NHibernate.AdoNet.Expectations.VerifyOutcomeBatched(Int32 expectedRowCount, Int32 rowCount)
   at NHibernate.AdoNet.SqlClientBatchingBatcher.DoExecuteBatch(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatchWithTiming(IDbCommand ps)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteBatch()
   at NHibernate.Engine.ActionQueue.ExecuteActions(IList list)
   at NHibernate.Engine.ActionQueue.ExecuteActions()
   at NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)
   at NHibernate.Event.Default.DefaultAutoFlushEventListener.OnAutoFlush(AutoFlushEvent event)
   at NHibernate.Impl.SessionImpl.AutoFlushIfRequired(ISet`1 querySpaces)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
   at NHibernate.Impl.AbstractQueryImpl2.List()
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Orchard.Utility.Extensions.ReadOnlyCollectionExtensions.ToReadOnlyCollection[T](IEnumerable`1 enumerable) in C:\local\1.9.2\src\Orchard\Utility\Extensions\ReadOnlyCollectionExtensions.cs:line 8
   at Orchard.Data.Repository`1.Orchard.Data.IRepository<T>.Fetch(Expression`1 predicate) in C:\local\1.9.2\src\Orchard\Data\Repository.cs:line 69
   at Orchard.Core.Scheduling.Services.ScheduledTaskManager.GetTasks(String taskType, Nullable`1 scheduledBeforeUtc) in C:\local\1.9.2\src\Orchard.Web\Core\Scheduling\Services\ScheduledTaskManager.cs:line 48
   at Example.TaskSchedulers.FacebookFeedTaskScheduler.ScheduleNextTask(DateTime date)
   at Example.TaskSchedulers.FacebookFeedTaskScheduler.Process(ScheduledTaskContext context)
   at Orchard.Core.Scheduling.Services.ScheduledTaskExecutor.Sweep() in C:\local\1.9.2\src\Orchard.Web\Core\Scheduling\Services\ScheduledTaskExecutor.cs:line 65
```
