### ISSUE TITLE
Orchard Redis Message Bus error

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#5508]
When toggling a module in our Azure web farm, we get an error stating the server was unable to connect to the Redis servers.
`An error occured while subscribing to ShellChanged`
```
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log)
   at Orchard.Redis.Configuration.RedisConnectionProvider.<>c__DisplayClass1.<GetConnection>b__0(String cfg)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orchard.Redis.Configuration.RedisConnectionProvider.GetConnection(String connectionString)
   at Orchard.Redis.MessageBus.RedisMessageBusBroker.Publish(String channel, String message)
   at Orchard.MessageBus.Services.DefaultMessageBus.Publish(String channel, String message)
   at Orchard.MessageBus.Services.DistributedShellTrigger.Orchard.Environment.Descriptor.IShellDescriptorManagerEventHandler.Changed(ShellDescriptor descriptor, String tenant)
   at Orchard.Events.DelegateHelper.<>c__DisplayClass2e`3.<BuildAction>b__2d(Object target, Object[] p)
   at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue)
   at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue)
```
This puts the instances out of sync.  The connection string for the shell state is the same as the connection string for output caching (which seems to be working).

**Comment by douwinga** [comment]
In case it helps at all, we had this same issue today when pushing code changes that had a migration with an update. We are using a self hosted web farm and Redis servers though.

**Comment by dcinzona** [comment]
So it still seems to be happening...
I restarted the web application by modifying the redis connection string in the web.config file and that brought everything back up.  But this is the second time it randomly disconnected and failed to reconnect to Redis.  There needs to be a graceful loss of connectivity.  Azure status isn't showing any issues.

**Comment by dcinzona** [comment]
Turns out this is 100% DNS.  We have the Azure Website connected to an azure VNET and had turned off the two DNS controllers in AD and changed the DNS settings in the VNET to a different server which was still active.  The trick was *syncing* the VNET certificates with the azure website because the DNS changes to the VNET did not get updated on the web app.  
Thanks KUDU console!!
