### ISSUE TITLE
Error when saving a content item (new or edit) with content permissions part

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#5523]
Since updating to Orchard 1.9 (and 1.9.1), whenever we create or edit a content item that contains the content permissions part, if we do not set permissions on the item, we received the following error:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Orchard.ContentPermissions.ViewModels.ContentPermissionsPartViewModel.SerializePermissions(IEnumerable`1 roleEntries)
   at Orchard.ContentPermissions.Drivers.ContentPermissionsPartDriver.Editor(ContentPermissionsPart part, IUpdateModel updater, Object shapeHelper)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at Orchard.ContentManagement.Drivers.ContentPartDriver`1.Orchard.ContentManagement.Drivers.IContentPartDriver.UpdateEditor(UpdateEditorContext context) in c:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\ContentManagement\Drivers\ContentPartDriver.cs:line 90
   at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.<>c__DisplayClass10.<UpdateEditor>b__f(IContentPartDriver driver) in c:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\ContentManagement\Drivers\Coordinators\ContentPartDriverCoordinator.cs:line 63
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger) in c:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\InvokeExtensions.cs:line 17
```
Has anyone else experienced this issue?

**Comment by dcinzona** [comment]
Figured out why the error is happening (basically, we are overriding the default content permissions view in our admin theme, but after saving the item and reloading the view, it fails to load the content permissions view that we created.  Going to try to figure out why it's failing to load on commit/save (post)
