### ISSUE TITLE
Error on upgrading to 1.9.1

### ISSUE THREAD

**Issue by jsiegmund** [OrchardCMS/Orchard#5589]
I was trying to upgrade to 1.9.1, but it's not working. I checked the logs and get the following: 

2015-07-29 16:51:18,165 [7] Orchard.Data.Migration.DataMigrationManager - (null) - An unexpected error occurred while applying migration on Orchard.MediaLibrary from version 6.
 (null)
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> NHibernate.Exceptions.GenericADOException: could not insert: [Orchard.Core.Settings.Metadata.Records.ContentPartDefinitionRecord][SQL: INSERT INTO Settings_ContentPartDefinitionRecord (Name, Hidden, Settings) VALUES (?, ?, ?); select SCOPE_IDENTITY()] ---> System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'Id', table 'jsiegmund_orchard.dbo.Settings_ContentPartDefinitionRecord'; column does not allow nulls. INSERT fails.

Any tips on what I can do to fix / prevent this?

**Comment by bleroy** [comment]
I could be wrong, but you seem to have corrupted data in the ContentPartDefinitionRecord table. You seem to have records in there with no Id. Make a backup of your database, then locate the faulty records and delete them. Then try again.

**Comment by jsiegmund** [comment]
That would be Settings_ContentPartDefinitionRecord I think? That table has a not null constraint for the id column, so there are no records without an Id in there. The error seems to indicate that Orchard is trying to insert a record with a NULL value for the id column, which is not valid because there is no auto generated id on that column, at least not in my database. But why it would do that?

**Comment by jsiegmund** [comment]
Okay so I took a different approach and ended up with different results. I copied my database to a local instance and got a clean install of Orchard. Copied the stuff you need to copy (read the manual for once) and fired it up. It works now, but when I go into the admin panel it says: 

"Some features need to be upgraded: Orchard.ContentTypes, Orchard.MediaLibrary"

When I try to upgrade the ContentTypes module:
"An error occured while updating the feature Orchard.ContentTypes: Error while running migration version 1 for Orchard.ContentTypes."

When I try to update the MediaLibrary module:
"An error occured while updating the feature Orchard.MediaLibrary: Error while running migration version 6 for Orchard.MediaLibrary."

**Comment by bleroy** [comment]
A full stack trace would help: there's nearly no usable information in the error messages alone. Also, maybe this should be closed and moved to forums.

**Comment by jsiegmund** [comment]
[SqlException (0x80131904): Cannot insert the value NULL into column 'Id', table 'jsiegmund_orchard.dbo.Settings_ShellFeatureRecord'; column does not allow nulls. INSERT fails.
The statement has been terminated.]
   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +2418094
   System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +5694468
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +285
   System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +3731
   System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() +58
   System.Data.SqlClient.SqlDataReader.get_MetaData() +89
   System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) +379
   System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest) +2064
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) +375
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) +53
   System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) +240
   System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior) +41
   System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader() +14
   NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd) +307
   NHibernate.Id.InsertSelectDelegate.ExecuteAndExtract(IDbCommand insert, ISessionImplementor session) +46
   NHibernate.Id.Insert.AbstractReturningDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder) +77

[GenericADOException: could not insert: [Orchard.Core.Settings.Descriptor.Records.ShellFeatureRecord][SQL: INSERT INTO Settings_ShellFeatureRecord (Name, ShellDescriptorRecord_id) VALUES (?, ?); select SCOPE_IDENTITY()]]
   NHibernate.Id.Insert.AbstractReturningDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder) +210
   NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Boolean[] notNull, SqlCommandInfo sql, Object obj, ISessionImplementor session) +205
   NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Object obj, ISessionImplementor session) +184
   NHibernate.Action.EntityIdentityInsertAction.Execute() +150
   NHibernate.Engine.ActionQueue.Execute(IExecutable executable) +25
   NHibernate.Event.Default.AbstractSaveEventListener.PerformSaveOrReplicate(Object entity, EntityKey key, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess) +497
   NHibernate.Event.Default.AbstractSaveEventListener.PerformSave(Object entity, Object id, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess) +298
   NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess) +124
   NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event) +35
   NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event) +63
   NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.PerformSaveOrUpdate(SaveOrUpdateEvent event) +89
   NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event) +203
   NHibernate.Impl.SessionImpl.FireSaveOrUpdate(SaveOrUpdateEvent event) +316
   NHibernate.Impl.SessionImpl.SaveOrUpdate(String entityName, Object obj) +311
   NHibernate.Engine.SaveUpdateCascadingAction.Cascade(IEventSource session, Object child, String entityName, Object anything, Boolean isCascadeDeleteEnabled) +66
   NHibernate.Engine.Cascade.CascadeToOne(Object parent, Object child, IType type, CascadeStyle style, Object anything, Boolean isCascadeDeleteEnabled) +148
   NHibernate.Engine.Cascade.CascadeAssociation(Object parent, Object child, IType type, CascadeStyle style, Object anything, Boolean isCascadeDeleteEnabled) +61
   NHibernate.Engine.Cascade.CascadeProperty(Object parent, Object child, IType type, CascadeStyle style, Object anything, Boolean isCascadeDeleteEnabled) +81
   NHibernate.Engine.Cascade.CascadeCollectionElements(Object parent, Object child, CollectionType collectionType, CascadeStyle style, IType elemType, Object anything, Boolean isCascadeDeleteEnabled) +396
   NHibernate.Engine.Cascade.CascadeCollection(Object parent, Object child, CascadeStyle style, Object anything, CollectionType type) +143
   NHibernate.Engine.Cascade.CascadeAssociation(Object parent, Object child, IType type, CascadeStyle style, Object anything, Boolean isCascadeDeleteEnabled) +124
   NHibernate.Engine.Cascade.CascadeProperty(Object parent, Object child, IType type, CascadeStyle style, Object anything, Boolean isCascadeDeleteEnabled) +81
   NHibernate.Engine.Cascade.CascadeOn(IEntityPersister persister, Object parent, Object anything) +369
   NHibernate.Event.Default.AbstractFlushingEventListener.CascadeOnFlush(IEventSource session, IEntityPersister persister, Object key, Object anything) +99
   NHibernate.Event.Default.AbstractFlushingEventListener.PrepareEntityFlushes(IEventSource session) +253
   NHibernate.Event.Default.AbstractFlushingEventListener.FlushEverythingToExecutions(FlushEvent event) +141
   NHibernate.Event.Default.DefaultFlushEventListener.OnFlush(FlushEvent event) +80
   NHibernate.Impl.SessionImpl.Flush() +346
   NHibernate.Transaction.AdoTransaction.Commit() +298
   Orchard.Data.SessionLocator.DisposeSession() in z:\Builds\work\9f6cd39ff0f68f41\src\Orchard\Data\SessionLocator.cs:75
   Orchard.Data.SessionLocator.Dispose() in z:\Builds\work\9f6cd39ff0f68f41\src\Orchard\Data\SessionLocator.cs:66
   Autofac.Core.Disposer.Dispose(Boolean disposing) +81
   Autofac.Util.Disposable.Dispose() +36
   Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing) +65
   Autofac.Util.Disposable.Dispose() +36
   Orchard.Environment.<>c__DisplayClass7.<.ctor>b__4() in z:\Builds\work\9f6cd39ff0f68f41\src\Orchard\Environment\WorkContextAccessor.cs:94
   Orchard.Environment.HttpContextScopeImplementation.System.IDisposable.Dispose() in z:\Builds\work\9f6cd39ff0f68f41\src\Orchard\Environment\WorkContextAccessor.cs:99
   Orchard.Mvc.Routes.<ProcessRequestAsync>d__7.MoveNext() in z:\Builds\work\9f6cd39ff0f68f41\src\Orchard\Mvc\Routes\ShellRoute.cs:181
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +71
   System.Web.HttpTaskAsyncHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +11
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9723757
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155


I'm ok with closing and moving to the forums. Is that the forums on codeplex or somewhere else?

**Comment by jsiegmund** [comment]
Stacktrace for the upgrade of the ContentTypes module. Somehow it all seems to revolve around inserting a record with a NULL id.

2015-07-30 22:11:23,501 [15] NHibernate.AdoNet.AbstractBatcher - (null) - Could not execute query: INSERT INTO Orchard_Framework_DataMigrationRecord (DataMigrationClass, Version) VALUES (@p0, @p1); select SCOPE_IDENTITY()
 (null)
System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Id', table 'jsiegmund_orchard.dbo.Orchard_Framework_DataMigrationRecord'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
ClientConnectionId:ff3afbb1-7f3d-43ab-bfe1-614971e5aa93
Error Number:515,State:2,Class:16
2015-07-30 22:11:23,503 [15] NHibernate.Util.ADOExceptionReporter - (null) - Cannot insert the value NULL into column 'Id', table 'jsiegmund_orchard.dbo.Orchard_Framework_DataMigrationRecord'; column does not allow nulls. INSERT fails.
The statement has been terminated.
 (null)
2015-07-30 22:11:23,504 [15] Orchard.Data.Migration.DataMigrationManager - Default - Error while running migration version 1 for Orchard.ContentTypes.
 http://localhost:44589/Admin/Modules/Features
NHibernate.Exceptions.GenericADOException: could not insert: [Orchard.Data.Migration.Records.DataMigrationRecord][SQL: INSERT INTO Orchard_Framework_DataMigrationRecord (DataMigrationClass, Version) VALUES (?, ?); select SCOPE_IDENTITY()] ---> System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'Id', table 'jsiegmund_orchard.dbo.Orchard_Framework_DataMigrationRecord'; column does not allow nulls. INSERT fails.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
   at NHibernate.Id.IdentityGenerator.InsertSelectDelegate.ExecuteAndExtract(IDbCommand insert, ISessionImplementor session)
   at NHibernate.Id.Insert.AbstractReturningDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   --- End of inner exception stack trace ---
   at NHibernate.Id.Insert.AbstractReturningDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Boolean[] notNull, SqlCommandInfo sql, Object obj, ISessionImplementor session)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Object obj, ISessionImplementor session)
   at NHibernate.Action.EntityIdentityInsertAction.Execute()
   at NHibernate.Engine.ActionQueue.Execute(IExecutable executable)
   at NHibernate.Event.Default.AbstractSaveEventListener.PerformSaveOrReplicate(Object entity, EntityKey key, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.AbstractSaveEventListener.PerformSave(Object entity, Object id, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListe

**Comment by bleroy** [comment]
Yes, CodePlex. A clean install probably doesn't do that much good if you're still using the same database. dbcc will fix any physical corruption of the database, but it won't fix any inconsistent data that you may have there. Depending on how much data you have, and what it looks like, you might want to export everything and reimport it back into a clean database. Backup everything first, of course, before you try that.

**Comment by bleroy** [comment]
Another thing: check the identity column settings in that table.

**Comment by jsiegmund** [comment]
Bingo, that's it I think. In the not-so-great working database the Id column is not a primary key / set up as identify. Going to try what happens when I manually change this. Guess I need to run a compare on a vanilla one vs mine. Thanks.
