### ISSUE TITLE
Exception in orchard.exe

### ISSUE THREAD

**Issue by qt1** [OrchardCMS/Orchard#5711]
Command line orchard fail due to an exception.

This happens in my configuration(which I am too lazy to describe so I'll prepare a PR)

```
Initializing Orchard session. (This might take a few seconds...)
27/08/2015 18:09:50: Virtual path: "/"
27/08/2015 18:09:50: Working directory: "F:\git_managed\github\Orchard_Ibn\src\T
ools\Orchard\bin\Debug"
27/08/2015 18:09:50: Detecting orchard installation root directory...
27/08/2015 18:09:50: Orchard root directory: "F:\git_managed\github\Orchard_Ibn\
src\Orchard.Web"
27/08/2015 18:09:50: Creating ASP.NET AppDomain for command agent...
27/08/2015 18:09:58: Starting Orchard session
Type "?" for help, "exit" to exit, "cls" to clear screen

orchard> feature list

Error executing command "feature list"
--------------------------------------------------------------------------------


The method or operation is not implemented.

Exception Details: System.NotImplementedException: The method or operation is no
t implemented.

Stack Trace:

[NotImplementedException: The method or operation is not implemented.]
   at System.Web.HttpRequestBase.get_HttpMethod()
   at Orchard.Localization.Selectors.ContentCultureSelector.GetCulture(HttpConte
xtBase context)
   at Orchard.Localization.Services.CurrentCultureWorkContext.<>c__DisplayClass4
_0.<GetCurrentCulture>b__0(ICultureSelector c) in F:\git_managed\github\Orchard_
Ibn\src\Orchard\Localization\Services\CurrentCultureWorkContext.cs:line 29
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`
2 predicate)
   at Orchard.Localization.Services.CurrentCultureWorkContext.GetCurrentCulture(
) in F:\git_managed\github\Orchard_Ibn\src\Orchard\Localization\Services\Current
CultureWorkContext.cs:line 28
   at Orchard.Localization.Services.CurrentCultureWorkContext.Get[T](String name
) in F:\git_managed\github\Orchard_Ibn\src\Orchard\Localization\Services\Current
CultureWorkContext.cs:line 19
   at Orchard.Environment.WorkContextImplementation.<>c__DisplayClass7_0`1.<Find
ResolverForState>b__0(IWorkContextStateProvider wcsp) in F:\git_managed\github\O
rchard_Ibn\src\Orchard\Environment\WorkContextImplementation.cs:line 32
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`
2 predicate)
   at Orchard.Environment.WorkContextImplementation.FindResolverForState[T](Stri
ng name) in F:\git_managed\github\Orchard_Ibn\src\Orchard\Environment\WorkContex
tImplementation.cs:line 32
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Fu
nc`2 valueFactory)
   at Orchard.Environment.WorkContextImplementation.GetState[T](String name) in
F:\git_managed\github\Orchard_Ibn\src\Orchard\Environment\WorkContextImplementat
ion.cs:line 27
   at Orchard.WorkContext.get_CurrentCulture() in F:\git_managed\github\Orchard_
Ibn\src\Orchard\WorkContext.cs:line 74
   at Orchard.Localization.Text.Get(String textHint, Object[] args) in F:\git_ma
naged\github\Orchard_Ibn\src\Orchard\Localization\Text.cs:line 29
   at Orchard.Modules.Commands.FeatureCommands.List(String[] featureNames)

--------------------------------------------------------------------------------

orchard>

```

**Comment by sebastienros** [comment]
FYI works for me on the current dev and 1.9x, there has been a bunch of fixes on this branch since your report.

**Comment by qt1** [comment]
Sorry I couldn't attend the triage today to discuss in person. 
Thanks for merging the PR.
This problem only appeared with a project with tenants and is possibly also related to another PR I am working on (#5604) so it is hard to describe a scenario. 

In any case the PR should fix the culture selection is it is a bit more robust now..
