### ISSUE TITLE
1.9.2 Media library recents link returns an error

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#5938]
This is because users may not have a ManageOwnMedia permissions and the result is null, causing an exception.
There might be a few issues going on here.  The permissions check is looking first for `ManageOwnMedia` in the Admin Controller, but in the `GetRootMediaFolder` method in the service, it is also checking for `ManageMediaContent`.  
In the case where it returns null, this line in the admin controller returns an error:
```cs
var rootMediaFolder = _mediaLibraryService.GetRootMediaFolder().MediaPath;
```

While this is a welcomed change, what happens if users want access to all media content, not just the stuff they uploaded?  i.e. we have multiple editors.  

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.MediaLibrary.Controllers.AdminController.RecentMediaItems(Int32 skip, Int32 count, String order, String mediaType)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
```

**Comment by dcinzona** [comment]
Duplicate of https://github.com/OrchardCMS/Orchard/issues/5891
