### ISSUE TITLE
DB Error - 1.9.1 Prepare requires an open connection

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#5953]
Issue:  1.9.1 error when querying a projection that has a thumbnail rewrite and the query is set to display mode `properties`...

I figured out how to resolve this issue, but I don't know exactly WHY it was resolved.  The resolution was to change the projection query from Properties to Content.  That solved the issue with the thumbnails not loading sometimes and causing the error listed below to appear in the logs (one error for each thumbnail that failed).

@pszmyd any ideas as to why Properties vs Content would cause this problem?

Rest of thread below
-----
Ok, so it looks like we are seeing some DB errors again… this time when trying to load thumbnails on the front end.
```
NHibernate.ADOException: While preparing SELECT this_.Id as Id31_2_, this_.Number as Number31_2_, this_.Published as Published31_2_, this_.Latest as Latest31_2_, this_.Data as Data31_2_, this_.ContentItemRecord_id as ContentI6_31_2_, contentite1_.Id as Id30_0_, contentite1_.Data as Data30_0_, contentite1_.ContentType_id as ContentT3_30_0_, contenttyp4_.Id as Id32_1_, contenttyp4_.Name as Name32_1_ FROM Orchard_Framework_ContentItemVersionRecord this_ inner join Orchard_Framework_ContentItemRecord contentite1_ on this_.ContentItemRecord_id=contentite1_.Id left outer join Orchard_Framework_ContentTypeRecord contenttyp4_ on contentite1_.ContentType_id=contenttyp4_.Id WHERE contentite1_.Id = @p0 and this_.Published = @p1 an error occurred ---> System.InvalidOperationException: Prepare requires an open and available Connection. The connection's current state is closed.
   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   at System.Data.SqlClient.SqlCommand.Prepare()
   at NHibernate.Driver.DriverBase.PrepareCommand(IDbCommand command)
   at NHibernate.AdoNet.AbstractBatcher.Prepare(IDbCommand cmd)
   --- End of inner exception stack trace ---
   at NHibernate.AdoNet.AbstractBatcher.Prepare(IDbCommand cmd)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes)
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results)
   at NHibernate.Impl.CriteriaImpl.List(IList results)
   at NHibernate.Impl.CriteriaImpl.List[T]()
   at Orchard.ContentManagement.DefaultContentManager.GetManyImplementation(QueryHints hints, Action`2 predicate)
   at Orchard.ContentManagement.DefaultContentManager.Get(Int32 id, VersionOptions options, QueryHints hints)
   at Orchard.ContentManagement.DefaultContentManager.Get(Int32 id, VersionOptions options)
   at Orchard.ContentManagement.DefaultContentManager.Get(Int32 id)
   at Orchard.ContentManagement.ContentGetExtensions.Get[T](IContentManager manager, Int32 id)
   at Orchard.MediaLibrary.Tokens.FieldTokens.MediaPart(MediaLibraryPickerField field)
   at Orchard.MediaLibrary.Tokens.FieldTokens.<Evaluate>b__b(MediaLibraryPickerField field)
   at Orchard.Tokens.Implementation.TokenManager.EvaluateContextImpl.EvaluateForImpl`1.Token(String token, Func`2 tokenValue)
   at Orchard.MediaLibrary.Tokens.FieldTokens.Evaluate(EvaluateContext context)
   at Orchard.Events.DelegateHelper.<>c__DisplayClass2b`2.<BuildAction>b__2a(Object target, Object[] p)
   at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue)
   at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue)
```
https://www.nflpa.com/news-events?page=2
```
 System.InvalidOperationException: Prepare requires an open and available Connection. The connection's current state is closed.
   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   at System.Data.SqlClient.SqlCommand.Prepare()
   at NHibernate.Driver.DriverBase.PrepareCommand(IDbCommand command)
   at NHibernate.AdoNet.AbstractBatcher.Prepare(IDbCommand cmd)
```
but the rest of the content loads fine… so there are open database connections??

The thumbnail shows up fine in Admin content index preview as well as in edit mode for the blog post...
We are using this rewrite rule to render the thumbnail in the projection query:
```
<img width="100" height="100" class="media-object" src="{Content.Fields.CustomBlogPostFieldsPart.Thumbnail.Url}">
```

**Comment by dcinzona** [comment]
So this is still happening.  I'm reaching out to a couple of different support providers, but is anyone else experiencing this?  This is now happening on a brand new blog post (on page 1)
https://www.nflpa.com/news-events

**Comment by dcinzona** [comment]
Wow, so I fixed this by selecting Content instead of Properties in the query settings...

This works:
![screen shot 2015-10-15 at 7 29 37 am](https://cloud.githubusercontent.com/assets/52411/10512469/96903cfc-730e-11e5-8ea3-aa7c780bb697.png)

This does not:
![screen shot 2015-10-15 at 7 29 47 am](https://cloud.githubusercontent.com/assets/52411/10512471/9b9373c2-730e-11e5-8fc6-bb8a242dc10e.png)

Anyone have any idea why this setting would produce database errors?

**Comment by sebastienros** [comment]
Can you try to repro on 1.9.2, we did some significant changes on the connection management.

**Comment by dcinzona** [comment]
Will do.  We have our QA environment running on 1.9.2 so all we need to do is update a few articles with thumbnails and test.

**Comment by dcinzona** [comment]
So we added a bunch of thumbnails on QA and page 2 now returns a completely different error that makes no results visible at all.  Page 3 and Page 1 work fine.

![screen shot 2015-10-15 at 3 12 35 pm](https://cloud.githubusercontent.com/assets/52411/10524764/2fcf0b24-734f-11e5-9344-1c9bcd6ce558.png)

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Orchard.ContentManagement.DefaultContentManagerSession.Store(ContentItem item) in G:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\ContentManagement\DefaultContentManagerSession.cs:line 12
   at Orchard.ContentManagement.DefaultContentManager.Get(Int32 id, VersionOptions options, QueryHints hints) in G:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\ContentManagement\DefaultContentManager.cs:line 231
   at Orchard.ContentManagement.DefaultContentManager.Get(Int32 id, VersionOptions options) in G:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\ContentManagement\DefaultContentManager.cs:line 131
   at Orchard.ContentManagement.DefaultContentManager.<GetManyByVersionId>b__31_1(ContentItemVersionRecord r) in G:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\ContentManagement\DefaultContentManager.cs:line 319
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at Orchard.ContentManagement.DefaultContentManager.GetManyByVersionId(IEnumerable`1 versionRecordIds, QueryHints hints) in G:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\ContentManagement\DefaultContentManager.cs:line 318
   at Orchard.ContentManagement.DefaultHqlQuery.Slice(Int32 skip, Int32 count) in G:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\ContentManagement\DefaultHqlQuery.cs:line 205
   at Orchard.Projections.Services.ProjectionManager.GetContentItems(Int32 queryId, Int32 skip, Int32 count)
   at Orchard.Projections.Drivers.ProjectionPartDriver.<>c__DisplayClass18_0.<Display>b__1(Object shape)
   at Orchard.ContentManagement.Drivers.ContentPartDriver`1.<>c__DisplayClass23_0.<ContentShape>b__0(BuildShapeContext ctx) in G:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\ContentManagement\Drivers\ContentPartDriver.cs:line 200
   at Orchard.ContentManagement.Drivers.ContentPartDriver`1.<>c__DisplayClass24_0.<ContentShapeImplementation>b__0(BuildShapeContext ctx) in G:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\ContentManagement\Drivers\ContentPartDriver.cs:line 205
   at Orchard.ContentManagement.Drivers.ContentShapeResult.ApplyImplementation(BuildShapeContext context, String displayType) in G:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 45
   at Orchard.ContentManagement.Drivers.ContentShapeResult.Apply(BuildDisplayContext context) in G:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 21
   at Orchard.ContentManagement.Drivers.CombinedResult.Apply(BuildDisplayContext context) in G:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\ContentManagement\Drivers\CombinedResult.cs:line 28
   at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.<>c__DisplayClass9_0.<BuildDisplay>b__0(IContentPartDriver driver) in G:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\ContentManagement\Drivers\Coordinators\ContentPartDriverCoordinator.cs:line 49
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger) in G:\TFS\NFLPA.com 2014\Dev-1.9\src\Orchard\InvokeExtensions.cs:line 17
```

**Comment by sebastienros** [comment]
Two fixes:
- the projection should not return the same version twice
- the DefaultContentManagerSession should not break if an item already exists

**Comment by sebastienros** [comment]
Or a bug in the database, where you would have a duplicate Id and Version number.

**Comment by dcinzona** [comment]
Ok, so this was the issue.  Our DB inserted duplicates with the same version number (version number 2 and version number 3).  This is running on 1.9.2 btw, when this happened.
When I deleted the duplicates (screenshot below), I was then able to restore it.
No idea why or how it would create duplicates but we are seeing similar duplicates with our user registration - happens seemingly randomly.

![screen shot 2015-10-15 at 4 07 06 pm](https://cloud.githubusercontent.com/assets/52411/10526134/f30f63ca-7356-11e5-8ccf-8a1b496f847c.png)

**Comment by dcinzona** [comment]
Btw, that screenshot is after I deleted the oldest duplicates

**Comment by sebastienros** [comment]
Database consistency issue. Please open the bug that incurred this consistency if you can repro it.

**Comment by dcinzona** [comment]
The original issue still persists.  When trying to reproduce it on QA, we surfaced the second issue... but on production, we still have the same problem with thumbnails not showing up when the query layout is set to properties.

**Comment by sebastienros** [comment]
Test

**Comment by dcinzona** [comment]
I'm planning to grab a copy of the production database and put it on my dev box so I can test locally to see if it's an issue with azure SQL, orchard, or the DB



On Oct 19, 2015, at 8:14 PM, S?bastien Ros <notifications@github.com<mailto:notifications@github.com>> wrote:


Test

-

**Comment by dcinzona** [comment]
So I restored the current production database to my local and ran 1.9.2 against my local after setting the query to use properties instead of Content.  My local database does not produce any errors on thumbnails and works fine.  There are two different setup with my local:
1. It is using the 1.9.2 code base
2. It is querying my local database instead of Azure SQL.

I'm going to look into downloading the current deployment on Azure and running THAT locally to see if it's an issue with 1.9.1 or Azure SQL.

**Comment by dcinzona** [comment]
Ok, so I've copied the 1.9.1 deployed code from the Azure Web App running in production to my local IIS.
I do not get the thumbnail issue on my local, which tells me there is an incompatibility with Azure SQL.  I'm not sure how to proceed here...

This is what I did:
1. Took a database backup from production and restored it locally
2. Took the code deployment from production and restored it locally
3. Changed Settings.TXT to point to my local database and started up IIS
4. Switched the Query Display Mode to Properties on both local and production:
![screen shot 2015-10-21 at 6 59 25 am](https://cloud.githubusercontent.com/assets/52411/10634647/55e52142-77c1-11e5-8c94-9e6aa154510c.png)
5. Went to the news landing page on local and on production.
5.a. Thumbnails appear fine on Local, no errors
5.b. Thumbnails are broken on production

Three errors are generated on the production database per thumbnail
First Error:
```
While preparing SELECT this_.Id as Id31_2_, this_.Number as Number31_2_, this_.Published as Published31_2_, this_.Latest as Latest31_2_, this_.Data as Data31_2_, this_.ContentItemRecord_id as ContentI6_31_2_, contentite1_.Id as Id30_0_, contentite1_.Data as Data30_0_, contentite1_.ContentType_id as ContentT3_30_0_, contenttyp4_.Id as Id32_1_, contenttyp4_.Name as Name32_1_ FROM Orchard_Framework_ContentItemVersionRecord this_ inner join Orchard_Framework_ContentItemRecord contentite1_ on this_.ContentItemRecord_id=contentite1_.Id left outer join Orchard_Framework_ContentTypeRecord contenttyp4_ on contentite1_.ContentType_id=contenttyp4_.Id WHERE contentite1_.Id = @p0 and this_.Published = @p1 an error occurred
```
Second Error:
```
Prepare requires an open and available Connection. The connection's current state is closed.
```
Third Error:
```
System.InvalidOperationException: Prepare requires an open and available Connection. The connection's current state is closed.
   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   at System.Data.SqlClient.SqlCommand.Prepare()
   at NHibernate.Driver.DriverBase.PrepareCommand(IDbCommand command)
   at NHibernate.AdoNet.AbstractBatcher.Prepare(IDbCommand cmd)
```
```
NHibernate.ADOException: While preparing SELECT this_.Id as Id31_2_, this_.Number as Number31_2_, this_.Published as Published31_2_, this_.Latest as Latest31_2_, this_.Data as Data31_2_, this_.ContentItemRecord_id as ContentI6_31_2_, contentite1_.Id as Id30_0_, contentite1_.Data as Data30_0_, contentite1_.ContentType_id as ContentT3_30_0_, contenttyp4_.Id as Id32_1_, contenttyp4_.Name as Name32_1_ FROM Orchard_Framework_ContentItemVersionRecord this_ inner join Orchard_Framework_ContentItemRecord contentite1_ on this_.ContentItemRecord_id=contentite1_.Id left outer join Orchard_Framework_ContentTypeRecord contenttyp4_ on contentite1_.ContentType_id=contenttyp4_.Id WHERE contentite1_.Id = @p0 and this_.Published = @p1 an error occurred ---> System.InvalidOperationException: Prepare requires an open and available Connection. The connection's current state is closed.
   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   at System.Data.SqlClient.SqlCommand.Prepare()
   at NHibernate.Driver.DriverBase.PrepareCommand(IDbCommand command)
   at NHibernate.AdoNet.AbstractBatcher.Prepare(IDbCommand cmd)
   --- End of inner exception stack trace ---
   at NHibernate.AdoNet.AbstractBatcher.Prepare(IDbCommand cmd)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes)
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results)
   at NHibernate.Impl.CriteriaImpl.List(IList results)
   at NHibernate.Impl.CriteriaImpl.List[T]()
   at Orchard.ContentManagement.DefaultContentManager.GetManyImplementation(QueryHints hints, Action`2 predicate)
   at Orchard.ContentManagement.DefaultContentManager.Get(Int32 id, VersionOptions options, QueryHints hints)
   at Orchard.ContentManagement.DefaultContentManager.Get(Int32 id, VersionOptions options)
   at Orchard.ContentManagement.DefaultContentManager.Get(Int32 id)
   at Orchard.ContentManagement.ContentGetExtensions.Get[T](IContentManager manager, Int32 id)
   at Orchard.MediaLibrary.Tokens.FieldTokens.MediaPart(MediaLibraryPickerField field)
   at Orchard.MediaLibrary.Tokens.FieldTokens.<Evaluate>b__b(MediaLibraryPickerField field)
   at Orchard.Tokens.Implementation.TokenManager.EvaluateContextImpl.EvaluateForImpl`1.Token(String token, Func`2 tokenValue)
   at Orchard.MediaLibrary.Tokens.FieldTokens.Evaluate(EvaluateContext context)
   at Orchard.Events.DelegateHelper.<>c__DisplayClass2b`2.<BuildAction>b__2a(Object target, Object[] p)
   at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue)
   at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue)
```

**Comment by dcinzona** [comment]
Ok, further testing...
I had my local code deployment point to the production database (and remember, the local code deployment is from an exact backup of production).  I changed the query display mode to properties, and my local deployment displays the thumbnails fine, which at the same time, production shows broken images...
Now I'm really stumped.

**Comment by dcinzona** [comment]
Ok, here's something interesting... I **restarted the Azure Web App** on production (drastic measures, I know) and now all thumbnails show up even with the query display mode set to `Properties`.  So now here's a new question...Does Orchard hold on to database connections indefinitely?  Or does the projection query reuse a previous connection, even if it's closed?

**Comment by dcinzona** [comment]
Here's a full summary of troubleshooting steps
------

First, I tried the following (Testing 1.9.1 code base on 1.9.1 database all running on my local dev box):
1.	Downloaded a copy of the production database and restored it to my local SQL instance
2.	Downloaded a copy of the production code and restored it to my local IIS instance
3.	Changed the web.config file to point to NFLPAWebDev storage for settings.txt (which points Orchard to localhost for database connectivity)
4.	Ran my local deployment
5.	Thumbnails loaded fine
6.	Changed projection query to display mode Properties
7.	Thumbnails still loaded fine

Second, I tried making a copy of the production database and deploying it to Azure (so now there’s an NFLPAWeb_Copy on Azure SQL)
1.	Copied the production database to a new Azure SQL database (minimal charge here since we are on Elastic storage ($2.00 / month or something))
2.	Changed Settings.TXT on NFLPAWebDev storage to point to the new Azure SQL database: NFLPAWeb_Copy
3.	Restarted my local instance of IIS 
4.	Went to the news page, thumbnails loaded fine (because at the time of the copy, the query was set to Content, not Properties)
5.	Changed the query to display mode: Properties
6.	Reloaded news page, thumbnails loaded fine

Ok so, this isn’t an issue with Azure SQL specifically, or the code from what I can see…
Then I tried pointing my 1.9.1 code base on my local to the production database
1.	Changed Settings.TXT on NFLPAWebDev storage to point to the production database NFLPAWeb
2.	Restarted my local instance and verified it was pointing to the production DB
3.	Changed the query to display mode: Properties
4.	Checked production (thumbnails were broken)
5.	Checked local (thumbnails loaded fine)
6.	Changed back the query display mode to Content to restore the thumbnails on production

Now I’m pretty stumped… Same code, same database, different hosting environments but also different running time… so I’m trying to rule out hosting environment
1.	Restarted the production web app instance (did it early this morning, minimal impact)
2.	Site came up fine after a minute
3.	Checked news thumbnails, they loaded fine
4.	Changed the query display mode to Properties
5.	Checked news thumbnails, and THEY LOADED FINE
6.	Switch the query display mode back to Content just in case it avoids broken thumbnails again in the future

Looks like long running web apps try to maintain/reuse connections or the projection queries do?

**Comment by sebastienros** [comment]
Investigating the fast multi-clicking issue.

**Comment by sebastienros** [comment]
Looks like it: https://github.com/OrchardCMS/Orchard/issues/5310

**Comment by dcinzona** [comment]
This issue is about a projection query connection breaking when the query is using properties display mode vs content... however, restarting the orchard application fixed the issue, so this may be that orchard projections are somehow caching the connection and not releasing it?  
#5310 is about duplicate content items

**Comment by sebastienros** [comment]
Current status: the issue to focus on is the connections one. Gustavo is trying to repro it on 1.9.2, if not then close the issue.

**Comment by dcinzona** [comment]
Will do

**Comment by sebastienros** [comment]
Please reopen when you get it back
