### ISSUE TITLE
email (Queued) does not work

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#5983]
Create a workflow that sends an email (Queued)
Trigger the workflow
--
can not recieve email
-----
2015-10-25 08:01:09,099 [104] Orchard.Exceptions.DefaultExceptionPolicy - (null) - An unexpected exception was caught [(null)]
System.NotImplementedException: The method or operation is not implemented.
   at System.Web.HttpRequestBase.get_RequestContext()
   at Orchard.Templates.Services.RazorTemplateProcessor.ActivateAndRenderTemplate(IRazorTemplateBase obj, DisplayContext displayContext, String templateVirtualPath, Object model)
   at Orchard.Templates.Services.RazorTemplateProcessor.Process(String template, String name, DisplayContext context, Object model)
   at Orchard.Templates.Services.DefaultTemplateService.Execute[TModel](String template, String name, String processorName, DisplayContext context, TModel model)
   at Orchard.Templates.Services.DefaultTemplateService.Execute[TModel](String template, String name, String processorName, TModel model)
   at Orchard.Templates.Services.TemplateShapeBindingResolver.<>c__DisplayClass6_0.<TryGetDescriptorBinding>b__0(DisplayContext ctx)
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context) in C:\Users\andy\Documents\ORCHARD-DEV-723-ZG\Orchard\src\Orchard\DisplayManagement\Implementation\DefaultDisplayManager.cs:line 203
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context) in C:\Users\andy\Documents\ORCHARD-DEV-723-ZG\Orchard\src\Orchard\DisplayManagement\Implementation\DefaultDisplayManager.cs:line 99
   at Orchard.DisplayManagement.Implementation.DisplayHelper.ShapeExecute(Object shape) in C:\Users\andy\Documents\ORCHARD-DEV-723-ZG\Orchard\src\Orchard\DisplayManagement\Implementation\DisplayHelper.cs:line 86
   at Orchard.DisplayManagement.ShapeDisplay.Display(Object shape) in C:\Users\andy\Documents\ORCHARD-DEV-723-ZG\Orchard\src\Orchard\DisplayManagement\ShapeDisplay.cs:line 39
   at Orchard.Email.Services.SmtpMessageChannel.Process(IDictionary`2 parameters)
   at Orchard.Messaging.Services.DefaultMessageService.Send(String type, IDictionary`2 parameters) in C:\Users\andy\Documents\ORCHARD-DEV-723-ZG\Orchard\src\Orchard\Messaging\Services\DefaultMessageService.cs:line 20
   at Orchard.Events.DelegateHelper.<>c__DisplayClass15_0`3.<BuildAction>b__0(Object target, Object[] p) in C:\Users\andy\Documents\ORCHARD-DEV-723-ZG\Orchard\src\Orchard\Events\DelegateHelper.cs:line 122
   at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) in C:\Users\andy\Documents\ORCHARD-DEV-723-ZG\Orchard\src\Orchard\Events\DefaultOrchardEventBus.cs:line 84
   at Orchard.Events.DefaultOrchardEventBus.TryInvoke(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) in C:\Users\andy\Documents\ORCHARD-DEV-723-ZG\Orchard\src\Orchard\Events\DefaultOrchardEventBus.cs:line 70
   at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue) in C:\Users\andy\Documents\ORCHARD-DEV-723-ZG\Orchard\src\Orchard\Events\DefaultOrchardEventBus.cs:line 53

**Comment by sfmskywalker** [comment]
Which version is this? It looks like this has something to do with the `HttpContextPlaceholder` not implementing certain properties required when rendering shape templates / Razor views. @jtkech is working on fixing this #5966. Perhaps give that PR a try and see if it fixes it?

**Comment by jeffolmstead** [comment]
@sfmskywalker I was on the 1.9.2 version and went ahead and pulled in the changes in Id #5966 and it fixed everything for me. Also not seeing any other incidental negative experiences with the changes. Will post back to #5966 if I do see any issues emerge.

**Comment by TFleury** [comment]
Could you try revert 9b91b1b2609439bb50dfc0321e72e5f39a95022f, it solved #6033.

**Comment by sebastienros** [comment]
I just verified and it works in 1.9.x
