### ISSUE TITLE
Azure Web App Deployments - HOWTO

### ISSUE THREAD

**Issue by andrewconnell** [OrchardCMS/Orchard#6201]
I have a working deployment to an Azure Web App, but only leveraging Azure blob storage for media. I understand Azure (+one or two 3rd party modules) can support getting 100% of your deployment specific configuration out of the codebase & into Azure storage (shell settings, search indexing, logging, etc). The page [Using Windows Azure Blob Storage](http://docs.orchardproject.net/Documentation/Using-Windows-Azure-Blob-Storage) has a lot of detail, but leaves a lot to be desired. Once I figure this out I will help doc it up on the Orchard Project site for others.

## Shell Settings in Azure Storage Blobs
After numerous interactions in the Gitter chat, I'm still left trying to get shell settings setup. I copied the [host.config](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Azure/Orchard.Azure.Web/Config/Host.config) and [host.components.config](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Azure/Orchard.Azure.Web/Config/Host.components.config) from the `src\orchard.azure\orchard.azure.web\config` & added a project reference to the module **Orchard.Azure** project/module to the **Orchard.Web** project so `orchard.azure.dll` is added to the site's `\bin` folder so it's there on startup & created the folder structure with the Orchard placeholders:

![image](https://cloud.githubusercontent.com/assets/2068657/11883580/f50a42be-a4e1-11e5-9c1c-7c803fe8b5f0.png)

But I still get errors that don't make sense... ideas?

```
2015-12-17 20:54:52,201 [6] Orchard.Exceptions.DefaultExceptionPolicy - (null) - An unexpected exception was caught
 (null)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.Environment.Extensions.ExtensionManagerExtensions.<>c__DisplayClass0_0.<EnabledFeatures>b__0(FeatureDescriptor fd) in D:\home\site\repository\src\Orchard\Environment\Extensions\IExtensionManager.cs:line 18
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Orchard.Data.Migration.AutomaticDataMigrations.Activated() in D:\home\site\repository\src\Orchard\Data\Migration\AutomaticDataMigrations.cs:line 35
   at Orchard.Events.DelegateHelper.<>c__DisplayClass13_0`1.<BuildAction>b__0(Object target, Object[] p) in D:\home\site\repository\src\Orchard\Events\DelegateHelper.cs:line 110
   at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) in D:\home\site\repository\src\Orchard\Events\DefaultOrchardEventBus.cs:line 83
   at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue) in D:\home\site\repository\src\Orchard\Events\DefaultOrchardEventBus.cs:line 53
2015-12-17 20:54:52,720 [6] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default
 (null)
Autofac.Core.DependencyResolutionException: None of the constructors found with 'Orchard.Environment.AutofacUtil.DynamicProxy2.ConstructorFinderWrapper' on type 'Orchard.Security.Authorizer' can be invoked with the available services and parameters:
Cannot resolve parameter 'Orchard.Security.IAuthorizationService authorizationService' of constructor 'Void .ctor(Orchard.Security.IAuthorizationService, Orchard.UI.Notify.INotifier, Orchard.IWorkContextAccessor)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Orchard.Environment.WorkRegistrationSource.<>c__DisplayClass5_0`1.<CreateMetaRegistration>b__1(Work`1 w) in D:\home\site\repository\src\Orchard\Environment\WorkContextModule.cs:line 98
   at Orchard.Environment.Work`1.get_Value() in D:\home\site\repository\src\Orchard\Environment\WorkContextModule.cs:line 41
   at Orchard.Exceptions.DefaultExceptionPolicy.RaiseNotification(Exception exception) in D:\home\site\repository\src\Orchard\Exceptions\DefaultExceptionPolicy.cs:line 63
   at Orchard.Exceptions.DefaultExceptionPolicy.HandleException(Object sender, Exception exception) in D:\home\site\repository\src\Orchard\Exceptions\DefaultExceptionPolicy.cs:line 44
   at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue) in D:\home\site\repository\src\Orchard\Events\DefaultOrchardEventBus.cs:line 59
   at Orchard.Events.DefaultOrchardEventBus.<NotifyHandlers>d__9.MoveNext() in D:\home\site\repository\src\Orchard\Events\DefaultOrchardEventBus.cs:line 41
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Orchard.Events.DefaultOrchardEventBus.Notify(String messageName, IDictionary`2 eventData) in D:\home\site\repository\src\Orchard\Events\DefaultOrchardEventBus.cs:line 27
   at Orchard.Events.EventsInterceptor.Intercept(IInvocation invocation) in D:\home\site\repository\src\Orchard\Events\EventsInterceptor.cs:line 26
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IOrchardShellEventsProxy.Activated()
   at Orchard.Environment.DefaultOrchardShell.Activate() in D:\home\site\repository\src\Orchard\Environment\DefaultOrchardShell.cs:line 81
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in D:\home\site\repository\src\Orchard\Environment\DefaultOrchardHost.cs:line 170
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__31_1(ShellSettings settings) in D:\home\site\repository\src\Orchard\Environment\DefaultOrchardHost.cs:line 142
```

## Log4Net Settings => Azure Storage Blob
I see that there is some work done on this so logs will not got to `App_Data` rather to an Azure storage account in the [log4net.config](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Azure/Orchard.Azure.Web/Config/log4net.config) but where do you configure the settings for WHERE the logs go? Does it just inherit the settings from the **Diagnostic Logging** configuration within the Azure Web App?

This would be cool to have and then have an ELK configuration setup to easily process & visualize the logs.

## Moving Search Indexes => Azure Storage Blob
I see this module... looks promising: https://github.com/Lombiq/Orchard-Azure-Indexing

**Comment by Piedone** [comment]
Summoning @DanielStolt for the shell settings thing.

About logs:
The AzureDiagnosticsAppender will use Azure Diagnostics (https://azure.microsoft.com/en-us/documentation/articles/cloud-services-dotnet-diagnostics/) so collect log files not in Blob Storage but rather in Table Storage. It will use the Cloud Service's config for this but no idea how to configure this while not in a Cloud Service.

Also FYI if you're on Azure Web Apps the app's storage is shared, so if you only want to make sure to collect logs from all server nodes (if you use multiple ones) then you already have this. Furthermore on a side note you can (additionally) also collect log entries in Azure Application Insights (https://github.com/Lombiq/Orchard-Azure-Application-Insights).

And yeah, the Azure Indexing module works well for us :-).

**Comment by andrewconnell** [comment]
Thanks for the insight @Piedone ... I'll wait to hear from @DanielStolt on the shell settings. I have it setup and partially working (2 of 3 tenants) but the error log above as you can see doesn't help with a missing assembly and can't figure out what's wrong there...

**Comment by DanielStolt** [comment]
@andrewconnell I have never actually tried using blob storage shell settings in the context of an Azure Web App, but as far as I can see, your setup should work:

- Adding a reference to Orchard.Azure
- Configuring the blob storage implementation of `IShellSettingsManager` like so:

		
		<component instance-scope="single-instance" type="Orchard.FileSystems.Media.ConfigurationMimeTypeProvider, Orchard.Framework" service="Orchard.FileSystems.Media.IMimeTypeProvider"></component>
		<component instance-scope="single-instance" type="Orchard.Azure.Services.Environment.Configuration.AzureBlobShellSettingsManager, Orchard.Azure" service="Orchard.Environment.Configuration.IShellSettingsManager"></component>

Looking at the exceptions you provided, it doesn't seem to me like they have anything to do with shell settings though. Looks more like Autofac is failing to find a dependency, no?

**Comment by jtkech** [comment]
@andrewconnell never used your scenario.

But your first issue seems to be related to a bad shell descriptor and / or its shell features. So, just a first idea...

In your scenario, do you still use the App_Data/cache.dat? If so, try to remove it and restart. Or disable it in the HostComponents.config file (if not already done)...

Best

**Comment by dcinzona** [comment]
I just came across this.  You are describing our exact deployment scenario.  We use Azure Blob Storage for Site Settings, Indexing, and Logs.  We also use ElasticSearch for logging outside of files (utilizing the ELK stack for parsing out the logs).  
Have you resolved the Shell settings issue you were having?  We have multiple environments all using different Blob Storage accounts for shell settings based on the environment (Prod, QA, Dev:localhost). Let me know if I can assist.  We have been using Azure Blob Storage for settings since 1.8.1 and haven't had any issues through the latest release (1.9.2).
