### ISSUE TITLE
Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.

### ISSUE THREAD

**Issue by david0718** [OrchardCMS/Orchard#6305]
we developed an new module for our business. for example, we call it an Event module. and the event module has dependency for odata module.
1. Go to dashboard, enable Event module, everything works fine.
2. Disable Event module, then enable event module.
3. Access the url for odata : http://localhost/odata/$metadata, exception as below:

The exception message is 'Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.'. See server logs for more details. The exception stack trace is:

at Autofac.Core.Lifetime.LifetimeScope.CheckNotDisposed() at Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope(Object tag) at Orchard.Environment.WorkContextAccessor.CreateWorkContextScope(HttpContextBase httpContext) at Orchard.Environment.WorkContextAccessor.CreateWorkContextScope() at Orchard.Wcf.OrchardInstanceContext..ctor(IWorkContextAccessor workContextAccessor) at Orchard.Wcf.OrchardInstanceProvider.GetInstance(InstanceContext instanceContext, Message message) at System.ServiceModel.InstanceContext.GetServiceInstance(Message message) at System.ServiceModel.Dispatcher.InstanceBehavior.EnsureServiceInstance(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage41(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc) at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)

I found the error from below method in WorkContextAccessor.cs class.

var workLifetime = _lifetimeScope.BeginLifetimeScope("work"); 

this line of code throw the exception. Only after we run iisreset, the exception will not appear.

______________________________________________________________________________

public IWorkContextScope CreateWorkContextScope(HttpContextBase httpContext) {
            var workLifetime = _lifetimeScope.BeginLifetimeScope("work");
            workLifetime.Resolve<WorkContextProperty<HttpContextBase>>().Value = httpContext;

            var events = workLifetime.Resolve<IEnumerable<IWorkContextEvents>>();
            events.Invoke(e => e.Started(), NullLogger.Instance);

            return new HttpContextScopeImplementation(
                events,
                workLifetime,
                httpContext,
                _workContextKey);
        }

Thanks

David

**Comment by david0718** [comment]
The orchard version is 1.9.2.

**Comment by sfmskywalker** [comment]
Unless you can reproduce this issue with core Orchard features, this is most probably a problem with your module. Perhaps you mixed lifetime scope dependencies, e.g. you inject IDependency types into singleton types. If you do think this is a problem with Orchard, then please provide repro steps that we can follow (even if we need to create a module with specific code to demonstrate the issue).

**Comment by david0718** [comment]
Autofac.Core.Lifetime.LifetimeScope.CheckNotDisposed() at Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope(Object tag) at Orchard.Environment.WorkContextAccessor.CreateWorkContextScope(HttpContextBase httpContext) at Orchard.Environment.WorkContextAccessor.CreateWorkContextScope() at Orchard.Wcf.OrchardInstanceContext..ctor(IWorkContextAccessor workContextAccessor) at Orchard.Wcf.OrchardInstanceProvider.GetInstance(InstanceContext instanceContext, Message message) at System.ServiceModel.InstanceContext.GetServiceInstance(Message message) at System.ServiceModel.Dispatcher.InstanceBehavior.EnsureServiceInstance(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage41(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc) at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)

**Comment by david0718** [comment]
Any idea on above error?

Best regards and Thanks

**Comment by sebastienros** [comment]
This is probably an issue with the module itself. Have you tried contacting the module developer?

**Comment by david0718** [comment]
Hi   Nice guys

After disable some module.  When I open "http://localhost/odata/$metadata"

The first time run " var workLifetime = _lifetimeScope.BeginLifetimeScope("work");"
_lifetimeScope  IsDisposed = false.

Then continue, this line code will be hit again, but _lifetimeScop's  IsDisposed = true.
So {"Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed."} throwed.

I think it is not odata module's bug, maybe it is orchard's wcf implementation.

Could you please check it. I really like wcf in orchard, but it seems it is not so perfect now.

Thanks and best regards

David

_______________________________________________________________________________
public object GetInstance(InstanceContext instanceContext, Message message) {
            OrchardInstanceContext item = new OrchardInstanceContext(_workContextAccessor);
            instanceContext.Extensions.Add(item);
            return item.Resolve(_componentRegistration);

        }

public IWorkContextScope CreateWorkContextScope(HttpContextBase httpContext) {
            var workLifetime = _lifetimeScope.BeginLifetimeScope("work");
            workLifetime.Resolve<WorkContextProperty<HttpContextBase>>().Value = httpContext;

            var events = workLifetime.Resolve<IEnumerable<IWorkContextEvents>>();
            events.Invoke(e => e.Started(), NullLogger.Instance);

            return new HttpContextScopeImplementation(
                events,
                workLifetime,
                httpContext,
                _workContextKey);
        }

**Comment by david0718** [comment]
@sebastienros  Not yet contact the owner, I will and meanwhile I modified your Contrib.MediaFolder for load banlance and also compatible with orchard 1.9.2, but I do not how to send it to you, so you could review and merge it.

Thanks

David

**Comment by david0718** [comment]
Temporarily I solved this issue by change WorkContextAccessor.cs for below code.
I restarted the app domain after and error for _lifetimeScope.BeginLifetimeScope("work");

Thanks

David  

try
            {
                var workLifetime = _lifetimeScope.BeginLifetimeScope("work");
                workLifetime.Resolve<WorkContextProperty<HttpContextBase>>().Value = httpContext;

                var events = workLifetime.Resolve<IEnumerable<IWorkContextEvents>>();
                events.Invoke(e => e.Started(), NullLogger.Instance);

                return new HttpContextScopeImplementation(
                    events,
                    workLifetime,
                    httpContext,
                    _workContextKey);
            }
            catch (Exception)
            {
                _hostEnvironment.RestartAppDomain();
                return null;
            }

**Comment by mohsen-jalalian** [comment]
you should do something link this:
public OnlineTradingHub(ILifetimeScope lifetimeScope)
{
      _lifetimeScope = lifetimeScope.BeginLifetimeScope();
}
