### ISSUE TITLE
Upgrade from 1.9.2 to 1.10 fails with SqlCE error

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/Orchard#6382]
For test purposes I upgraded a test 'site' from 1.9.2 to 1.10 (github) and get below error.
When checking the SqlCE DBs (Orchard.sdf): both versions have a table: 'Orchard_Indexing_IndexingTaskRecord'
I.e. the table: 'Orchard_Indexing_IndexTaskBatchRecord' really does NOT exist (see error below)!
In 'Orchard 1.10 Release Notes' (orchard project doc) I couldn't find any info in this direction!
My upgrade procedure was as usual:
- copy foders; App_Data (includes orchard.sdf), Media and themes
Thanks for your time and ideas, ed

ERROR msg;
System.Data.SqlServerCe.SqlCeException was unhandled by user code
  ErrorCode=-2147467259
  HResult (System.Exception)=-2147467259
  HResult=-2147217865
  Message=The specified table does not exist. [ Orchard_Indexing_IndexTaskBatchRecord ]
  NativeError=0
  Source=SQL Server Compact ADO.NET Data Provider
  StackTrace:
       at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
       at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommandText(IntPtr& pCursor, Boolean& isBaseTableCursor)
       at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
       at System.Data.SqlServerCe.SqlCeCommand.ExecuteNonQuery()
       at Orchard.Data.Migration.Interpreters.DefaultDataMigrationInterpreter.RunPendingStatements() in D:\CMSites\Org_110\src\Orchard\Data\Migration\Interpreters\DefaultDataMigrationInterpreter.cs:line 380
       at Orchard.Data.Migration.Interpreters.DefaultDataMigrationInterpreter.Visit(DropTableCommand command) in D:\CMSites\Org_110\src\Orchard\Data\Migration\Interpreters\DefaultDataMigrationInterpreter.cs:line 116
       at Orchard.Data.Migration.Interpreters.AbstractDataMigrationInterpreter.Visit(ISchemaBuilderCommand command) in D:\CMSites\Org_110\src\Orchard\Data\Migration\Interpreters\AbstractDataMigrationInterpreter.cs:line 20
       at Orchard.Data.Migration.Schema.SchemaBuilder.Run(ISchemaBuilderCommand command) in D:\CMSites\Org_110\src\Orchard\Data\Migration\Schema\SchemaBuilder.cs:line 84
       at Orchard.Data.Migration.Schema.SchemaBuilder.DropTable(String name) in D:\CMSites\Org_110\src\Orchard\Data\Migration\Schema\SchemaBuilder.cs:line 63
       at Orchard.Indexing.Migrations.UpdateFrom3()
  InnerException:

**Comment by BenedekFarkas** [comment]
@sebastienros we should have this in 1.10 (1.9.3 doesn't include the modified migrations). The problem come up if your migration version is 2. If the migration version is 3, then `UpdateFrom3` will run and drop the table (that was created in `UpdateFrom2` before its logic was removed).

The easy fix is to change `UpdateFrom2` and in `Orchard.Indexing.Migrations` to return 4 (but since `UpdateFrom2` is now empty, `UpdateFrom1` could also return 4).

**Comment by sebastienros** [comment]
GO

**Comment by BenedekFarkas** [comment]
@edikaufmann please check the 1.10 branch and reopen if there's an issue with the fix.
