### ISSUE TITLE
media folders are mixed in diff tenant

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6395]
in default tenant site, i have  folder called admin.
in my second tenant site, i create a folder called  admin, now i can see the  files' name from default although the media from default tenant can not be showed

**Comment by sebastienros** [comment]
What version?

**Comment by BenedekFarkas** [comment]
No repro on 1.9.3/1.10/dev.

**Comment by infofromca** [comment]
1.10

**Comment by infofromca** [comment]
![multi-tenants-media](https://cloud.githubusercontent.com/assets/297675/13152458/4ab18402-d63d-11e5-8de0-2be78f8f0c71.png)

**Comment by infofromca** [comment]
![multi-tenants-media-default](https://cloud.githubusercontent.com/assets/297675/13152503/8a1552b8-d63d-11e5-977e-d957cf4149bf.png)

**Comment by infofromca** [comment]
error log:

2016-02-18 12:39:48,319 [28] Orchard.MediaProcessing.Services.ImageProfileManager - RealEstateWorld - path:/OrchardLocal/Media/RealEstateWorld/Admin/feed-after-submit-local.png storagePath:Admin\feed-after-submit-local.png [http://realestateworld:30321/OrchardLocal/Admin/Orchard.MediaLibrary/MediaItems?folderPath=&skip=0&count=25&order=created&mediaType=&_=1455817182610]
System.ArgumentException: File Admin\feed-after-submit-local.png does not exist
   at Orchard.FileSystems.Media.FileSystemStorageProvider.GetFile(String path) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\FileSystems\Media\FileSystemStorageProvider.cs:line 114
   at Orchard.MediaProcessing.Services.ImageProfileManager.GetImage(String path)
2016-02-18 12:39:48,640 [28] Orchard.MediaProcessing.Services.ImageProfileManager - RealEstateWorld - path:/OrchardLocal/Media/RealEstateWorld/Admin/Capture.PNG storagePath:Admin\Capture.PNG [http://realestateworld:30321/OrchardLocal/Admin/Orchard.MediaLibrary/MediaItems?folderPath=&skip=0&count=25&order=created&mediaType=&_=1455817182610]
System.ArgumentException: File Admin\Capture.PNG does not exist
   at Orchard.FileSystems.Media.FileSystemStorageProvider.GetFile(String path) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\FileSystems\Media\FileSystemStorageProvider.cs:line 114
   at Orchard.MediaProcessing.Services.ImageProfileManager.GetImage(String path)
2016-02-18 12:39:48,807 [28] Orchard.MediaProcessing.Services.ImageProfileManager - RealEstateWorld - path:/OrchardLocal/Media/RealEstateWorld/Admin/IMG_2003.JPG storagePath:Admin\IMG_2003.JPG [http://realestateworld:30321/OrchardLocal/Admin/Orchard.MediaLibrary/MediaItems?folderPath=&skip=0&count=25&order=created&mediaType=&_=1455817182610]
System.ArgumentException: File Admin\IMG_2003.JPG does not exist
   at Orchard.FileSystems.Media.FileSystemStorageProvider.GetFile(String path) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\FileSystems\Media\FileSystemStorageProvider.cs:line 114
   at Orchard.MediaProcessing.Services.ImageProfileManager.GetImage(String path)
2016-02-18 12:39:48,875 [28] Orchard.MediaProcessing.Services.ImageProfileManager - RealEstateWorld - path:/OrchardLocal/Media/RealEstateWorld/Admin/IMG_1705.JPG storagePath:Admin\IMG_1705.JPG [http://realestateworld:30321/OrchardLocal/Admin/Orchard.MediaLibrary/MediaItems?folderPath=&skip=0&count=25&order=created&mediaType=&_=1455817182610]
System.ArgumentException: File Admin\IMG_1705.JPG does not exist
   at Orchard.FileSystems.Media.FileSystemStorageProvider.GetFile(String path) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\FileSystems\Media\FileSystemStorageProvider.cs:line 114
   at Orchard.MediaProcessing.Services.ImageProfileManager.GetImage(String path)

**Comment by sebastienros** [comment]
Are you migrating from a previous version, could it be that you imported the images using the Update module ?

**Comment by sebastienros** [comment]
Please re-open if you can provide repro steps from a new setup.
