### ISSUE TITLE
multi tenant --save the same host

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6493]
1--i have tenant1 with host name tetant1
2--now create tenant2 with the same name tenant1
got exception which is not dealt
![tenant-samekey](https://cloud.githubusercontent.com/assets/297675/13370840/3937bce4-dce3-11e5-9517-a014a3059add.png)

**Comment by infofromca** [comment]
the worse:
the next day, when i start vs and run the solution, it goes to set up page of default site.
the log:
2016-02-28 07:30:19,308 [5] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default [(null)]
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Orchard.Environment.RunningShellTable.Organize() in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\RunningShellTable.cs:line 81
   at Orchard.Environment.RunningShellTable.Add(ShellSettings settings) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\RunningShellTable.cs:line 34
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 184
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__32_1(ShellSettings settings) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 147
2016-02-28 07:30:19,308 [13] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Collaboration16 [(null)]
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Orchard.Environment.RunningShellTable.Organize() in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\RunningShellTable.cs:line 81
   at Orchard.Environment.RunningShellTable.Add(ShellSettings settings) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\RunningShellTable.cs:line 34
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 184
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__32_1(ShellSettings settings) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 147
2016-02-28 07:30:20,298 [17] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Test [(null)]
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Orchard.Environment.RunningShellTable.Organize() in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\RunningShellTable.cs:line 81
   at Orchard.Environment.RunningShellTable.Add(ShellSettings settings) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\RunningShellTable.cs:line 34
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 184
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__32_1(ShellSettings settings) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 147
2016-02-28 07:30:22,351 [16] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: RealEstateWorld [(null)]
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Orchard.Environment.RunningShellTable.Organize() in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\RunningShellTable.cs:line 81
   at Orchard.Environment.RunningShellTable.Add(ShellSettings settings) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\RunningShellTable.cs:line 34
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 184
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__32_1(ShellSettings settings) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 147

**Comment by infofromca** [comment]
it is because the catch can not catch the exception from async method

**Comment by sebastienros** [comment]
Solution is to check for the tenant name to be unique.
