### ISSUE TITLE
Connection disposal NRE

### ISSUE THREAD

**Issue by carlwoodhouse** [OrchardCMS/Orchard#6555]
So, we've had a bit of an odd issue on one of our azure instances this morning .... where we got a load of errors saying we had no connections available for sql.

Some investigation later revealed that one of the instances was having an issue disposing it's session and was throwing this every 1minute (so possibly related to the alias refresh?)

`Exception information: 
    Exception type: NullReferenceException 
    Exception message: Object reference not set to an instance of an object.
   at Orchard.Data.TransactionManager.DisposeSession()
   at Autofac.Core.Disposer.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Orchard.Mvc.Routes.ShellRoute.HttpAsyncHandler.<ProcessRequestAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
`

One assumes because it was failing to dispose the session, it was leaving db connections open.

Recycling the app pool fixed the issue for now, this was using 1.9.2.

**Comment by sebastienros** [comment]
I remember I made the alias refresh a separate feature for this reason. I could see the connection pool getting filled quickly with its queries. I assumed at that point that the query was not well constructed and would lock the table.
And you need this feature as you have multiple nodes ... I will check what it's doing to see if I can find something wrong with the code.
If you want to help it might be interesting to trigger the issue on purpose by shortening the background task delay, and having multiple instances of the site do the same work (to simulate multiple nodes, which by the way can be done by creating multiple tenants on the SAME DATABASE tables, nice trick). You can also add some log on the transaction instantiation and disposal, to ensure they are correctly handled.

**Comment by carlwoodhouse** [comment]
Interesting tip about the multiple tenant :) will investigate further.

**Comment by jtkech** [comment]
After a quick look in the dev branch around this, first, 2 things that seems weird to me.

When starting the app, `_aliasHolderUpdater.Refresh();` is called 2 times. One in `AliasHolderUpdater.cs` through `AliasUpdaterEvent IOrchardShellEvents.Activated()`, and one in `AliasHolderUpdaterTask.cs` through its `IOrchardShellEvents.Activated()`.

In background tasks, `_aliasHolderUpdater.Refresh();` is executed through `AliasHolderUpdaterTask.Sweep()` that also inherit from `IBackgroundTask`, and if i enable the `Alias Updater` feature, then it is executed a 2nd time in `AliasUpdaterBackgroundTask` through its `Sweep()` method.

Best

**Comment by sebastienros** [comment]
That could explain the deadlock on the tables. I will look at it.

**Comment by dcinzona** [comment]
Just wondering if this could be due to the MessageBus bug (distributed shell restarts).

**Comment by jtkech** [comment]
@carlwoodhouse looking at your trace, it happens at the end of a web request and in `TransactionManager.DisposeSession()`.

Here, without analysing nhibernate, it would mean that `_session` is null or `_session.Transaction` is null. The 1st one is checked at the beginning of the method, this would mean a concurent access on the same `TransactionManager` instance.

So, just for testing, without disturbing you, before re-checking `_session` itself before closing and diposing, can you do this 1st test by replacing this:

    if (_session.Transaction.IsActive) {

With:

    if (_session.Transaction != null && _session.Transaction.IsActive) {

Best.

**Comment by carlwoodhouse** [comment]
sorry had zero time to look at this since! will try to find time toward the end of the week
