### ISSUE TITLE
dynamic form -contact

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6558]
created dynamic form -contact as the guide which was good days ago in 1.10
today's version, got many issue issues:
1--got strange thing --red circle
2--i can not send out email , but it shows -orange circle
3--token  can not work
![contact](https://cloud.githubusercontent.com/assets/297675/13644134/312962a6-e5f2-11e5-8ef7-3818ea5f6ff2.png)

**Comment by infofromca** [comment]
2016-03-09 11:41:20,152 [26] Orchard.Exceptions.DefaultExceptionPolicy - Default - An unexpected exception was caught [http://noagent.properties/]
System.ArgumentException: The virtual path '/' maps to another application, which is not allowed.
   at System.Web.CachedPathData.GetVirtualPathData(VirtualPath virtualPath, Boolean permitPathsOutsideApp)
   at System.Web.HttpContext.GetFilePathData()
   at System.Web.HttpContext.GetConfigurationPathData()
   at System.Web.HttpContext.GetSection(String sectionName)
   at System.Web.Configuration.HttpConfigurationSystem.GetSection(String sectionName)
   at System.Web.Configuration.HttpConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
   at System.Net.Configuration.SmtpSectionInternal.GetSection()
   at System.Net.Mail.SmtpClient.get_MailConfiguration()
   at System.Net.Mail.MailMessage..ctor()
   at Orchard.Email.Services.SmtpMessageChannel.Process(IDictionary`2 parameters)
   at Orchard.Messaging.Services.DefaultMessageService.Send(String type, IDictionary`2 parameters) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Messaging\Services\DefaultMessageService.cs:line 20
   at Orchard.Events.DelegateHelper.<>c__DisplayClass15_0`3.<BuildAction>b__0(Object target, Object[] p) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Events\DelegateHelper.cs:line 122
   at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Events\DefaultOrchardEventBus.cs:line 84
   at Orchard.Events.DefaultOrchardEventBus.TryInvoke(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Events\DefaultOrchardEventBus.cs:line 70
   at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Events\DefaultOrchardEventBus.cs:line 53

**Comment by infofromca** [comment]
and another log after i disable my custom email module

2016-03-09 12:11:19,903 [31] Orchard.Email.Services.SmtpMessageChannel - Default - Could not send email [http://localhost:30321/OrchardLocal/Orchard.DynamicForms/Form/Submit]
System.Net.Mail.SmtpException: Failure sending mail. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 69.24.64.28:25
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.PooledStream.Activate(Object owningObject, GeneralAsyncDelegate asyncCallback)
   at System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- End of inner exception stack trace ---
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at Orchard.Email.Services.SmtpMessageChannel.Process(IDictionary`2 parameters)

====
but actually the server )papercut is ok because i test it on email setting page

**Comment by infofromca** [comment]
after reset  email setting page, i can send out email

**Comment by Skrypt** [comment]
We need repro steps. Do you have a binding to a custom content type that you made ? Do you have 2 different dynamic forms with the same name ? The red warning message tells me that you are saving to the database the contact form entries. If your custom content type that is binded to your dynamic form has the autoroute part attached to it ; it will create an Alias to the contact request that the form creates. To me, it does not make sense that you need to be able to create an Alias for those contact requests. The Alias is a way to access the content items with a nice url ex: /contact-request-1.

To fix your issue, I would remove the autoroute part to the custom content type you created in the content definitions. Though, if you need to keep the autoroute part on the custom content type you created. I would try to set a different pattern in your autoroute settings in the custom content type you created. Example : /contact-requests/{content.slug}

Though this is still an "issue" that I will try to repro to find why it is creating duplicate Alias's

**Comment by Skrypt** [comment]
Here is the repro : 

Create a custom content type named Contact Request with an AutoroutePart and 3 fields : Topic, Email, Message.
Create a dynamic form with a binding to those 3 fields and set it to create Contact Request content type and set it to make them published.

![image](https://cloud.githubusercontent.com/assets/3228637/13685408/4f3bb7ca-e6de-11e5-9e96-73450974556a.png)

The Contact Request does'nt have a Title part so it has no {content.slug}. It will name the Alias's like this : 

![image](https://cloud.githubusercontent.com/assets/3228637/13685522/d803a022-e6de-11e5-86fb-e646ba48cddf.png)

Now, trying a different pattern in the autoroute part /contact-request/{FormSubmission.Field:Topic} does'nt work either. The token does'nt work.

I'm not sure if this is an issue since we can save the form submissions without creating a custom content type every time. And, having the topic as a {content.slug} won't prevent to make duplicates.

**Comment by infofromca** [comment]
i remember that this only happen in 1.10 after a91b06f1b55c38ff78ee1d880db27b845e2f114a

**Comment by sebastienros** [comment]
Maybe you also need to setup a correct pattern for the autoroute as there are no title.

TODO: @sfmskywalker please ensure that form elements can be used in autoroute patterns.
