### ISSUE TITLE
NREs in logs for comments

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard#6565]
```
2016-03-10 05:25:47,440 [168] Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator - dixin - NullReferenceException thrown from IContentPartDriver by Orchard.Comments.Drivers.CommentPartDriver
 http://weblogs-1.asp.net/dixin/comments/comment/create
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.Comments.Drivers.CommentPartDriver.Editor(CommentPart part, IUpdateModel updater, Object shapeHelper)
   at Orchard.ContentManagement.Drivers.ContentPartDriver`1.Orchard.ContentManagement.Drivers.IContentPartDriver.UpdateEditor(UpdateEditorContext context)
   at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.<>c__DisplayClass10.<UpdateEditor>b__f(IContentPartDriver driver)
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger) 
```

**Comment by sebastienros** [comment]
Duplicate of https://github.com/OrchardCMS/Orchard/issues/5836
