### ISSUE TITLE
Empty Main Menu

### ISSUE THREAD

**Issue by aprotskiv** [OrchardCMS/Orchard#6584]
Orchard became broken after all items were removed from Main Menu

2016-03-14 16:55:42,904 [56] Orchard.Core.Navigation.Services.NavigationManager - Default - Unexpected error while querying a menu provider. It was ignored. The menu provided by the provider may not be complete.
 http://www.myorchardwebsite.com/favicon.ico
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at PJS.Bootstrap.MainMenu.GetMenu(IContent menu, NavigationBuilder builder)
   at Orchard.Core.Navigation.Services.NavigationManager.<GetSources>d__1d.MoveNext() in z:\Builds\work\9f6cd39ff0f68f41\src\Orchard.Web\Core\Navigation\Services\NavigationManager.cs:line 173

**Comment by jersiovic** [comment]
Problem doesn't look related with Orchard Core. It is a problem with PJS Bootstrap so you should add an issue on its githup repo.

This is the class causing the exception: https://github.com/psenechal/PJS.Bootstrap/blob/master/MainMenu.cs
As you can see it can be fixed avoiding to execute the max instruction. Simply checking  that there is not any menu item before.
