### ISSUE TITLE
Features in modules installed from the Gallery can't be enabled after install [1.10]

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#6592]
Repro:

- Install any module from the Gallery that has one or more features
- Select any number (at least 1) of those features to enable in the next step

Expected result: the features are enabled.
Actual result: the features are still not enabled (but they can be enabled manually after that, that's not an issue).

The exception logged is the following:
```
2016-03-16 10:52:24,481 [24] Orchard.Recipes.Services.RecipeStepExecutor - Default - Recipe execution failed because the step 'Feature' failed. [http://orchard.127-0-0-1.org.uk/Packaging/PackagingServices/InstallPackageDetails?packageId=Orchard.Module.Orchard.OData&version=1.9.0.1&sourceId=1&redirectUrl=%2FPackaging%2FGallery%2FModules]
System.InvalidOperationException: Could not enable feature 0 because it was not found.
   at Orchard.Modules.Recipes.Executors.FeatureStep.Execute(RecipeExecutionContext recipeContext)
   at Orchard.Recipes.Providers.RecipeHandlers.RecipeExecutionStepHandler.ExecuteRecipeStep(RecipeContext recipeContext)
   at Orchard.Recipes.Services.RecipeStepExecutor.ExecuteNextStep(String executionId)
2016-03-16 10:52:24,569 [24] Orchard.Exceptions.DefaultExceptionPolicy - Default - An unexpected exception was caught [http://orchard.127-0-0-1.org.uk/Packaging/PackagingServices/InstallPackageDetails?packageId=Orchard.Module.Orchard.OData&version=1.9.0.1&sourceId=1&redirectUrl=%2FPackaging%2FGallery%2FModules]
Orchard.OrchardCoreException: Recipe execution with ID 55e5448f4d144750a8e40161253c9682 failed because the step 'Feature' failed to execute. The following exception was thrown:
Could not enable feature 0 because it was not found.
Refer to the error logs for more information.
   at Orchard.Recipes.Services.RecipeStepExecutor.ExecuteNextStep(String executionId)
   at Orchard.Recipes.Services.RecipeScheduler.ExecuteWork(String executionId)
   at Orchard.Events.DelegateHelper.<>c__DisplayClass2b`2.<BuildAction>b__2a(Object target, Object[] p) in e:\DEV\Orchard\Orchard CMS\src\Orchard\Events\DelegateHelper.cs:line 116
   at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) in e:\DEV\Orchard\Orchard CMS\src\Orchard\Events\DefaultOrchardEventBus.cs:line 84
   at Orchard.Events.DefaultOrchardEventBus.TryInvoke(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) in e:\DEV\Orchard\Orchard CMS\src\Orchard\Events\DefaultOrchardEventBus.cs:line 70
   at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue) in e:\DEV\Orchard\Orchard CMS\src\Orchard\Events\DefaultOrchardEventBus.cs:line 53
```

Line 256-264 in the PackagingServiceController in Orchard.Packaging is responsible for generating a recipe dynamically for enabling those features. The recipe steps are not passing the ID of the feature into the recipe, but an integer (Priority maybe?), that's why it says `Could not enable feature 0 because it was not found.`. Changing it to pass the ID of the feature into the recipe results in the following exception:

```
2016-03-16 11:42:41,654 [8] NHibernate.AssertionFailure - Default - An AssertionFailure occurred - this may indicate a bug in NHibernate or in your custom types. [http://orchard.127-0-0-1.org.uk/Packaging/PackagingServices/InstallPackageDetails?packageId=Orchard.Module.Piedone.HelpfulLibraries&version=1.9&sourceId=1&redirectUrl=%2FPackaging%2FGallery%2FModules]
NHibernate.AssertionFailure: null id in Orchard.Recipes.Models.RecipeStepResultRecord entry (don't flush the Session after an exception occurs)
```

I didn't dig deeper than that at this point, but I assume that this information is passed on to some other code that creates the `RecipeStepResultRecord` entry and it expects and integer, not a string.

**Comment by dcinzona** [comment]
I wonder if there will be other issues with 1.10 and gallery modules... for example, if the module is old and requires Orchard.jQuery, it will not be able to be enabled.  Maybe it's not an issue because in the features list, the requirement would be missing.
