### ISSUE TITLE
Snippet Harvester throws NotImplemented exception during command line setup

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#6597]
When executing Setup via Orchard.exe and a Recipe containing a Snippet Element, the process fails at:

```
2016-03-17 01:27:02,711 [1] Orchard.ContentManagement.DefaultContentManager - (null) - NotImplementedException thrown from IContentHandler by Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator [(null)]
System.NotImplementedException: The method or operation is not implemented.
   at System.Web.HttpServerUtilityBase.MapPath(String path)
   at Orchard.Layouts.Providers.SnippetElementHarvester.HasSnippetFields(ShapeDescriptor shapeDescriptor)
   at Orchard.Layouts.Providers.SnippetElementHarvester.<HarvestElements>d__10.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__31`3.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Orchard.Caching.Cache`2.CreateEntry(TKey k, Func`2 acquire)
   at Orchard.Caching.Cache`2.AddEntry(TKey k, Func`2 acquire)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at Orchard.Caching.Cache`2.Get(TKey key, Func`2 acquire)
   at Orchard.Caching.CacheManagerExtensions.Get[TKey,TResult](ICacheManager cacheManager, TKey key, Boolean preventConcurrentCalls, Func`2 acquire)
   at Orchard.Layouts.Services.ElementManager.DescribeElements(DescribeElementsContext context)
   at Orchard.Layouts.Services.ElementManager.GetElementDescriptorByTypeName(DescribeElementsContext context, String typeName)
   at Orchard.Layouts.Services.ElementSerializer.ParseNode(JToken node, Container parent, Int32 index, DescribeElementsContext describeContext)
   at Orchard.Layouts.Services.LayoutSerializer.<>c__DisplayClass2_0.<Deserialize>b__0(JToken x, Int32 i)
   at System.Linq.Enumerable.<SelectIterator>d__7`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Orchard.Layouts.Services.LayoutSerializer.Deserialize(String data, DescribeElementsContext describeContext)
   at Orchard.Layouts.Services.LayoutManager.Imported(ImportLayoutContext context)
   at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.Imported(ImportContentContext context)
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger)
```

The problem is that the HttpContext stand-in for Orchardard.exe does not implement the Server.MapPath method.

To fix this, the method should be implemented.

**Comment by sfmskywalker** [comment]
The fix is to add the following method override in MvcModule.cs in the `HttpServerUtilityPlaceholder` class:

```
public override string MapPath(string path) {
   return HostingEnvironment.MapPath(path);
}
```

This fix is to be pushed to the 1.10.x branch.
