### ISSUE TITLE
We are getting Null Reference Exception in Orchard Logs for https://www.pedalheads.com/camp

### ISSUE THREAD

**Issue by dashleen-bhandari** [OrchardCMS/Orchard#6620]
Intermittently, while we browse https://www.pedalheads.com/camp, we are getting Null reference exception. The stack is:

2016-03-21 06:07:39,338 [7] Orchard.Exceptions.DefaultExceptionPolicy - Default - An unexpected exception was caught
 https://www.pedalheads.com/AtlantisCamps.CampModule/Camp/GetHoldTimeRemaining?_=1458540475251
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.CreateControllerContext()
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.RenderRazorViewToString(String path, DisplayContext context)
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.Render(ShapeDescriptor shapeDescriptor, DisplayContext displayContext, HarvestShapeInfo harvestShapeInfo, HarvestShapeHit harvestShapeHit)
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.<>c__DisplayClass26.<>c__DisplayClass28.<Discover>b__15(DisplayContext displayContext)
   at Orchard.DisplayManagement.Descriptors.ShapeAlterationBuilder.<>c__DisplayClass3.<>c__DisplayClass5.<BoundAs>b__2(DisplayContext displayContext)
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context)
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context)
   at Orchard.DisplayManagement.Implementation.DisplayHelper.ShapeExecute(Object shape)
   at Orchard.DisplayManagement.ShapeDisplay.Display(Object shape)
   at Orchard.Email.Services.SmtpMessageChannel.Process(IDictionary`2 parameters)
   at AtlantisCamps.CampModule.Services.ExceptionManager.HandleException(Exception ex, String data)
   at AtlantisCamps.CampModule.Services.APIService.<.ctor>b__0(Exception ex, String info, IExceptionManager mngr)
   at AtlantisCamps.CampModule.Services.APIService.<GetAsync>d__2`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at AtlantisCamps.CampModule.Services.APIService.Get[T](String uri)
   at AtlantisCamps.CampModule.Services.AtlantisApi.GetHoldTimeRemaining(String registrationCode)
   at AtlantisCamps.CampModule.Controllers.CampController.GetHoldTimeRemaining()
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass48.<InvokeActionMethodFilterAsynchronouslyRecursive>b__41()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass48.<InvokeActionMethodFilterAsynchronouslyRecursive>b__41()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass48.<InvokeActionMethodFilterAsynchronouslyRecursive>b__41()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass48.<InvokeActionMethodFilterAsynchronouslyRecursive>b__41()
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.CreateControllerContext()
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.RenderRazorViewToString(String path, DisplayContext context)
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.Render(ShapeDescriptor shapeDescriptor, DisplayContext displayContext, HarvestShapeInfo harvestShapeInfo, HarvestShapeHit harvestShapeHit)
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.<>c__DisplayClass26.<>c__DisplayClass28.<Discover>b__15(DisplayContext displayContext)
   at Orchard.DisplayManagement.Descriptors.ShapeAlterationBuilder.<>c__DisplayClass3.<>c__DisplayClass5.<BoundAs>b__2(DisplayContext displayContext)
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context)
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context)
   at Orchard.DisplayManagement.Implementation.DisplayHelper.ShapeExecute(Object shape)
   at Orchard.DisplayManagement.ShapeDisplay.Display(Object shape)
   at Orchard.Email.Services.SmtpMessageChannel.Process(IDictionary`2 parameters)
   at AtlantisCamps.CampModule.Services.ExceptionManager.HandleException(Exception ex, String data)
   at AtlantisCamps.CampModule.Services.APIService.<.ctor>b__0(Exception ex, String info, IExceptionManager mngr)
   at AtlantisCamps.CampModule.Services.APIService.<GetAsync>d__2`1.MoveNext()<---

Please guide on troubleshooting this issue.

**Comment by sebastienros** [comment]
It could happen if the Shapetable is generated during a background task. The solution is to find the code which assumes there is an active request/controller/action where it could be null.

**Comment by infofromca** [comment]
I also got this issue when run during a background task , i guess it is because of null httpContext.

2016-05-03 17:35:31,442 [56] Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator - Default - NullReferenceException thrown from IContentPartDriver by Orchard.Core.Title.Drivers.TitlePartDriver [http://realestateworld:30321/OrchardLocal]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.ShapePlacementParsingStrategy.<>c__DisplayClass8_4.<BuildPredicate>b__7(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapePlacementStrategy\ShapePlacementParsingStrategy.cs:line 158
   at Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.ShapePlacementParsingStrategy.<>c__DisplayClass6_0.<ProcessPlacementFile>b__4(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapePlacementStrategy\ShapePlacementParsingStrategy.cs:line 99
   at Orchard.DisplayManagement.Descriptors.ShapeAlterationBuilder.<>c__DisplayClass13_1.<Placement>b__1(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapeAlterationBuilder.cs:line 104
   at Orchard.ContentManagement.DefaultContentDisplay.<>c__DisplayClass15_0.<BindPlacement>b__0(String partShapeType, String differentiator, String defaultLocation) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\DefaultContentDisplay.cs:line 143
   at Orchard.ContentManagement.Drivers.ContentShapeResult.ApplyImplementation(BuildShapeContext context, String displayType) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 31
   at Orchard.ContentManagement.Drivers.ContentShapeResult.Apply(BuildDisplayContext context) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 23
   at Orchard.ContentManagement.Drivers.CombinedResult.Apply(BuildDisplayContext context) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\CombinedResult.cs:line 28
   at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.<>c__DisplayClass9_0.<BuildDisplay>b__0(IContentPartDriver driver) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\Coordinators\ContentPartDriverCoordinator.cs:line 49
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\InvokeExtensions.cs:line 17
2016-05-03 17:35:31,799 [56] Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator - Default - NullReferenceException thrown from IContentPartDriver by Orchard.Core.Common.Drivers.CommonPartDriver [http://realestateworld:30321/OrchardLocal]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.ShapePlacementParsingStrategy.<>c__DisplayClass8_4.<BuildPredicate>b__7(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapePlacementStrategy\ShapePlacementParsingStrategy.cs:line 158
   at Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.ShapePlacementParsingStrategy.<>c__DisplayClass6_0.<ProcessPlacementFile>b__4(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapePlacementStrategy\ShapePlacementParsingStrategy.cs:line 99
   at Orchard.DisplayManagement.Descriptors.ShapeAlterationBuilder.<>c__DisplayClass13_1.<Placement>b__1(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapeAlterationBuilder.cs:line 104
   at Orchard.ContentManagement.DefaultContentDisplay.<>c__DisplayClass15_0.<BindPlacement>b__0(String partShapeType, String differentiator, String defaultLocation) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\DefaultContentDisplay.cs:line 143
   at Orchard.ContentManagement.Drivers.ContentShapeResult.ApplyImplementation(BuildShapeContext context, String displayType) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 31
   at Orchard.ContentManagement.Drivers.ContentShapeResult.Apply(BuildDisplayContext context) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 23
   at Orchard.ContentManagement.Drivers.CombinedResult.Apply(BuildDisplayContext context) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\CombinedResult.cs:line 28
   at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.<>c__DisplayClass9_0.<BuildDisplay>b__0(IContentPartDriver driver) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\Coordinators\ContentPartDriverCoordinator.cs:line 49
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\InvokeExtensions.cs:line 17
2016-05-03 17:35:32,083 [56] Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator - Default - NullReferenceException thrown from IContentPartDriver by Szmyd.Orchard.Modules.Sharing.Drivers.ShareBarPartDriver [http://realestateworld:30321/OrchardLocal]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.ShapePlacementParsingStrategy.<>c__DisplayClass8_4.<BuildPredicate>b__7(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapePlacementStrategy\ShapePlacementParsingStrategy.cs:line 158
   at Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.ShapePlacementParsingStrategy.<>c__DisplayClass6_0.<ProcessPlacementFile>b__4(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapePlacementStrategy\ShapePlacementParsingStrategy.cs:line 99
   at Orchard.DisplayManagement.Descriptors.ShapeAlterationBuilder.<>c__DisplayClass13_1.<Placement>b__1(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapeAlterationBuilder.cs:line 104
   at Orchard.ContentManagement.DefaultContentDisplay.<>c__DisplayClass15_0.<BindPlacement>b__0(String partShapeType, String differentiator, String defaultLocation) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\DefaultContentDisplay.cs:line 143
   at Orchard.ContentManagement.Drivers.ContentShapeResult.ApplyImplementation(BuildShapeContext context, String displayType) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 31
   at Orchard.ContentManagement.Drivers.ContentShapeResult.Apply(BuildDisplayContext context) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 23
   at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.<>c__DisplayClass9_0.<BuildDisplay>b__0(IContentPartDriver driver) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\Coordinators\ContentPartDriverCoordinator.cs:line 49
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\InvokeExtensions.cs:line 17
2016-05-03 17:35:32,410 [56] Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator - Default - NullReferenceException thrown from IContentPartDriver by Orchard.Core.Title.Drivers.TitlePartDriver [http://realestateworld:30321/OrchardLocal]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.ShapePlacementParsingStrategy.<>c__DisplayClass8_4.<BuildPredicate>b__7(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapePlacementStrategy\ShapePlacementParsingStrategy.cs:line 158
   at Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.ShapePlacementParsingStrategy.<>c__DisplayClass6_0.<ProcessPlacementFile>b__4(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapePlacementStrategy\ShapePlacementParsingStrategy.cs:line 99
   at Orchard.DisplayManagement.Descriptors.ShapeAlterationBuilder.<>c__DisplayClass13_1.<Placement>b__1(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapeAlterationBuilder.cs:line 104
   at Orchard.ContentManagement.DefaultContentDisplay.<>c__DisplayClass15_0.<BindPlacement>b__0(String partShapeType, String differentiator, String defaultLocation) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\DefaultContentDisplay.cs:line 143
   at Orchard.ContentManagement.Drivers.ContentShapeResult.ApplyImplementation(BuildShapeContext context, String displayType) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 31
   at Orchard.ContentManagement.Drivers.ContentShapeResult.Apply(BuildDisplayContext context) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 23
   at Orchard.ContentManagement.Drivers.CombinedResult.Apply(BuildDisplayContext context) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\CombinedResult.cs:line 28
   at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.<>c__DisplayClass9_0.<BuildDisplay>b__0(IContentPartDriver driver) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\Coordinators\ContentPartDriverCoordinator.cs:line 49
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\InvokeExtensions.cs:line 17
2016-05-03 17:35:32,429 [56] Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator - Default - NullReferenceException thrown from IContentPartDriver by Orchard.Core.Common.Drivers.CommonPartDriver [http://realestateworld:30321/OrchardLocal]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.ShapePlacementParsingStrategy.<>c__DisplayClass8_4.<BuildPredicate>b__7(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapePlacementStrategy\ShapePlacementParsingStrategy.cs:line 158
   at Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.ShapePlacementParsingStrategy.<>c__DisplayClass6_0.<ProcessPlacementFile>b__4(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapePlacementStrategy\ShapePlacementParsingStrategy.cs:line 99
   at Orchard.DisplayManagement.Descriptors.ShapeAlterationBuilder.<>c__DisplayClass13_1.<Placement>b__1(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapeAlterationBuilder.cs:line 104
   at Orchard.ContentManagement.DefaultContentDisplay.<>c__DisplayClass15_0.<BindPlacement>b__0(String partShapeType, String differentiator, String defaultLocation) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\DefaultContentDisplay.cs:line 143
   at Orchard.ContentManagement.Drivers.ContentShapeResult.ApplyImplementation(BuildShapeContext context, String displayType) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 31
   at Orchard.ContentManagement.Drivers.ContentShapeResult.Apply(BuildDisplayContext context) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 23
   at Orchard.ContentManagement.Drivers.CombinedResult.Apply(BuildDisplayContext context) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\CombinedResult.cs:line 28
   at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.<>c__DisplayClass9_0.<BuildDisplay>b__0(IContentPartDriver driver) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\Coordinators\ContentPartDriverCoordinator.cs:line 49
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\InvokeExtensions.cs:line 17
2016-05-03 17:35:32,462 [56] Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator - Default - NullReferenceException thrown from IContentPartDriver by Szmyd.Orchard.Modules.Sharing.Drivers.ShareBarPartDriver [http://realestateworld:30321/OrchardLocal]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.ShapePlacementParsingStrategy.<>c__DisplayClass8_4.<BuildPredicate>b__7(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapePlacementStrategy\ShapePlacementParsingStrategy.cs:line 158
   at Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.ShapePlacementParsingStrategy.<>c__DisplayClass6_0.<ProcessPlacementFile>b__4(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapePlacementStrategy\ShapePlacementParsingStrategy.cs:line 99
   at Orchard.DisplayManagement.Descriptors.ShapeAlterationBuilder.<>c__DisplayClass13_1.<Placement>b__1(ShapePlacementContext ctx) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\DisplayManagement\Descriptors\ShapeAlterationBuilder.cs:line 104
   at Orchard.ContentManagement.DefaultContentDisplay.<>c__DisplayClass15_0.<BindPlacement>b__0(String partShapeType, String differentiator, String defaultLocation) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\DefaultContentDisplay.cs:line 143
   at Orchard.ContentManagement.Drivers.ContentShapeResult.ApplyImplementation(BuildShapeContext context, String displayType) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 31
   at Orchard.ContentManagement.Drivers.ContentShapeResult.Apply(BuildDisplayContext context) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\ContentShapeResult.cs:line 23
   at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.<>c__DisplayClass9_0.<BuildDisplay>b__0(IContentPartDriver driver) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\ContentManagement\Drivers\Coordinators\ContentPartDriverCoordinator.cs:line 49
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\InvokeExtensions.cs:line 17

**Comment by mtcindia** [comment]
what is the solution to solve this exception.

**Comment by sebastienros** [comment]
Can you provide some repro?
