### ISSUE TITLE
run 1.10.x, got exception

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6666]
error between 1.10 and 7e11509182db6529c41acfd459a9196e65e4ad76 
homepage or other pages.
sometimes refresh can resolved it , somethings no.
![homepage](https://cloud.githubusercontent.com/assets/297675/14072041/c1bf2f26-f489-11e5-99d4-b7aee53f9aaf.png)

2016-03-27 09:13:43,968 [7] Orchard.Exceptions.DefaultExceptionPolicy - Default - An unexpected exception was caught [http://localhost:30321/OrchardLocal/]
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Web.HttpHeaderCollection.SetHeader(String name, String value, Boolean replace)
   at System.Web.HttpHeaderCollection.Set(String name, String value)
   at System.Collections.Specialized.NameValueCollection.set_Item(String name, String value)
   at Orchard.OutputCache.Filters.OutputCacheFilter.ServeCachedItem(ActionExecutingContext filterContext, CacheItem cacheItem)
   at Orchard.OutputCache.Filters.OutputCacheFilter.OnActionExecuting(ActionExecutingContext filterContext)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
2016-03-27 09:16:33,740 [9] Orchard.Exceptions.DefaultExceptionPolicy - RealEstateWorld - An unexpected exception was caught [http://realestateworld:30321/OrchardLocal/]
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Web.HttpHeaderCollection.SetHeader(String name, String value, Boolean replace)
   at System.Web.HttpHeaderCollection.Set(String name, String value)
   at System.Collections.Specialized.NameValueCollection.set_Item(String name, String value)
   at Orchard.OutputCache.Filters.OutputCacheFilter.ServeCachedItem(ActionExecutingContext filterContext, CacheItem cacheItem)
   at Orchard.OutputCache.Filters.OutputCacheFilter.OnActionExecuting(ActionExecutingContext filterContext)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)

**Comment by infofromca** [comment]
it is inside ServeCachedItem(filterContext, cacheItem); 
etag got null
if (cacheItem.IsValid(_now)) {
                        Logger.Debug("Cached item is valid: {0}", _cacheKey);
                        ServeCachedItem(filterContext, cacheItem);
                        return;
                    }

![etag-null](https://cloud.githubusercontent.com/assets/297675/14555894/344baf50-02c3-11e6-9131-39b294048cd7.png)
