### ISSUE TITLE
NullReferenceException in SessionLocator.DisposeSession()

### ISSUE THREAD

**Issue by 560889223** [OrchardCMS/Orchard#6722]
Hi recently we are seeing NRE in SessionLocator.DisposeSession(). As we use Debug binaries, we managed to pinpoint the exact line that causing the issue:
`_contentManagerSession.Clear();`

I looked at all references to `_contentManagerSession` and it seems to me that the only possible explanation is that `Require()`/`RequireNew()`/`Cancel()`/`Dispose()` was called before `GetSession()` is called. I'm not exactly sure how this (sequence of calls) would happen, but it's happening to us. I'm proposing a simple fix by using the new C# 6.0 syntax:
`_contentManagerSession?.Clear();`

Please let me know your thoughts.

**Comment by jtkech** [comment]
I think it's a good catch.

There are some other issues related to this one. See #6555 where, because i couldn't repro myself, i just also proposed this null check `_session.Transaction != null`. (may also be useful)

But i didn't think about `_contentManagerSession`, maybe because it seemed to me as a normal `IDependency`... This could explain some issues where sessions are not correctly disposed...

But how can `_contentManagerSession` be null? Calling `_contentManagerSession.Clear()` before doesn't explain this. But your debugging proves it.

Right now, just seen that it is not directly injected. It's an auto generated (by autofac) delegate factory func `_contentManagerSessionFactory` that is injected and then used to construct `_contentManagerSession` when creating a new session.

Maybe a thread safety problem when using this factory...

Best.

**Comment by 560889223** [comment]
@jtkech 

To help anyone understand how we found this issue, here is the call stack when exception was thrown:
```
2016-04-07 00:00:53,433 [125] Orchard.Tasks.BackgroundService - (null) - ERROR Error while processing background task "Orchard.Indexing.Services.IndexingBackgroundTask" on tenant "Default".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.Data.TransactionManager.DisposeSession() in C:\projects\orchard\src\Orchard\Data\SessionLocator.cs:line 96
   at Orchard.Data.TransactionManager.RequireNew(IsolationLevel level) in C:\projects\orchard\src\Orchard\Data\SessionLocator.cs:line 68
   at Orchard.Data.TransactionManager.RequireNew() in C:\projects\orchard\src\Orchard\Data\SessionLocator.cs:line 64
   at Orchard.Tasks.BackgroundService.Sweep() in C:\projects\orchard\src\Orchard\Tasks\BackgroundService.cs:line 38
```

To answer "how can `_contentManagerSession` be null", here is my proposed explanation:
1. `_contentManagerSession` can only be set when `EnsureSession()` is called, which is in turn called by `GetSession()`, `Demand()`, and `RequireNew(...)`. However, `Demand()` is not called by anyone other than `GetSession()`, and `RequireNew(...)` would call `DisposeSession()` first and throw an NRE inevitably, the only caller that will **safely** set `_contentManagerSession` is `GetSession()`.
2. I analyzed the calls to `GetSession()`, and my conclusion is that it is called only when anyone is trying to touch data (get/update/remove). There are framework references from these classes:
 * `DefaultContentManager`
 * `DefaultDataMigrationInterpreter`
 * `SessionLocator`
 * `TransactionFilter`
3. On the other hand, `DisposeSession()`, which calls `_contentManagerSession.Clear()`, is called by `RequireNew()`/`RequireNew(...)`/`Cancel()`/`Dispose()`.
4. If for somehow, any of the above is called before `GetSession()`, say `ITransactionManager.RequireNew()`, `_contentManagerSession` will be `null` when executing `_contentManagerSession.Clear()` from `DisposeSession()`. Looking at the code in `BackgroundService.Sweep()` and its (theoratical) call stack starting from `SweepGenerator.Elapsed()`, it seems to me that this is destined to happen, if no other code will be involved.

Does anyone think of a reason that this `BackgroundService.Sweep()` thing shouldn't be happening this way? Otherwise, I will prepare a fix based on 1.10.x if that's the branch this issue should target.

**Comment by 560889223** [comment]
PR #6722 is prepared

**Comment by jtkech** [comment]
Anyway your fix is good but, if possible, would be good to know the root cause.

So, i try to understand your analysis. When `DisposeSession()` is called, if `_contentManagerSession` is null (not already set), "normally", `_session` is also null, so `_contentManagerSession.Clear()` is not called...

Except if there are concurrent accesses of the same instance (but it would not be normal), one having set `_session` but not yet `_contentManagerSession`, and another executing `DisposeSession()`...

Best

**Comment by 560889223** [comment]
@jtkech Ah, now I see your point and why you would think of race condition. However, yet following your insights, I found this exception in the log, which will well explain why the code path has ever gone down to _contentManagerSession.Clear() when _session is not null but _contentManagerSession is.
```
2016-04-07 00:18:53,613 [163] Orchard.Tasks.BackgroundService - (null) - ERROR Error while processing background task "Orchard.Alias.Implementation.Updater.AliasHolderUpdaterTask" on tenant "Default".
NHibernate.TransactionException: Begin failed with SQL exception ---> System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.SqlClient.SqlConnection.Open()
   at NHibernate.Connection.DriverConnectionProvider.GetConnection()
   at NHibernate.AdoNet.ConnectionManager.GetConnection()
   at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel)
   --- End of inner exception stack trace ---
   at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel)
   at NHibernate.Impl.SessionImpl.BeginTransaction(IsolationLevel isolationLevel)
   at Orchard.Data.TransactionManager.EnsureSession(IsolationLevel level) in C:\projects\chichard\src\Orchard\Data\SessionLocator.cs:line 114
   at Orchard.Data.TransactionManager.RequireNew(IsolationLevel level) in C:\projects\chichard\src\Orchard\Data\SessionLocator.cs:line 69
   at Orchard.Data.TransactionManager.RequireNew() in C:\projects\chichard\src\Orchard\Data\SessionLocator.cs:line 64
   at Orchard.Tasks.BackgroundService.Sweep() in C:\projects\chichard\src\Orchard\Tasks\BackgroundService.cs:line 38
```
Now looking at `EnsureSession()`:
```
        private void EnsureSession(IsolationLevel level) {
            // ... 
            // not so important code, ellipsed
            // ...
            _session = sessionFactory.OpenSession(new OrchardSessionInterceptor(_interceptors.ToArray(), Logger));
            _session.BeginTransaction(level);
            _contentManagerSession = _contentManagerSessionFactory();
        }
```
If `_session.BeginTransaction(level)` throws exception, as indicated from the log, `_contentManagerSession` will not be set and remain null, yet `_session` is assigned. So a more logical fix would put a try-catch block around `_session.BeginTransaction(level)` (or even including the line above) to set `_session` back to null if anything goes wrong.

**Comment by jtkech** [comment]
You saved my night because i was trying to find another source, e.g around dependency injection...

Indeed, this is one of the possible reason i thought, but because nobody reported this exception... What's good with you is that you report real facts with which we can progress...

So, let me think about this, maybe we can enhance your related PR, e.g with a try / catch. I also think about a null check  on `_session.Transaction` before checking `_session.Transaction.IsActive`. This e.g when not in a try block as in `Cancel()`...

Best

**Comment by 560889223** [comment]
@jtkech 

I have updated the PR with more changes around accessing `_session` and `_session.Transaction`. Please let me know your thoughts. How would you suggest me doing the testing? I'm going to make sure the normal case is still working, but I'm not sure if I should test against the exact situation we are preventing from (say DB connection pool full)

**Comment by jtkech** [comment]
Ok.

There would be so many cases to check. So, the goal is to let things as much as possible as they was. We still have to let nhibernate surface its exceptions but prevent our own exceptions. This to not mix problems.

So, maybe the best is to only do your first null check. But it was so important to know the root cause. I'll take a look directly on the PR.

See also #5653, it may help you to configure retries logic for connections.

Best.

**Comment by 560889223** [comment]
Hi @jtkech I did update the PR to reflect your latest comments. I'm taking the advice on new syntax as it makes sense to enable people who use VS2013 to build it. Also now the fix relies on global exception handling to dispose the session object when exception is thrown from BeginTransaction.
