### ISSUE TITLE
the "get_IsReadOnlyInitialized" of NHibernate.Linq.Util.DetachedCriteriaAdapter was not implemented

### ISSUE THREAD

**Issue by ensleep** [OrchardCMS/Orchard#6747]
My Enviranment is Chinese.And I got the exception when configed the setup (write site name,admin name ,pwd,database,and so on) to waiting the site initialing.
the chinese message of exception is:

`引发的异常:“System.TypeLoadException”(位于 NHibernate.Linq.dll 中)
Orchard.Exceptions.DefaultExceptionPolicy: ERROR - An unexpected exception was caught
System.TypeLoadException: 程序集“NHibernate.Linq, Version=1.1.0.1001, Culture=neutral, PublicKeyToken=null”中的类型“NHibernate.Linq.Util.DetachedCriteriaAdapter”的方法“get_IsReadOnlyInitialized”没有实现。
   在 NHibernate.Linq.Util.CriteriaUtil.GetRootType(ICriteria criteria)
   在 NHibernate.Linq.Visitors.MemberNameVisitor.IsRootEntity(EntityExpression expr)
   在 NHibernate.Linq.Visitors.MemberNameVisitor.VisitEntity(EntityExpression expr)
   在 NHibernate.Linq.Visitors.NHibernateExpressionVisitor.Visit(Expression exp)
   在 NHibernate.Linq.Visitors.NHibernateExpressionVisitor.VisitPropertyAccess(PropertyAccessExpression expr)
   在 NHibernate.Linq.Visitors.MemberNameVisitor.VisitPropertyAccess(PropertyAccessExpression expr)
   在 NHibernate.Linq.Visitors.NHibernateExpressionVisitor.Visit(Expression exp)
   在 NHibernate.Linq.Visitors.ExpressionVisitor.VisitLambda(LambdaExpression lambda)
   在 NHibernate.Linq.Visitors.ExpressionVisitor.Visit(Expression exp)
   在 NHibernate.Linq.Visitors.NHibernateExpressionVisitor.Visit(Expression exp)
   在 NHibernate.Linq.Visitors.MemberNameVisitor.GetMemberName(ICriteria rootCriteria, Expression expr)
   在 NHibernate.Linq.Visitors.RootVisitor.HandleOrderByCall(MethodCallExpression call)
   在 NHibernate.Linq.Visitors.RootVisitor.VisitMethodCall(MethodCallExpression expr)
   在 NHibernate.Linq.Visitors.ExpressionVisitor.Visit(Expression exp)
   在 NHibernate.Linq.Visitors.NHibernateExpressionVisitor.Visit(Expression exp)
   在 NHibernate.Linq.Visitors.NHibernateQueryTranslator.TranslateInternal(Expression expression)
   在 NHibernate.Linq.Visitors.NHibernateQueryTranslator.Translate(Expression expression, QueryOptions queryOptions)
   在 NHibernate.Linq.NHibernateQueryProvider.TranslateExpression(Expression expression)
   在 Orchard.ContentManagement.DefaultContentQuery.OrderBy[TRecord,TKey](Expression`1 keySelector) 位置 E:\Repos\Orchard\Orchard-1.10.x\src\Orchard\ContentManagement\DefaultContentQuery.cs:行号 150`

my version is 1.10.x. Please help me....

**Comment by sebastienros** [comment]
Are you using SysCache module? If so then please disable it.

**Comment by ensleep** [comment]
@sebastienros I am trying to find where I enable the SysCache . But I have not found it.
Just a Orchard.Caching Module Project in the sln.Could you tell me how to find it?not in web.config,host.config,Sites.config.

**Comment by sebastienros** [comment]
In the Orchard dashboard, go into Modules, look for the SysCAche feature, disable it.

**Comment by ensleep** [comment]
Oh,this error is apeared when I am installing the Orchard.So I have not got a dashboard.But now I using the 1.9.So there is no error like this.Thank you!

**Comment by ninety7** [comment]
Same error here with v1.10.1. Source did not compile until I added NHibernate.Linq nuget package v1.0.0 to Orchard.Framework project

**Comment by parxal** [comment]
Same  problem installing a fresh new version 1.10.2, Visual Studio 2017, When opening the solution  NHibernate.Linq nuget package  is missing, add that, try to install on sql server 2016, tables are created but orchard never starts, i get that error...

**Comment by sebastienros** [comment]
Can anyone repro it?

**Comment by Calvijn** [comment]
Same problem here.
Error is right during the Setup. 

`Orchard.Exceptions.DefaultExceptionPolicy - Default - ERROR An unexpected exception was caught
System.TypeLoadException: Method 'get_IsReadOnlyInitialized' in type 'NHibernate.Linq.Util.DetachedCriteriaAdapter' from assembly 'NHibernate.Linq, Version=1.1.0.1001, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at NHibernate.Linq.Util.CriteriaUtil.GetRootType(ICriteria criteria)
   at NHibernate.Linq.Visitors.MemberNameVisitor.IsRootEntity(EntityExpression expr)
   at NHibernate.Linq.Visitors.MemberNameVisitor.VisitEntity(EntityExpression expr)
   at NHibernate.Linq.Visitors.NHibernateExpressionVisitor.Visit(Expression exp)
   at NHibernate.Linq.Visitors.NHibernateExpressionVisitor.VisitEntity(EntityExpression expr)
   at NHibernate.Linq.Visitors.MemberNameVisitor.VisitEntity(EntityExpression expr)
   at NHibernate.Linq.Visitors.NHibernateExpressionVisitor.Visit(Expression exp)
   at NHibernate.Linq.Visitors.NHibernateExpressionVisitor.VisitPropertyAccess(PropertyAccessExpression expr)
   at NHibernate.Linq.Visitors.MemberNameVisitor.VisitPropertyAccess(PropertyAccessExpression expr)
   at NHibernate.Linq.Visitors.NHibernateExpressionVisitor.Visit(Expression exp)
   at NHibernate.Linq.Visitors.MemberNameVisitor.GetMemberName(ICriteria rootCriteria, Expression expr)
   at NHibernate.Linq.Visitors.WhereArgumentsVisitor.GetCollectionContainsCriteria(Expression list, Expression containedExpr)
   at NHibernate.Linq.Visitors.WhereArgumentsVisitor.VisitMethodCall(MethodCallExpression expr)
   at NHibernate.Linq.Visitors.ExpressionVisitor.Visit(Expression exp)
   at NHibernate.Linq.Visitors.NHibernateExpressionVisitor.Visit(Expression exp)
   at NHibernate.Linq.Visitors.ExpressionVisitor.VisitLambda(LambdaExpression lambda)
   at NHibernate.Linq.Visitors.ExpressionVisitor.Visit(Expression exp)
   at NHibernate.Linq.Visitors.NHibernateExpressionVisitor.Visit(Expression exp)
   at NHibernate.Linq.Visitors.WhereArgumentsVisitor.VisitUnary(UnaryExpression expr)
   at NHibernate.Linq.Visitors.ExpressionVisitor.Visit(Expression exp)
   at NHibernate.Linq.Visitors.NHibernateExpressionVisitor.Visit(Expression exp)
   at NHibernate.Linq.Visitors.WhereArgumentsVisitor.GetCriterion(ICriteria rootCriteria, ISession session, Expression expression)
   at NHibernate.Linq.Visitors.RootVisitor.HandleWhereCall(MethodCallExpression call)
   at NHibernate.Linq.Visitors.RootVisitor.VisitMethodCall(MethodCallExpression expr)
   at NHibernate.Linq.Visitors.ExpressionVisitor.Visit(Expression exp)
   at NHibernate.Linq.Visitors.NHibernateExpressionVisitor.Visit(Expression exp)
   at NHibernate.Linq.Visitors.NHibernateQueryTranslator.TranslateInternal(Expression expression)
   at NHibernate.Linq.Visitors.NHibernateQueryTranslator.Translate(Expression expression, QueryOptions queryOptions)
   at NHibernate.Linq.NHibernateQueryProvider.TranslateExpression(Expression expression)
   at Orchard.ContentManagement.DefaultContentQuery.Where[TRecord](Expression`1 predicate, ICriteria bindCriteria)
   at Orchard.ContentManagement.DefaultContentQuery.Where[TRecord](Expression`1 predicate)
   at Orchard.ContentManagement.DefaultContentQuery.ContentQuery`1.Orchard.ContentManagement.IContentQuery<T>.Where[TRecord](Expression`1 predicate)
   at Orchard.Widgets.Services.WidgetsService.GetWidgets(Int32[] layerIds)
   at Orchard.Widgets.Filters.WidgetFilter.OnResultExecuting(ResultExecutingContext filterContext)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
`

**Comment by sebastienros** [comment]
I just updated to the dev branch, opened it on VS 2017 and the reference was correct. Also could go through Setup.
