### ISSUE TITLE
'orchard_framework_distributedlockrecord' table doe not exist when MySQL is used for database?

### ISSUE THREAD

**Issue by ramiassi** [OrchardCMS/Orchard#6803]
'Orchard.JobsQueue.Services.JobsQueueProcessor'.
NHibernate.Exceptions.GenericADOException: could not execute query
[ select distribute0_.Id as Id3616_, distribute0_.Name as Name3616_, distribute0_.MachineName as MachineN3_3616_, distribute0_.CreatedUtc as CreatedUtc3616_, distribute0_.ValidUntilUtc as ValidUnt5_3616_ from Orchard_Framework_DistributedLockRecord distribute0_ where distribute0_.Name=?p0 and (distribute0_.ValidUntilUtc is null or distribute0_.ValidUntilUtc>=?p1) limit 1 ]
  Name:p1 - Value:DistributedLock:Default:Orchard.JobsQueue.Services.JobsQueueProcessor  Name:p3 - Value:4/19/2016 12:00:35 PM
[SQL: select distribute0_.Id as Id3616_, distribute0_.Name as Name3616_, distribute0_.MachineName as MachineN3_3616_, distribute0_.CreatedUtc as CreatedUtc3616_, distribute0_.ValidUntilUtc as ValidUnt5_3616_ from Orchard_Framework_DistributedLockRecord distribute0_ where distribute0_.Name=?p0 and (distribute0_.ValidUntilUtc is null or distribute0_.ValidUntilUtc>=?p1) limit 1] ---> MySql.Data.MySqlClient.MySqlException: Table 'orchard_framework_distributedlockrecord' doesn't exist
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   --- End of inner exception stack trace ---

**Comment by BenedekFarkas** [comment]
#6783 is probably related.

**Comment by sebastienros** [comment]
What branch do you see this issue on?

**Comment by ramiassi** [comment]
Orchard 1.10
