### ISSUE TITLE
On azure, error thrown from OutputCacheFilter

### ISSUE THREAD

**Issue by daxu7509** [OrchardCMS/Orchard#6813]
Hi,
We have ORchard hosted in azure as a web app, from azure log, we see vast amount of error got thrown out with exception below. Can someone suggest why this error can happen?

Orchard.OutputCache.Filters.OutputCacheFilter - Default - An unexpected error occured while reading a cache entry
System.Runtime.Serialization.SerializationException: Assembly 'App_Web_suev4fil, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is not found.
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeInSharedTypeMode(XmlReaderDelegator xmlReader, Int32 declaredTypeID, Type declaredType, String name, String ns)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, String name, String ns)
   at System.Runtime.Serialization.NetDataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   at Microsoft.ApplicationServer.Caching.NetDataContractCacheObjectSerializer.Deserialize(Stream stream)
   at Microsoft.ApplicationServer.Caching.DataCacheObjectSerializationProvider.DeserializeUserObject(Byte[][] serializedData, ValueFlagsVersion flagsType)
   at Microsoft.ApplicationServer.Caching.SocketClientProtocol.Get(String key, DataCacheItemVersion& version, TimeSpan& timeout, ErrStatus& err, String region, IMonitoringListener listener)
   at Microsoft.ApplicationServer.Caching.DataCache.InternalGet(String key, DataCacheItemVersion& version, String region, IMonitoringListener listener)
   at Microsoft.ApplicationServer.Caching.DataCache.<>c__DisplayClass5b.<Get>b__5a()
   at Microsoft.ApplicationServer.Caching.MonitoringListenerFactory.EmptyListener.Microsoft.ApplicationServer.Caching.IMonitoringListener.Listen[TResult](Func`1 innerDelegate)
   at Microsoft.ApplicationServer.Caching.DataCache.Get(String key, String region)
   at Orchard.Azure.Services.Caching.Output.AzureOutputCacheStorageProvider.<>c__DisplayClassf.<GetCacheItem>b__e()
   at Orchard.Azure.Services.Caching.Output.AzureOutputCacheStorageProvider.Retry[T](Func`1 function, Int32 times)
   at Orchard.Azure.Services.Caching.Output.AzureOutputCacheStorageProvider.GetCacheItem(String key)
   at Orchard.OutputCache.Filters.OutputCacheFilter.GetCacheItem(String key)

**Comment by sebastienros** [comment]
It seems you are using the wrong module to cache data on azure. If you have a single instance on azure you don't need any Azure Cache module. Otherwise you should use the Redis CAche module which is compatible with Azure Redis Cache.
