### ISSUE TITLE
Orchard 1.10.1 redist will not run when unzipped

### ISSUE THREAD

**Issue by robertmclaws** [OrchardCMS/Orchard#6858]
Was told to open a new issue by @sebastienros. 

If you download Orchard.Web.1.10.1.zip, unzip it, and then point IISExpress at the unpacked version, the website won't run. Same is true if you download the source, run the build script, and then point IISExpress at Orchard.Web. The log files say that it can't find System.Data.DataSetExtensions, though, if you turn off CustomErrors, .NET throws an AutoFac error.

**Comment by agriffard** [comment]
see #6406

**Comment by agriffard** [comment]
#6406

**Comment by sebastienros** [comment]
Let's follow up with this issue as the other one was labeled for 1.10.
I tried yesterday and it worked fine on my machine.

Is the issue about having modules which require `System.Data.DataSetExtensions` ?
Which modules exactly don't work without it?

**Comment by donaldboulton** [comment]
I got 1.10.1, Two days after it was posted vanilla IIS install and there is no errors, nothing in the logs and nothing asking for System.Data.DataSetExtensions. Some third party modules are ask for it.

**Comment by sebastienros** [comment]
Doesn't work on some servers. Need to find the differences.

**Comment by advancedrei** [comment]
The steps here solved the problem for me: https://github.com/OrchardCMS/Orchard/issues/6406#issuecomment-216208329

The issue: The web.config is either not including or actively removing assemblies from compilation that are needed by several of the modules.

**Comment by sebastienros** [comment]
Will update the packages on the release page as soon as the CI passes

**Comment by sebastienros** [comment]
Packages updated on the 1.10.1 release page

**Comment by agriffard** [comment]
There is still another problem. Some modules that reference other modules and have the <add assembly... in their web.config, don't compile :

`2016-05-06 10:47:30,169 [15] Orchard.Environment.Extensions.ExtensionManager - (null) - WARN No suitable loader found for extension "Orchard.Resources"
2016-05-06 10:48:05,786 [7] Orchard.Environment.DefaultBuildManager - Default - WARN Error when compiling assembly under ~/Modules/Orchard.Dashboards/Orchard.Dashboards.csproj.
System.Configuration.ConfigurationErrorsException: Could not load file or assembly 'Orchard.Layouts' or one of its dependencies. The system cannot find the file specified. (D:\Antoine\Orchard.Web.1.10.1\Orchard\modules\orchard.dashboards\web.config line 35) ---> System.IO.FileNotFoundException: Could not load file or assembly 'Orchard.Layouts' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective)
   --- End of inner exception stack trace ---
   at System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective)
   at System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai)
   at System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig)
   at System.Web.Compilation.WebDirectoryBatchCompiler..ctor(VirtualDirectory vdir)
   at System.Web.Compilation.BuildManager.BatchCompileWebDirectoryInternal(VirtualDirectory vdir, Boolean ignoreErrors)
   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResult(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetCompiledAssembly(String virtualPath)
   at Orchard.Environment.DefaultBuildManager.GetCompiledAssembly(String virtualPath)
2016-05-06 10:48:08,755 [7] Orchard.Environment.DefaultBuildManager - Default - WARN Error when compiling assembly under ~/Modules/Orchard.DynamicForms/Orchard.DynamicForms.csproj.
System.Configuration.ConfigurationErrorsException: Could not load file or assembly 'Orchard.Layouts' or one of its dependencies. The system cannot find the file specified. (D:\Antoine\Orchard.Web.1.10.1\Orchard\modules\orchard.dynamicforms\web.config line 35) ---> System.IO.FileNotFoundException: Could not load file or assembly 'Orchard.Layouts' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective)
   --- End of inner exception stack trace ---
   at System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective)
   at System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai)
   at System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig)
   at System.Web.Compilation.WebDirectoryBatchCompiler..ctor(VirtualDirectory vdir)
   at System.Web.Compilation.BuildManager.BatchCompileWebDirectoryInternal(VirtualDirectory vdir, Boolean ignoreErrors)
   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResult(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetCompiledAssembly(String virtualPath)
   at Orchard.Environment.DefaultBuildManager.GetCompiledAssembly(String virtualPath)
2016-05-06 10:48:09,442 [7] Orchard.Environment.DefaultBuildManager - Default - WARN Error when compiling assembly under ~/Modules/Orchard.ImageEditor/Orchard.ImageEditor.csproj.
System.Configuration.ConfigurationErrorsException: Could not load file or assembly 'Orchard.MediaLibrary' or one of its dependencies. The system cannot find the file specified. (D:\Antoine\Orchard.Web.1.10.1\Orchard\modules\orchard.imageeditor\web.config line 33) ---> System.IO.FileNotFoundException: Could not load file or assembly 'Orchard.MediaLibrary' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective)
   --- End of inner exception stack trace ---
   at System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective)
   at System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai)
   at System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig)
   at System.Web.Compilation.WebDirectoryBatchCompiler..ctor(VirtualDirectory vdir)
   at System.Web.Compilation.BuildManager.BatchCompileWebDirectoryInternal(VirtualDirectory vdir, Boolean ignoreErrors)
   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResult(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetCompiledAssembly(String virtualPath)
   at Orchard.Environment.DefaultBuildManager.GetCompiledAssembly(String virtualPath)
`

**Comment by advancedrei** [comment]
Yep, I had the ImageEditor issues too. Did you restart IIS after updating the web,config? Orchard started up for me after that, though I'm not sure the problem was actually solved.

On another note, I totally get why you added the "<remove/>" entries to the compilation section, the memory footprint for Orchard is much better than previous versions. But when modules don't make it clear what assemblies they are loading, and Orchard doesn't have a built-in way to compensate when a module-referenced assembly is on the "remove" list, it seems to be doing more harm than good.

Just something to think about.
