### ISSUE TITLE
OutputCacheFilter  exeption after updateing to  latest 1.10.1

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6875]
2:09:57,070 [6] Orchard.OutputCache.Filters.OutputCacheFilter 
- Default - An unexpected error occured while reading a cache entry [http://localhost:30321/OrchardLocal/]
System.ArgumentException: Invalid path
   at Orchard.Validation.PathValidation.ValidatePath(String basePath, String mappedPath) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\Validation\PathValidation.cs:line 29
   at Orchard.FileSystems.AppData.AppDataFolder.CombineToPhysicalPath(String[] paths) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\FileSystems\AppData\AppDataFolder.cs:line 95
   at Orchard.FileSystems.AppData.AppDataFolder.FileExists(String path) in C:\Users\andy\Documents\orchard110house-zg\Orchard1203\Orchard\src\Orchard\FileSystems\AppData\AppDataFolder.cs:line 158
   at Orchard.OutputCache.Services.FileSystemOutputCacheStorageProvider.<>c__DisplayClass12_0.<GetCacheItem>b__0()
   at Orchard.OutputCache.Services.FileSystemOutputCacheStorageProvider.Retry[T](Func`1 action)
   at Orchard.OutputCache.Services.FileSystemOutputCacheStorageProvider.GetCacheItem(String key)
   at Orchard.OutputCache.Filters.OutputCacheFilter.GetCacheItem(String key)

![cache-exp](https://cloud.githubusercontent.com/assets/297675/15093259/189ebe2a-1450-11e6-826c-76dac7746dc2.png)
![cache-exp-path](https://cloud.githubusercontent.com/assets/297675/15093260/189f1adc-1450-11e6-8bd5-9d7906879934.png)

**Comment by infofromca** [comment]
![cache-ex-p](https://cloud.githubusercontent.com/assets/297675/15093387/55be549c-1454-11e6-8eb2-939dc3420063.png)

**Comment by infofromca** [comment]
use clean code, it is ok, so close it
