### ISSUE TITLE
Serialization Exception when entering invalid value in ReCaptcha on Custom Forms in a Web Farm setup Orchard Version 1.9.1)

### ISSUE THREAD

**Issue by Garpo001** [OrchardCMS/Orchard#7461]
A Serialization error is thrown when submitting a Custom form with an incorrect value for ReCaptcha in a web farm environment (using State Server / SQL Server for session state)

```
Exception information: 
    Exception type: SerializationException 
    Exception message: Type 'Orchard.UI.Zones.ZoneHolding' in Assembly 'Orchard.Framework, Version=1.9.1.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArrayMember(WriteObjectInfo objectInfo, NameInfo arrayElemTypeNameInfo, Object data)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray(WriteObjectInfo objectInfo, NameInfo memberNameInfo, WriteObjectInfo memberObjectInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers)
   at System.Web.Util.AltSerialization.WriteValueToStream(Object value, BinaryWriter writer)

```
In order to replicate, setup an instance of Orchard and configure session state to use State Server or SQL Server. Create a Custom Form with input fields and add a ReCaptha part. Browse to Custom form on front end. Enter incorrect ReCaptha value and try to submit Form. Serialization error occurs with "Oops something went wrong.." message instead of appropriate action allowing user to re-enter ReCapha value.

Apologies incorrectly referred to Dynamic forms when in fact it is Custom form

**Comment by sebastienros** [comment]
There is shape that somehow goes into the Session, probably with TempData. Could you provide some repro steps?

**Comment by Garpo001** [comment]
@sebastienros I believe the shape associated with the reCaptcha is the culprit. It only happens when a custom form has a reCapcha on it. I did include repro steps on original post after Exception Information. Please advise if this is not sufficient so I can provide more details.

**Comment by sebastienros** [comment]
I will try to repro the issue locally: Custom Form + Recaptcha

**Comment by sebastienros** [comment]
Commenting to bump it in the list.

**Comment by sebastienros** [comment]
I couldn't repro locally, here are my steps:

- Enable the ASP.NET State Service locally
- change the web.config to use it

```
      <sessionState mode="StateServer"
        stateConnectionString="tcpip=localhost:42424"
        cookieless="false"
        timeout="20"/>
```

- Created a custom form `MyForm` with a Text field and the reCaptcha
- Configured the keys for reCaptcha
- Submitted a form

I could not see any issue.
