### ISSUE TITLE
User tokens cause failure on user created and creating workflow events

### ISSUE THREAD

**Issue by mvarblow** [OrchardCMS/Orchard#7481]
The problem seems to go back to previous releases, but with a vanilla Orchard 1.10.1 installation if you create a workflow triggered by a User Created or User Creating activity and reference any user tokens (e.g. from a notification or email activity) the workflow will crash and the following will show up in the error log:

2016-12-20 16:52:36,768 [93] Orchard.Exceptions.DefaultExceptionPolicy - Default - An unexpected exception was caught [http://localhost:30321/OrchardLocal/Users/Account/Register?ReturnUrl=%2FOrchardLocal%2F]
System.InvalidCastException: Unable to cast object of type 'Orchard.Users.Events.UserContext' to type 'Orchard.Security.IUser'.
   at Orchard.Tokens.Implementation.TokenManager.EvaluateContextImpl.For[TData](String target, Func`1 defaultData)
   at Orchard.Tokens.Providers.UserTokens.Evaluate(EvaluateContext context)
   at Orchard.Events.DelegateHelper.<>c__DisplayClass14_0`2.<BuildAction>b__0(Object target, Object[] p) in C:\Code\Temp\Orchard-1.10.1\src\Orchard\Events\DelegateHelper.cs:line 116
   at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) in C:\Code\Temp\Orchard-1.10.1\src\Orchard\Events\DefaultOrchardEventBus.cs:line 84
   at Orchard.Events.DefaultOrchardEventBus.TryInvoke(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) in C:\Code\Temp\Orchard-1.10.1\src\Orchard\Events\DefaultOrchardEventBus.cs:line 70
   at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue) in C:\Code\Temp\Orchard-1.10.1\src\Orchard\Events\DefaultOrchardEventBus.cs:line 53

The problem seems to be that the events are triggered with a "User" token that contains a UserContext data element:

        public void Creating(UserContext context) {
            _workflowManager.TriggerEvent("UserCreating",
                                         context.User,
                                         () => new Dictionary<string, object> {{"User", context}});
        }

        public void Created(UserContext context) {
            _workflowManager.TriggerEvent("UserCreated",
                                         context.User,
                                         () => new Dictionary<string, object> {{"User", context}});
        }

But the UserTokens provider also adds a User token with an IUser object as the "default" value.

        public void Evaluate(EvaluateContext context) {
            context.For("User", () => _orchardServices.WorkContext.CurrentUser ?? _anonymousUser)
                .Token("Name", u => u.UserName)
                .Token("Email", u => u.Email)
                .Token("Id", u => u.Id)
                .Chain("Content", "Content", u => u.ContentItem);
            // todo: cross-module dependency -- should be provided by the User module?
            //.Token("Roles", user => string.Join(", ", user.As<UserRolesPart>().Roles.ToArray()));
        }

The TokenManager.For method attempts to cast the UserContext object to an IUser object.  This cast fails.

            public override EvaluateFor<TData> For<TData>(string target, Func<TData> defaultData) {
                if (string.Equals(target, _target, StringComparison.InvariantCulture)) {
                    var data = default(TData);
                    object value;
                    if (_data != null && _data.TryGetValue(target, out value)) {  // <--- this cast fails
                        data = (TData)value;
                    }
                    else if (defaultData != null) {
                        data = defaultData();
                    }

                    return new EvaluateForImpl<TData>(this, data);
                }

                return new EvaluateForSilent<TData>();
            }

I think the fix is probably to change the Creating and Created events to push two token values - "User" would come from context.User (which is an IUser) and "UserParams" from context.UserParameters.

**Comment by sebastienros** [comment]
Can you point us to the change that introduced the issue? Just to be sure your PR is not conflicting with it.

**Comment by mvarblow** [comment]
As far as I can tell, the problem has been there since the initial commit of the tokens module.
https://github.com/OrchardCMS/Orchard/commit/f2bb3ee47a801cf428f20f5e4776231c3bcaab27
