### ISSUE TITLE
Openid: Server Error after enable google feature

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#7544]
1-- login as admin, enable openid and  google features
2--add google credential,use original CallbackPath(not changed it),   save
3- logout
4-clean sln
5-build sln
6 -run it
got this error
![google-enabled](https://cloud.githubusercontent.com/assets/297675/22400600/9fcff7a2-e587-11e6-8138-bd471d45d632.png)
===============
2017-01-28 18:06:35,917 [11] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default Attempt number: 0 [(null)]
System.ArgumentException: The path must start with a '/' followed by one or more characters.
Parameter name: value
   at Microsoft.Owin.PathString..ctor(String value)
   at Orchard.OpenId.OwinMiddlewares.Google.GetOwinMiddlewares()
   at Orchard.Environment.DefaultOrchardShell.<>c.<Activate>b__16_0(IOwinMiddlewareProvider p) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 61
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Orchard.Environment.DefaultOrchardShell.Activate() in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 64
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 210
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__41_1(ShellSettings settings) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 167
2017-01-28 18:06:37,798 [11] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default after 1 retries. [(null)]
2017-01-28 18:06:38,920 [11] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default Attempt number: 0 [(null)]
System.ArgumentException: The path must start with a '/' followed by one or more characters.
Parameter name: value
   at Microsoft.Owin.PathString..ctor(String value)
   at Orchard.OpenId.OwinMiddlewares.Google.GetOwinMiddlewares()
   at Orchard.Environment.DefaultOrchardShell.<>c.<Activate>b__16_0(IOwinMiddlewareProvider p) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 61
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Orchard.Environment.DefaultOrchardShell.Activate() in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 64
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 210
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__41_1(ShellSettings settings) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 167
2017-01-28 18:06:40,591 [11] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default after 1 retries. [(null)]
2017-01-28 18:06:41,691 [14] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default Attempt number: 0 [http://localhost:30321/OrchardLocal/]
System.ArgumentException: The path must start with a '/' followed by one or more characters.
Parameter name: value
   at Microsoft.Owin.PathString..ctor(String value)
   at Orchard.OpenId.OwinMiddlewares.Google.GetOwinMiddlewares()
   at Orchard.Environment.DefaultOrchardShell.<>c.<Activate>b__16_0(IOwinMiddlewareProvider p) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 61
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Orchard.Environment.DefaultOrchardShell.Activate() in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 64
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 210
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__41_1(ShellSettings settings) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 167
2017-01-28 18:06:43,462 [14] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default after 1 retries. [http://localhost:30321/OrchardLocal/]
2017-01-28 18:06:55,052 [13] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default Attempt number: 0 [http://localhost:30321/OrchardLocal/]
System.ArgumentException: The path must start with a '/' followed by one or more characters.
Parameter name: value
   at Microsoft.Owin.PathString..ctor(String value)
   at Orchard.OpenId.OwinMiddlewares.Google.GetOwinMiddlewares()
   at Orchard.Environment.DefaultOrchardShell.<>c.<Activate>b__16_0(IOwinMiddlewareProvider p) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 61
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Orchard.Environment.DefaultOrchardShell.Activate() in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 64
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 210
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__41_1(ShellSettings settings) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 167
2017-01-28 18:06:56,815 [13] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default after 1 retries. [http://localhost:30321/OrchardLocal/]
2017-01-28 18:07:16,712 [14] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default Attempt number: 0 [http://localhost:30321/OrchardLocal/]
System.ArgumentException: The path must start with a '/' followed by one or more characters.
Parameter name: value
   at Microsoft.Owin.PathString..ctor(String value)
   at Orchard.OpenId.OwinMiddlewares.Google.GetOwinMiddlewares()
   at Orchard.Environment.DefaultOrchardShell.<>c.<Activate>b__16_0(IOwinMiddlewareProvider p) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 61
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Orchard.Environment.DefaultOrchardShell.Activate() in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 64
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 210
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__41_1(ShellSettings settings) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 167
2017-01-28 18:07:18,428 [14] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default after 1 retries. [http://localhost:30321/OrchardLocal/]
2017-01-28 18:07:19,807 [10] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default Attempt number: 0 [http://localhost:30321/OrchardLocal/Users/Account/LogOn?ReturnUrl=%2FOrchardLocal%2F]
System.ArgumentException: The path must start with a '/' followed by one or more characters.
Parameter name: value
   at Microsoft.Owin.PathString..ctor(String value)
   at Orchard.OpenId.OwinMiddlewares.Google.GetOwinMiddlewares()
   at Orchard.Environment.DefaultOrchardShell.<>c.<Activate>b__16_0(IOwinMiddlewareProvider p) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 61
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Orchard.Environment.DefaultOrchardShell.Activate() in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 64
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 210
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__41_1(ShellSettings settings) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 167
2017-01-28 18:07:21,534 [10] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default after 1 retries. [http://localhost:30321/OrchardLocal/Users/Account/LogOn?ReturnUrl=%2FOrchardLocal%2F]
2017-01-28 18:07:22,897 [12] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default Attempt number: 0 [http://localhost:30321/OrchardLocal/Users/Account/LogOn?ReturnUrl=%2FOrchardLocal%2F]
System.ArgumentException: The path must start with a '/' followed by one or more characters.
Parameter name: value
   at Microsoft.Owin.PathString..ctor(String value)
   at Orchard.OpenId.OwinMiddlewares.Google.GetOwinMiddlewares()
   at Orchard.Environment.DefaultOrchardShell.<>c.<Activate>b__16_0(IOwinMiddlewareProvider p) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 61
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Orchard.Environment.DefaultOrchardShell.Activate() in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 64
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 210
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__41_1(ShellSettings settings) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 167
2017-01-28 18:07:25,114 [12] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default after 1 retries. [http://localhost:30321/OrchardLocal/Users/Account/LogOn?ReturnUrl=%2FOrchardLocal%2F]
2017-01-28 18:13:00,939 [11] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default Attempt number: 0 [(null)]
System.ArgumentException: The path must start with a '/' followed by one or more characters.
Parameter name: value
   at Microsoft.Owin.PathString..ctor(String value)
   at Orchard.OpenId.OwinMiddlewares.Google.GetOwinMiddlewares()
   at Orchard.Environment.DefaultOrchardShell.<>c.<Activate>b__16_0(IOwinMiddlewareProvider p) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 61
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Orchard.Environment.DefaultOrchardShell.Activate() in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 64
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 210
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__41_1(ShellSettings settings) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 167
2017-01-28 18:13:02,528 [11] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default after 1 retries. [(null)]
2017-01-28 18:13:03,580 [11] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default Attempt number: 0 [(null)]
System.ArgumentException: The path must start with a '/' followed by one or more characters.
Parameter name: value
   at Microsoft.Owin.PathString..ctor(String value)
   at Orchard.OpenId.OwinMiddlewares.Google.GetOwinMiddlewares()
   at Orchard.Environment.DefaultOrchardShell.<>c.<Activate>b__16_0(IOwinMiddlewareProvider p) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 61
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Orchard.Environment.DefaultOrchardShell.Activate() in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 64
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 210
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__41_1(ShellSettings settings) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 167
2017-01-28 18:13:05,084 [11] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default after 1 retries. [(null)]
2017-01-28 18:13:05,997 [14] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default Attempt number: 0 [http://localhost:30321/OrchardLocal/]
System.ArgumentException: The path must start with a '/' followed by one or more characters.
Parameter name: value
   at Microsoft.Owin.PathString..ctor(String value)
   at Orchard.OpenId.OwinMiddlewares.Google.GetOwinMiddlewares()
   at Orchard.Environment.DefaultOrchardShell.<>c.<Activate>b__16_0(IOwinMiddlewareProvider p) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 61
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at Orchard.Environment.DefaultOrchardShell.Activate() in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:line 64
   at Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellContext context) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 210
   at Orchard.Environment.DefaultOrchardHost.<CreateAndActivateShells>b__41_1(ShellSettings settings) in E:\orchard111-zg\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:line 167
2017-01-28 18:13:07,560 [14] Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: Default after 1 retries. [http://localhost:30321/OrchardLocal/]

**Comment by infofromca** [comment]
rosloved: redo from empty
this time change  CallbackPath to
http://localhost:30321/OrchardLocal/Users/Account/LogonCallback
result: ok

**Comment by infofromca** [comment]
but now produce another issue

**Comment by infofromca** [comment]
still problem
https://github.com/OrchardCMS/Orchard/issues/7546

**Comment by infofromca** [comment]
disable output cache also got the same error
![disable-cache](https://cloud.githubusercontent.com/assets/297675/22401229/d89bd2ec-e599-11e6-82c8-b044da71332d.png)

**Comment by sebastienros** [comment]
I assume the other issues explain what the problem is.
