### ISSUE TITLE
1.10.2 Error with System.Drawing

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard#7651]
I tried to install the latest version of Orchard 1.10.2. 

I can see the front but f I am going to /admin, there is this error in logs, occurring multiple times about 'System.Drawing':

2017-04-07 10:23:00,709 [108] Orchard.Environment.Extensions.Compilers.DefaultExtensionCompiler - (null) - Assembly reference 'Orchard.MediaLibrary' for project '/Modules/Markdown/Markdown.csproj' cannot be loaded [(null)]
2017-04-07 10:23:00,787 [108] Orchard.Environment.DefaultAssemblyLoader - (null) - Error loading assembly 'System.Drawing' [(null)]
System.IO.FileNotFoundException: Could not load file or assembly 'System.Drawing' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Drawing'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Orchard.Environment.DefaultAssemblyLoader.LoadWorker(String shortName, String fullName)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orchard.Environment.DefaultAssemblyLoader.Load(String assemblyName)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2017-04-07 10:23:00,787 [108] Orchard.Environment.Extensions.Compilers.DefaultExtensionCompiler - (null) - Assembly reference 'System.Drawing' for project '/Modules/Orchard.Tokens/Orchard.Tokens.csproj' cannot be loaded [(null)]
2017-04-07 10:23:00,787 [108] Orchard.Environment.DefaultAssemblyLoader - (null) - Error loading assembly 'Orchard.Tokens' [(null)]
System.IO.FileNotFoundException: Could not load file or assembly 'Orchard.Tokens' or one of its dependencies. The system cannot find the file specified.
File name: 'Orchard.Tokens'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Orchard.Environment.DefaultAssemblyLoader.LoadWorker(String shortName, String fullName)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orchard.Environment.DefaultAssemblyLoader.Load(String assemblyName)

**Comment by agriffard** [comment]
Same error if I launch the Orchard.Web retrieved from the MSDeploy/Orchard.Web.10.2.....zip on teamCity CI on my dev machine.

**Comment by sebastienros** [comment]
It works fine for me. I copy/pasted the ms deploy version from teamcity directly to a brand new Web app on Azure and can get to the admin without any issues.

![image](https://cloud.githubusercontent.com/assets/1165805/24885867/c2609e6e-1e05-11e7-8602-577c9cfe68fa.png)

**Comment by agriffard** [comment]
The error is not occurring anymore. 
I don't understand what changed but I managed to upgrade my site and orchardproject.fr.
