### ISSUE TITLE
NHibernate issues in orchard 1.8.2

### ISSUE THREAD

**Issue by ankitchugh1987** [OrchardCMS/Orchard#7700]
We have upgraded the orchard framework from 1.8.1 to orchard 1.8.2 But still we are getting NHibernate issues.

2017-05-17 14:05:49,470 [14] NHibernate.AdoNet.AbstractBatcher - (null) - Could not execute query: SELECT this_.Id , from ........ table
 (null)
System.InvalidOperationException: Internal connection fatal error.
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd) in c:\Users\sebros\Documents\My Projects\nhibernate-core\src\NHibernate\AdoNet\AbstractBatcher.cs:line 223
2017-05-17 14:05:49,704 [14] NHibernate.Util.ADOExceptionReporter - (null) - Internal connection fatal error.
 (null)
2017-05-17 14:05:49,704 [14] NHibernate.Util.ADOExceptionReporter - (null) - Internal connection fatal error.
 (null)
2017-05-17 14:05:49,704 [14] NHibernate.Util.ADOExceptionReporter - (null) - Internal connection fatal error.
 (null)

Anyone have any idea for the above error.

**Comment by sebastienros** [comment]
We could help you find a mitigation if you provided more details about how and when it's happening.
Then for a real solution, all the answers you will get will be to upgrade to a more recent version in case it's a bug that has been fixed in the last 2 years.

**Comment by ankitchugh1987** [comment]
Thanks sebastienros for the response. All the error details i have share in the above. This is the generic error which occurred in 15-20 when we are fetching something from orchard database.

**Comment by ankitchugh1987** [comment]
Even in the chat some of the person said me that it was 1.8 was two year old. Can you please let us know in which exact version orchard folks fix Nhibernate fatal issue. Because we want to upgrade the orchard to that specific version not the latest version.

**Comment by ankitchugh1987** [comment]
Hi sebastienros,

i am not able to reproduce the exact same issue. But i am able replicate the similar issue in our environment.

In load testing if i  Hit 10 request which are fetching some data from the Orchard by using Nhibernte. 10 parallel hits break the below code.

ABCPart settings =
ContentManager.Query<ABCPart, ABCPartRecord>().List().FirstOrDefault();

**Comment by sebastienros** [comment]
I will test that. Also you query is not optimized, you should not call `.List()`. /cc @MatteoPiovanelli-Laser

**Comment by carlwoodhouse** [comment]
@sebastienros i pointed that out on gitter but apparently this was just an example and not many records of that type. That been said if its purely getting settings it probably doesn't even need a backing record ... (was infoset in 1.8.2? - i forget)

**Comment by MatteoPiovanelli** [comment]
I am setting up the tool to do parallel tests. It will (should) work for any kind of call, since those will be set up in configuration files. 
I expect we'll be able to share a repo some time next week, with code and instructions.

**Comment by MatteoPiovanelli** [comment]
repo: https://github.com/LaserSrl/Newman-Orchard-Parallel-Tests-
preliminary tests: https://github.com/OrchardCMS/Orchard/issues/7708

@ankitchugh1987 
What we are seeing is that performances can vary widely depending on what parts are in the contents your are dealing with, depending on what "happens" for that part in its handlers and so on. What I tried so far was in creating contents, so not exactly what you are seeing, but maybe the root cause is similar. Do the parts in your content do anything special? Maybe while they are being loaded?

**Comment by ankitchugh1987** [comment]
Thank for the reply. Please find the way to re-produce.

Add constraint in Route.

 Route = new Route(
                                                         "Test/Nhibernate",
                                                         new RouteValueDictionary {
                                                                                      {"area", "Abc.NameSpace"},
                                                                                      {"controller", "Controller Name"},
                                                                                      {"action", "LogOn"}
                                                         },
                                                         new RouteValueDictionary {{ "controller", this.VerifyConstraint }},
                                                         new RouteValueDictionary {
                                                                                      {"area", "Abc.NameSpace"}
                                                         },
                                                         new MvcRouteHandler())



    public class VerifyConstraint: IVerifyConstraint
    {
         public FederationEnabledRouteConstraint(IVService settings)
        {
            this.Settings = settings;
        }

   
        protected (IVService Settings { get; private set; }

       
        public bool Match(HttpContextBase httpContext, Route route, string parameterName, RouteValueDictionary values, RouteDirection routeDirection)
        {
            return Settings.//DatabaseCall.Neable;
        }
    }

**Comment by ankitchugh1987** [comment]
If you define some database call in the route.cs it will get failed during parallel hit.

**Comment by MatteoPiovanelli** [comment]
@ankitchugh1987 It's probably qiucker if you run the script ot test things yourself, and get back here with the exceptions.

Have you tried setting the ReadUncommitted isolation level? @sebastienros told me about it yesterday. If you are not using SQL server CE it may help. To enable it, look for `Config/Sites.config` in your Orchard.Web project (that's the file in 1.10. I am not sure it's the same in 1.8). You will see some commented lines about the isolation level. Uncommenting those solved several concurrency issues I had.

**Comment by carlwoodhouse** [comment]
I think routeconstraints are singletons? so you might need to inject this as Work<IVService> ?

**Comment by sebastienros** [comment]
@ankitchugh1987 a database in a route constraint, I am not sure there could be something worse for your application. Route constraints are called on each request, and for each generated link. You should definitely preload all the data from database and use this when you build the constraint. An example is what is done in the Autoroute module to preload all the slugs.

**Comment by carlwoodhouse** [comment]
Totally agree on that; when we need to do this (not sure we do anymore) - we load them all into a singleton containing a ConcurrentDictionary on a startup/background thread and just access that in the constraints.

**Comment by sebastienros** [comment]
@carlwoodhouse side comment, unless some other service is updating the dictionary while the app is running, a simple dictionary is fine.

**Comment by carlwoodhouse** [comment]
@sebastienros true; in our scenario we potentially had handlers updating it.

**Comment by BenedekFarkas** [comment]
@ankitchugh1987 btw can you please tell why you specifically need Orchard 1.8.2 and can't upgrade to a higher version? It might be some useful information for us.
