### ISSUE TITLE
TinyMce selection error

### ISSUE THREAD

**Issue by roballred** [OrchardCMS/Orchard#7710]
I am find this error when trying to select an image while editing content in TinyMce. I see this on older and latest versions of orchard. I am not sure if browsers have updated and cause this error or something else.

DOMException: Failed to execute 'setBaseAndExtent' on 'Selection': There is no child at offset 1.
tinymce.min.js:8 Uncaught DOMException: Failed to execute 'setBaseAndExtent' on 'Selection': There is no child at offset 1.
    at N.<anonymous> (http://xxxx.azurewebsites.net/Modules/TinyMce/scripts/tinymce.min.js:8:22402)
    at t.r [as fire] (http://xxxx.azurewebsites.net/Modules/TinyMce/scripts/tinymce.min.js:7:11787)
    at N.fire (http://xxxx.azurewebsites.net/Modules/TinyMce/scripts/tinymce.min.js:8:29404)
    at N.<anonymous> (http://xxxx.azurewebsites.net/Modules/TinyMce/scripts/tinymce.min.js:8:28434)
    at t.r [as fire] (http://xxxx.azurewebsites.net/Modules/TinyMce/scripts/tinymce.min.js:7:11787)
    at N.fire (http://xxxx.azurewebsites.net/Modules/TinyMce/scripts/tinymce.min.js:8:29404)
    at f.i (http://xxxx.azurewebsites.net/Modules/TinyMce/scripts/tinymce.min.js:8:30469)
    at i (http://xxxx.azurewebsites.net/Modules/TinyMce/scripts/tinymce.min.js:2:5288)
    at HTMLBodyElement.m (http://xxxx.azurewebsites.net/Modules/TinyMce/scripts/tinymce.min.js:2:5628)

**Comment by sebastienros** [comment]
It's possible, I think there is an issue tracking a breaking change in chrome that requires an update to tinymce.

**Comment by BenedekFarkas** [comment]
I can repro this, but the error comes up when I click on an image that is already inserted into the HTML editor. In this case the image is still selected, so if I hit Delete, it is removed from the editor.
The included version is 4 years old, so an upgrade would be definitely useful.

**Comment by BenedekFarkas** [comment]
@roballred can you please check the `issue/7710` branch? It should be fixed now (to be included in the upcoming release).

**Comment by BenedekFarkas** [comment]
Fixed in c3b11fca44ddcbef5b94e513e221b09e5c671cbf
