### ISSUE TITLE
Issues in Orchard

### ISSUE THREAD

**Issue by MuraliAele** [OrchardCMS/Orchard#7803]
2017-07-29 05:57:11,114 [36] Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator - Default - IOException thrown from IContentPartDriver by RiseTekMachinary.Drivers.CatogoriesPartPartDriver
 http://www.risetekmachinery.com/robots.txt
System.IO.IOException: The process cannot access the file 'D:\home\site\wwwroot\Media\LogError\2017\07\29.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at RiseTekMachinary.Services.XrmRepository.logfile(Exception ex)
   at RiseTekMachinary.Services.XrmRepository.GetMainPageCategories()
   at RiseTekMachinary.Drivers.CatogoriesPartPartDriver.<>c__DisplayClass3.<Display>b__2()
   at Orchard.ContentManagement.Drivers.ContentPartDriver`1.<>c__DisplayClassf.<ContentShape>b__e(BuildShapeContext ctx)
   at Orchard.ContentManagement.Drivers.ContentPartDriver`1.<>c__DisplayClass15.<ContentShapeImplementation>b__14(BuildShapeContext ctx)
   at Orchard.ContentManagement.Drivers.ContentShapeResult.ApplyImplementation(BuildShapeContext context, String displayType)
   at Orchard.ContentManagement.Drivers.ContentShapeResult.Apply(BuildDisplayContext context)
   at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.<>c__DisplayClassa.<BuildDisplay>b__9(IContentPartDriver driver)
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger)

**Comment by sebastienros** [comment]
Looks like the module named `RiseTekMachinary` that we are not developing is the source of the issue.
