### ISSUE TITLE
accessing the contentmanager from a shapeprovider or filter - not allowed?

### ISSUE THREAD

**Issue by jimasp** [OrchardCMS/Orchard#7883]
Hi,

There seems to be an unwritten? rule in Orchard that you cannot (reliably) access the contentManager from a callstack topped by ShapeProviders or MVC Filters due to the autofac lifetime scopes.
I am currently having an issue with the latter.
The call works most of the time, but fails intermittently and only on deployed servers, (it always works locally).

I currently have the following code:

in MyFilter.OnActionExecuted():

```
            var workContext = filterContext.GetContext();
            var ci = layout.ContentItem; 

            var contentPart = ci.Parts.SingleOrDefault(part => part.PartDefinition.Name == ci.ContentType);
            if (contentPart != null)
            {
                var flds = contentPart.Fields;
                var myTxyField = flds.FirstOrDefault(field => field.PartFieldDefinition.Name == "MyTaxonomyField");
                if (myTxyField != null)
                {
                    // intermittent failure - see exception below
                    workContext.Layout.MyKeywords = ((TermsPart)myTxyField).Terms;
                }
            }
```

The above will call this code in TermsPart:

```
        public IEnumerable<TermPart> Terms {
            get { return TermsField.Value; }
        }
```

Which will call this lazy loader func in TermsPartHandler:

```
                field.TermsField.Loader(() => {
                    var fieldTermRecordIds = part.Record.Terms.Where(t => t.Field == tempField).Select(tci => tci.TermRecord.Id);
                    var terms = _contentManager.GetMany<TermPart>(fieldTermRecordIds, VersionOptions.Published, queryHint);
                    return terms.ToList();
                });
```

Which results in _intermittent_ failures like this on our servers:

```
<!--
Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.   at Autofac.Core.Lifetime.LifetimeScope.CheckNotDisposed()
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at lambda_method(Closure )
   at Orchard.ContentManagement.DefaultContentManager.Get(Int32 id, VersionOptions options, QueryHints hints) in c:\BuildAgent\work\2890687c35f1e582\src\Orchard\ContentManagement\DefaultContentManager.cs:line 135
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Orchard.ContentManagement.DefaultContentManager.GetMany[T](IEnumerable`1 ids, VersionOptions options, QueryHints hints) in c:\BuildAgent\work\2890687c35f1e582\src\Orchard\ContentManagement\DefaultContentManager.cs:line 0
   at Orchard.Taxonomies.Handlers.TermsPartHandler.&lt;&gt;c__DisplayClass1d.&lt;InitializerTermsLoader&gt;b__12()
   at Orchard.ContentManagement.Utilities.LazyField`1.GetValue() in c:\BuildAgent\work\2890687c35f1e582\src\Orchard\ContentManagement\Utilities\LazyField.cs:line 29
   at CallSite.Target(Closure , CallSite , Object )
   at MyFilter.OnActionExecuted(ActionExecutedContext filterContext)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.&lt;&gt;c__DisplayClass46.&lt;InvokeActionMethodFilterAsynchronouslyRecursive&gt;b__3f()
```

Please can someone explain this behaviour, and if so, is it documented anywhere? 
(I had a quick trawl through all the Orchard filters and shapeproviders and didn't see any that access a contentManager, which could suggest this is a known restriction).

As far as I can tell though, the LifetimeScope should last the length of the request and presumably the same scope object is used for the Filter and the ContentHandler, so I don't know why there is this intermittent issue with a filter. 
Unfortunately I can't debug the problem because it always works fine locally.

Perhaps more importantly - is there a workaround?
I need something that can:
1. run on every action request (custom mvc requests and content item display) - i.e. like the above filter,
2. reliably access the contentManager
3. happens _after_ the controller action (e.g. so the action can use layout flags to override the default behaviour).

**Comment by HermesSbicego-Laser** [comment]
Similar problem here, in my case it seems to be a problem of Lazy fields...

I have a `MyMVCFilter.OnResultExecuted` in which I need to transform the output stream by reproccessing the `Display` of some `shapes`. If in the razor view I try to access a Lazy Field (ie the  `ContentPickerField.ContentItems` property) the above exception is fired, because Autofac **already has disposed the WorkContext and its IContentManager**.
In the MVC filter, in order to have the ability to access a valid WorkContext, I create a new one (`WorkContextAccessor.CreateWorkContextScope`) so that I can use it in the razor view. In the specific case I could use the ContentPickerField.Ids property and then call an IContentManager.Get but I would like to have a **more generic solution** that **does not depend on how the code in the razor has been written** .

Any idea on how to solve the problem?

**Comment by sebastienros** [comment]
You definitely need a new wrokcontext instance to resolve an IContentManager. Otherwise you get a scoped instance in a singleton.

**Comment by sebastienros** [comment]
There must be other examples doing that, maybe the background tasks

**Comment by HermesSbicego-Laser** [comment]
To create a new `WorkContext `is exactly what I do, but **it doesn't solve the problem** because the ContentPickerField.ContentItems (Lazy Field) in the `Loading` method of its `Handler` uses the IContentManager injeceted in the previous Autofac Lifescope which it is already disposed when called from the view (the `Display` is called just before flushing the `Response Output`). 
What perhaps could solve the problem is to inject a new instance of all dependencies(?) - if null - during Field Lazy Loading, but I don't know if it's a good idea and how to do that **in a generic way for all Lazy Fields** if it makes sense.
