### ISSUE TITLE
Lucene index settings lock file is not properly released and cannot be accessed by application

### ISSUE THREAD

**Issue by 0liver** [OrchardCMS/Orchard#7890]
We're running around 20 sites off of a single code base that uses Orchard as its foundation. After every deployment (to all these sites) there is a handful of sites on which we have a locked **.lock** file on one of our indices. 98% of the time it's the same one (Managemen_Latest).

Here's the stacktrace:
```
System.IO.IOException: The process cannot access the file
'[...]\App_Data\Sites\Default\Management_Latest.settings.xml.lock' because it is being used by another process.
(Tried to aquire the index lock file 'Sites/Default/Management_Latest.settings.xml.lock'!)

at System.IO.__Error.WinIOError(Int32, System.String)
at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
at System.IO.StreamReader..ctor(System.String, System.Text.Encoding, Boolean, Int32, Boolean)
at System.IO.File.InternalReadAllText(System.String, System.Text.Encoding, Boolean)
at Orchard.FileSystems.LockFile.DefaultLockFileManager.IsLockedImpl(System.String) in C:\TeamCity\buildAgent\work\8eded68158648c8\src\Orchard\FileSystems\LockFile\DefaultLockFileManager.cs:line 64
at Orchard.FileSystems.LockFile.DefaultLockFileManager.TryAcquireLock(System.String, Orchard.FileSystems.LockFile.ILockFile ByRef) in C:\TeamCity\buildAgent\work\8eded68158648c8\src\Orchard\FileSystems\LockFile\DefaultLockFileManager.cs:line 24
at Discoverize.Management.Indexing.IndexingTaskExecutorDz.UpdateIndexBatch(System.String)
at Orchard.Indexing.Services.UpdateIndexScheduler.UpdateIndex(System.String)
at Orchard.Events.DelegateHelper+<>c__DisplayClass14_0`2.<BuildAction>b__0(System.Object, System.Object[]) in C:\TeamCity\buildAgent\work\8eded68158648c8\src\Orchard\Events\DelegateHelper.cs:line 116
at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(Orchard.Events.IEventHandler, System.Type, System.String, System.String, System.String, System.Collections.Generic.IDictionary`2[System.String,System.Object], System.Collections.IEnumerable ByRef) in C:\TeamCity\buildAgent\work\8eded68158648c8\src\Orchard\Events\DefaultOrchardEventBus.cs:line 79
at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(Orchard.Events.IEventHandler, System.String, System.String, System.String, System.Collections.Generic.IDictionary`2[System.String,System.Object], System.Collections.IEnumerable ByRef) in C:\TeamCity\buildAgent\work\8eded68158648c8\src\Orchard\Events\DefaultOrchardEventBus.cs:line 53
at Orchard.Events.DefaultOrchardEventBus+<NotifyHandlers>d__9.MoveNext() in C:\TeamCity\buildAgent\work\8eded68158648c8\src\Orchard\Events\DefaultOrchardEventBus.cs:line 41
at System.Linq.Buffer`1..ctor(System.Collections.Generic.IEnumerable`1[TElement])
at System.Linq.Enumerable.ToArray[TSource](System.Collections.Generic.IEnumerable`1[TSource])
at Orchard.Events.EventsInterceptor.Intercept(Castle.Core.Interceptor.IInvocation) in C:\TeamCity\buildAgent\work\8eded68158648c8\src\Orchard\Events\EventsInterceptor.cs:line 26
at Orchard.Indexing.Services.IndexingBackgroundTask.Sweep()
at Orchard.Tasks.BackgroundService.Sweep() in C:\TeamCity\buildAgent\work\8eded68158648c8\src\Orchard\Tasks\BackgroundService.cs:line 30
at Orchard.Tasks.SweepGenerator.DoWork() in C:\TeamCity\buildAgent\work\8eded68158648c8\src\Orchard\Tasks\SweepGenerator.cs:line 65
at Orchard.Tasks.SweepGenerator.Elapsed(System.Object, System.Timers.ElapsedEventArgs) in C:\TeamCity\buildAgent\work\8eded68158648c8\src\Orchard\Tasks\SweepGenerator.cs:line 50
at System.Timers.Timer.MyTimerCallback(System.Object)
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.TimerQueueTimer.CallCallback()
at System.Threading.TimerQueueTimer.Fire()
at System.Threading.TimerQueue.FireNextTimers()
```

I know this will put some of you off, but we're running on Orchard 1.7.0 with some minor tweaks and fixes here and there. In **August 2017**, we chose to update the whole source to MVC 5 and .NET Framework 4.6.1 - and since then this problem has become really annoying because it happens on up to 7 (random) sites on every deployment. We've faced this issue before, for over a year now, but at the beginning it happened only once every couple of deployments...

Weird facts:
* the locking process that Process Explorer points us to is the **w3wp** of the given app pool
* we tried waiting for the **.lock** files to disappear within the **Application_End** method -> no success
* we tried deleting the **.lock** file from within the **Application_End** method -> that would also throw the IOException

Does anyone have an idea of why this is happening or what we can do to fix this problem?

**Comment by sebastienros** [comment]
Could be the lucene module that holds the lock and doesn't release it correctly when it's disposed. It might have been fixed, you could check the history of the module first.
Look at how it handles the IFileLock service and where it should release it.

**Comment by 0liver** [comment]
Thanks, Sébastien, for getting back.

We've done about 10 iterations of trying to fix this bug until [this stackoverflow question](https://stackoverflow.com/q/25366534/177710) gave us the idea for an extreme, but working solution:
we replaced the implementation of `AppDataFolder.CreateFile(string path, string content)`:

[current Orchard source](https://github.com/OrchardCMS/Orchard/blob/6720b71cf3474a9a7b8a8cc9a99d58b1e733acfa/src/Orchard/FileSystems/AppData/AppDataFolder.cs):
```
public void CreateFile(string path, string content) { 
    using (var stream = CreateFile(path)) { 
        using (var tw = new StreamWriter(stream)) { 
            tw.Write(content); 
        } 
    } 
}
```

new implementation:
```
public void CreateFile(string path, string content) {
    var filePath = CombineToPhysicalPath(path);
    var folderPath = Path.GetDirectoryName(filePath);
    if (!Directory.Exists(folderPath))
        Directory.CreateDirectory(folderPath);

    // for existing files, just overwrite
    if (File.Exists(filePath)) {
        File.WriteAllText(filePath, content);
    }
    else {
        WriteAllTextWithTempFileAndMove(filePath, content);
    }
}

private static void WriteAllTextWithTempFileAndMove(string path, string content) {
    // generate a temp filename
    var tempPath = path + "." + Path.GetRandomFileName();

    // write the data to a temp file
    using (var tempFile = File.Create(tempPath, 4096, FileOptions.WriteThrough))
    using (var writer = new StreamWriter(tempFile)) {
        writer.Write(content);
    }

    // move to destination
    // will throw exception if destination exists
    File.Move(tempPath, path);
}
```

Since we've deployed this change, no more files are being held locked :-)

**Comment by GiuseppeMusso-Laser** [comment]
Hi Oliver, we are experiencing the same issue in our production environment so we would like to apply your solution.
Are you going to post a PR?
Or can we copy your code in our Orchard branch?
Thank you.

**Comment by 0liver** [comment]
@GiuseppeMusso-Laser:

Please go ahead and copy all you want :-)
