### ISSUE TITLE
Creating content items programmatically throws an error

### ISSUE THREAD

**Issue by kcastro18** [OrchardCMS/Orchard#7983]
Does anyone know what is the meaning of this error? 

This is the code I was running whenever I get the error:

`public string CreateContentLawyers()
        {
            IEnumerable<LawyerRecord> lawyers = _lawyerManager.GetLawyers();

            foreach (LawyerRecord l in lawyers)
            {
                var dynamicContentItem = _orchardServices.ContentManager.New(Constants.ContentTypeNames.Lawyer);
                dynamicContentItem.As<AutoroutePart>().UseCustomPattern = true;
                dynamicContentItem.As<AutoroutePart>().CustomPattern = "lawyers/" + l.BarNum;                
                dynamicContentItem.As<TitlePart>().Title = l.LastName + ", " + l.FirstName + " " + l.MiddleName + " - " + l.BarNum;
                dynamicContentItem.As<LawyerPart>().BarNum = l.BarNum;
                _orchardServices.ContentManager.Create(dynamicContentItem);                
            }           

            return "Content item lawyers created.";
        }`

`NHibernate.Exceptions.GenericADOException
  HResult=0x80131600
  Message=could not execute query
[ SELECT this_.Id as Id4_4_, this_.Number as Number4_4_, this_.Published as Published4_4_, this_.Latest as Latest4_4_, this_.Data as Data4_4_, this_.ContentItemRecord_id as ContentI6_4_4_, contentite1_.Id as Id3_0_, contentite1_.Data as Data3_0_, contentite1_.ContentType_id as ContentT3_3_0_, commonpart3_.Id as Id51_1_, commonpart3_.OwnerId as OwnerId51_1_, commonpart3_.CreatedUtc as CreatedUtc51_1_, commonpart3_.PublishedUtc as Publishe4_51_1_, commonpart3_.ModifiedUtc as Modified5_51_1_, commonpart3_.Container_id as Container6_51_1_, widgetpart2_.Id as Id55_2_, widgetpart2_.Title as Title55_2_, widgetpart2_.Position as Position55_2_, widgetpart2_.Zone as Zone55_2_, widgetpart2_.RenderTitle as RenderTi5_55_2_, widgetpart2_.Name as Name55_2_, contenttyp8_.Id as Id5_3_, contenttyp8_.Name as Name5_3_ FROM Orchard_Framework_ContentItemVersionRecord this_ inner join Orchard_Framework_ContentItemRecord contentite1_ on this_.ContentItemRecord_id=contentite1_.Id inner join Common_CommonPartRecord commonpart3_ on contentite1_.Id=commonpart3_.Id inner join Orchard_Widgets_WidgetPartRecord widgetpart2_ on contentite1_.Id=widgetpart2_.Id left outer join Orchard_Framework_ContentTypeRecord contenttyp8_ on contentite1_.ContentType_id=contenttyp8_.Id WHERE commonpart3_.Container_id in (@p0, @p1) and this_.Published = @p2 ]
  Name:cp0 - Value:3  Name:cp1 - Value:4  Name:cp2 - Value:True
[SQL: SELECT this_.Id as Id4_4_, this_.Number as Number4_4_, this_.Published as Published4_4_, this_.Latest as Latest4_4_, this_.Data as Data4_4_, this_.ContentItemRecord_id as ContentI6_4_4_, contentite1_.Id as Id3_0_, contentite1_.Data as Data3_0_, contentite1_.ContentType_id as ContentT3_3_0_, commonpart3_.Id as Id51_1_, commonpart3_.OwnerId as OwnerId51_1_, commonpart3_.CreatedUtc as CreatedUtc51_1_, commonpart3_.PublishedUtc as Publishe4_51_1_, commonpart3_.ModifiedUtc as Modified5_51_1_, commonpart3_.Container_id as Container6_51_1_, widgetpart2_.Id as Id55_2_, widgetpart2_.Title as Title55_2_, widgetpart2_.Position as Position55_2_, widgetpart2_.Zone as Zone55_2_, widgetpart2_.RenderTitle as RenderTi5_55_2_, widgetpart2_.Name as Name55_2_, contenttyp8_.Id as Id5_3_, contenttyp8_.Name as Name5_3_ FROM Orchard_Framework_ContentItemVersionRecord this_ inner join Orchard_Framework_ContentItemRecord contentite1_ on this_.ContentItemRecord_id=contentite1_.Id inner join Common_CommonPartRecord commonpart3_ on contentite1_.Id=commonpart3_.Id inner join Orchard_Widgets_WidgetPartRecord widgetpart2_ on contentite1_.Id=widgetpart2_.Id left outer join Orchard_Framework_ContentTypeRecord contenttyp8_ on contentite1_.ContentType_id=contenttyp8_.Id WHERE commonpart3_.Container_id in (@p0, @p1) and this_.Published = @p2]
  Source=NHibernate
  StackTrace:
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes)
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results)
   at NHibernate.Impl.CriteriaImpl.List(IList results)
   at NHibernate.Impl.CriteriaImpl.List[T]()
   at Orchard.ContentManagement.DefaultContentQuery.Slice(Int32 skip, Int32 count) in C:\Dev\Orchard\Orchard-1.10.2\src\Orchard\ContentManagement\DefaultContentQuery.cs:line 191
   at Orchard.ContentManagement.DefaultContentQuery.ContentQuery`1.Orchard.ContentManagement.IContentQuery<T>.List() in C:\Dev\Orchard\Orchard-1.10.2\src\Orchard\ContentManagement\DefaultContentQuery.cs:line 292
   at Orchard.Widgets.Services.WidgetsService.GetWidgets(Int32[] layerIds) in C:\Dev\Orchard\Orchard-1.10.2\src\Orchard.Web\Modules\Orchard.Widgets\Services\WidgetsService.cs:line 75
   at Orchard.Widgets.Filters.WidgetFilter.OnResultExecuting(ResultExecutingContext filterContext) in C:\Dev\Orchard\Orchard-1.10.2\src\Orchard.Web\Modules\Orchard.Widgets\Filters\WidgetFilter.cs:line 52
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)

Inner Exception 1:
SqlException: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

Inner Exception 2:
Win32Exception: The wait operation timed out
`

**Comment by ghost** [comment]
can you please format the exception ?

**Comment by kcastro18** [comment]
I'm sorry this might be a stupid question but what do you mean format the exception?

**Comment by Hazzamanic** [comment]
Paste the exception in using the 'Insert Code' option so we can read it better. The editor is also stripping parts of the exception because it thinks it is html you've pasted in.

**Comment by kcastro18** [comment]
`NHibernate.Exceptions.GenericADOException
  HResult=0x80131600
  Message=could not execute query
[ SELECT this_.Id as Id4_4_, this_.Number as Number4_4_, this_.Published as Published4_4_, this_.Latest as Latest4_4_, this_.Data as Data4_4_, this_.ContentItemRecord_id as ContentI6_4_4_, contentite1_.Id as Id3_0_, contentite1_.Data as Data3_0_, contentite1_.ContentType_id as ContentT3_3_0_, commonpart3_.Id as Id51_1_, commonpart3_.OwnerId as OwnerId51_1_, commonpart3_.CreatedUtc as CreatedUtc51_1_, commonpart3_.PublishedUtc as Publishe4_51_1_, commonpart3_.ModifiedUtc as Modified5_51_1_, commonpart3_.Container_id as Container6_51_1_, widgetpart2_.Id as Id55_2_, widgetpart2_.Title as Title55_2_, widgetpart2_.Position as Position55_2_, widgetpart2_.Zone as Zone55_2_, widgetpart2_.RenderTitle as RenderTi5_55_2_, widgetpart2_.Name as Name55_2_, contenttyp8_.Id as Id5_3_, contenttyp8_.Name as Name5_3_ FROM Orchard_Framework_ContentItemVersionRecord this_ inner join Orchard_Framework_ContentItemRecord contentite1_ on this_.ContentItemRecord_id=contentite1_.Id inner join Common_CommonPartRecord commonpart3_ on contentite1_.Id=commonpart3_.Id inner join Orchard_Widgets_WidgetPartRecord widgetpart2_ on contentite1_.Id=widgetpart2_.Id left outer join Orchard_Framework_ContentTypeRecord contenttyp8_ on contentite1_.ContentType_id=contenttyp8_.Id WHERE commonpart3_.Container_id in (@p0, @p1) and this_.Published = @p2 ]
  Name:cp0 - Value:3  Name:cp1 - Value:4  Name:cp2 - Value:True
[SQL: SELECT this_.Id as Id4_4_, this_.Number as Number4_4_, this_.Published as Published4_4_, this_.Latest as Latest4_4_, this_.Data as Data4_4_, this_.ContentItemRecord_id as ContentI6_4_4_, contentite1_.Id as Id3_0_, contentite1_.Data as Data3_0_, contentite1_.ContentType_id as ContentT3_3_0_, commonpart3_.Id as Id51_1_, commonpart3_.OwnerId as OwnerId51_1_, commonpart3_.CreatedUtc as CreatedUtc51_1_, commonpart3_.PublishedUtc as Publishe4_51_1_, commonpart3_.ModifiedUtc as Modified5_51_1_, commonpart3_.Container_id as Container6_51_1_, widgetpart2_.Id as Id55_2_, widgetpart2_.Title as Title55_2_, widgetpart2_.Position as Position55_2_, widgetpart2_.Zone as Zone55_2_, widgetpart2_.RenderTitle as RenderTi5_55_2_, widgetpart2_.Name as Name55_2_, contenttyp8_.Id as Id5_3_, contenttyp8_.Name as Name5_3_ FROM Orchard_Framework_ContentItemVersionRecord this_ inner join Orchard_Framework_ContentItemRecord contentite1_ on this_.ContentItemRecord_id=contentite1_.Id inner join Common_CommonPartRecord commonpart3_ on contentite1_.Id=commonpart3_.Id inner join Orchard_Widgets_WidgetPartRecord widgetpart2_ on contentite1_.Id=widgetpart2_.Id left outer join Orchard_Framework_ContentTypeRecord contenttyp8_ on contentite1_.ContentType_id=contenttyp8_.Id WHERE commonpart3_.Container_id in (@p0, @p1) and this_.Published = @p2]
  Source=NHibernate
  StackTrace:
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters)
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes)
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results)
   at NHibernate.Impl.CriteriaImpl.List(IList results)
   at NHibernate.Impl.CriteriaImpl.List[T]()
   at Orchard.ContentManagement.DefaultContentQuery.Slice(Int32 skip, Int32 count) in C:\Dev\Orchard\Orchard-1.10.2\src\Orchard\ContentManagement\DefaultContentQuery.cs:line 191
   at Orchard.ContentManagement.DefaultContentQuery.ContentQuery`1.Orchard.ContentManagement.IContentQuery<T>.List() in C:\Dev\Orchard\Orchard-1.10.2\src\Orchard\ContentManagement\DefaultContentQuery.cs:line 292
   at Orchard.Widgets.Services.WidgetsService.GetWidgets(Int32[] layerIds) in C:\Dev\Orchard\Orchard-1.10.2\src\Orchard.Web\Modules\Orchard.Widgets\Services\WidgetsService.cs:line 75
   at Orchard.Widgets.Filters.WidgetFilter.OnResultExecuting(ResultExecutingContext filterContext) in C:\Dev\Orchard\Orchard-1.10.2\src\Orchard.Web\Modules\Orchard.Widgets\Filters\WidgetFilter.cs:line 52
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)

Inner Exception 1:
SqlException: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

Inner Exception 2:
Win32Exception: The wait operation timed out
`

**Comment by Hazzamanic** [comment]
That kinda worked... :P

Also can you either post your code again with the code tags or edit your original post to format the code part

**Comment by Hazzamanic** [comment]
The error you've posted is coming from the widgets service trying to get the content items with a container id of 3 or 4, so I'd find those items in the database to see what is causing that issue. Regarding the code for programmatically creating a content item, I believe you will need to create the content item as a draft before you assign properties to parts etc. You can then publish the item at the end if you wish. So your code might look like this:

```
public string CreateContentLawyers()
{
	IEnumerable lawyers = _lawyerManager.GetLawyers();
	foreach (LawyerRecord l in lawyers)
	{
		var dynamicContentItem = _orchardServices.ContentManager.Create(Constants.ContentTypeNames.Lawyer, VersionOptions.Draft);
		dynamicContentItem.As<AutoroutePart>().UseCustomPattern = true;
		dynamicContentItem.As<AutoroutePart>().CustomPattern = "lawyers/" + l.BarNum;                
		dynamicContentItem.As<TitlePart>().Title = l.LastName + ", " + l.FirstName + " " + l.MiddleName + " - " + l.BarNum;
		dynamicContentItem.As<LawyerPart>().BarNum = l.BarNum; 

		_orchardServices.ContentManager.Publish(dynamicContentItem);
	}           

	return "Content item lawyers created.";
}
```
