### ISSUE TITLE
RuntimeBinderException: Cannot perform runtime binding on a null reference

### ISSUE THREAD

**Issue by nutullahkisa** [OrchardCMS/Orchard#8142]
Hello,

I have started to hit this runtime error (included below) on the server side on my published website. I do not get this error on my local copy and I have tried copying everything from my local copy to the published website in case a difference got in, but that did not fix it.

I have a custom module that presents a employee contact list and admins are able to add/edit the employee information. Some fields (first name, last name, and email) are required. In the EmployeePart.cs file I add [Required] above the property fields. This worked on my local computer and highlights that the fields need to be populated, but does not work on the published site. Once I added these is around the time that I started to get the runtime error on the published site; however, even when I remove the [Required] from the properties I am still hitting this runtime error on the published site.

Any ideas what might be causing this/how to track this down? Since this error is only on the published version, I am limited in being able to debug this (I'm not getting the error when I run the solution locally).

Thank you and I appreciate any help you can offer! Please let me know if there is any other information that I could provide that would be helpful here.

Here's what I added for the required fields in EmployeePart.cs:
  
        [Required]
        public string First {
            get { return Retrieve(x => x.First); }
            set { Store(x => x.First, value); }
        }
        [Required]
        public string Last {
            get { return Retrieve(x => x.Last); }
            set { Store(x => x.Last, value); }
        }
        [Required]
        public string Email {
            get { return Retrieve(x => x.Email); }
            set { Store(x => x.Email, value); }
        }

And here are the fields in the Employee.cshtml:

    <div class="field-label">@Html.LabelFor(x => x.First, T("First Name"))</div>
    <div class="field-editor">
        @Html.TextBoxFor(x => x.First, new { style = "width:750px", @class = "large text" })
        @Html.ValidationMessageFor(x => x.First)
    </div>

    <div class="field-label">@Html.LabelFor(x => x.Middle)</div>
    <div class="field-editor">@Html.TextBoxFor(x => x.Middle, new { style = "width:750px", @class = "large text" })</div>

    <div class="field-label">@Html.LabelFor(x => x.Last, T("Last Name"))</div>
    <div class="field-editor">
        @Html.TextBoxFor(x => x.Last, new { style = "width:750px", @class = "large text" })
        @Html.ValidationMessageFor(x => x.Last)
    </div>

    <div class="field-label">@Html.LabelFor(x => x.Email, T("Email"))</div>
    <div class="field-editor">
        @Html.TextBoxFor(x => x.Email, new { style = "width:750px", @class = "large text" })
        @Html.ValidationMessageFor(x => x.Email)
    </div>

Migration.cs

    public class Migrations : DataMigrationImpl
    {
        public int Create()
        {
            SchemaBuilder.CreateTable("EmployeeRecord", table => table
                .ContentPartRecord()
                .Column<string>("First")
                .Column<string>("Last")
                .Column<string>("Email")
                );

            ContentDefinitionManager.AlterPartDefinition("EmployeePart",
                                                     builder => builder.Attachable());

            return 1;
        }
        public int UpdateFrom1()
        {
            SchemaBuilder.AlterTable("EmployeePart", table => {table.AlterColumn("Bio", x => x.WithType(DbType.String).Unlimited()); });
            ContentDefinitionManager.AlterPartDefinition(typeof(EmployeePart).Name, part => part
               .Attachable());

            ContentDefinitionManager.AlterTypeDefinition(
            "Employee",
            t => t
                       .WithPart("EmployeePart")
                       .WithPart("CommonPart")
                       .WithPart("IdentityPart")
                       .Creatable()
            );

            return 2;
        }
    }

nResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
2018-12-04 20:21:48,104 [14] Orchard.Exceptions.DefaultExceptionPolicy - Default - An unexpected exception was caught [http://144.92.66.217/OBGYN.Directory/EmployeeAdmin/Edit/2902]
System.Exception: TargetInvocationException Zone ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object , String , String )
   at ASP._Page_Core_Shapes_Views_Message_cshtml.Execute() in c:\inetpub\wwwroot\Orchard.Web.1.10.2\Orchard\Core\Shapes\Views\Message.cshtml:line 7
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.Render(ShapeDescriptor shapeDescriptor, DisplayContext displayContext, HarvestShapeInfo harvestShapeInfo, HarvestShapeHit harvestShapeHit)
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.<>c__DisplayClass20_7.<Discover>b__14(DisplayContext displayContext)
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context)
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context)
   at Orchard.DisplayManagement.Implementation.DisplayHelper.TryInvoke(InvokeBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , Object , Object )
   at Orchard.Core.Shapes.CoreShapes.Zone(Object Display, Object Shape, TextWriter Output)
   --- End of inner exception stack trace ---
   at Orchard.DisplayManagement.Descriptors.ShapeAttributeStrategy.ShapeAttributeBindingStrategy.PerformInvoke(DisplayContext displayContext, MethodInfo methodInfo, Object serviceInstance)
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context)
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context)
   at Orchard.DisplayManagement.Implementation.DisplayHelper.TryInvoke(InvokeBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , Object )
   at ASP._Page_Themes_TheAdmin_Views_Layout_cshtml.<Execute>b__42(Object x) in c:\inetpub\wwwroot\Orchard.Web.1.10.2\Orchard\Themes\TheAdmin\Views\Layout.cshtml:line 21
   at ASP._Page_Themes_TheAdmin_Views_Layout_cshtml.Execute() in c:\inetpub\wwwroot\Orchard.Web.1.10.2\Orchard\Themes\TheAdmin\Views\Layout.cshtml:line 54
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.Render(ShapeDescriptor shapeDescriptor, DisplayContext displayContext, HarvestShapeInfo harvestShapeInfo, HarvestShapeHit harvestShapeHit)
   at Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.<>c__DisplayClass20_7.<Discover>b__14(DisplayContext displayContext)
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context)
   at Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context)
   at Orchard.DisplayManagement.Implementation.DisplayHelper.TryInvoke(InvokeBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , Object )
   at Orchard.Mvc.ViewEngines.ThemeAwareness.LayoutAwareViewEngine.<>c__DisplayClass9_0.<FindView>b__0(ViewContext viewContext, TextWriter writer, IViewDataContainer viewDataContainer)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecurs

**Comment by Skrypt** [comment]
Have you looked in the production website database that these fields are not already there with allowing a NULL value on them?

**Comment by nutullahkisa** [comment]
Thank you so much for replying. I updated the database to not allow null values (to match the fields) and that fixed the problem!
