### ISSUE TITLE
Shape tracing conflicts with JQuery plugins

### ISSUE THREAD

**Issue by AndreaPiovanelli** [OrchardCMS/Orchard#8559]
https://github.com/OrchardCMS/Orchard/blob/0973810c0998ee567d53507bbb0171cc4c04f6b2/src/Orchard.Web/Modules/Orchard.DesignerTools/Views/ShapeTracingWrapper.cshtml#L20

When Shape Tracing is active, it conflicts with several jquery plugins, raising exceptions in browser console.
Example of console error:
```
Uncaught TypeError: $(...).tmpl is not a function
    at displayTabShape (orchard-designertools-shapetracing.js:357:53)
    at selectShape (orchard-designertools-shapetracing.js:291:9)
    at HTMLDivElement.<anonymous> (orchard-designertools-shapetracing.js:297:9)
    at HTMLDivElement.dispatch (jquery-2.1.4.js:4435:1)
    at HTMLDivElement.elemData.handle (jquery-2.1.4.js:4121:1)
```

I noticed that moving js references at head solves this issue and gets shape tracing to work properly.

**Comment by sebastienros** [comment]
> solves this issue

I hope it doesn't create other problems
